/* Animal Crossing: New Leaf (Welcome amiibo) item list (FR) for Save Editor */

var ITEM_GROUPS_TRANSLATED=[

//Patterns
[
"Motif"
],

//Outside flowers
[
"tulipe rouge",
"tulipe blanche",
"tulipe jaune",
"tulipe rose",
"tulipe mauve",
"tulipe noire",
"tulipe orange",
"pensée blanche",
"pensée jaune",
"pensée rouge",
"pensée mauve",
"pensée orange",
"pensée bleue",
"cosmos blanc",
"cosmos rouge",
"cosmos jaune",
"cosmos rose",
"cosmos orange",
"cosmos noir",
"rose rouge",
"rose blanche",
"rose jaune",
"rose rose",
"rose orange",
"rose mauve",
"rose noire",
"rose bleue",
"rose dorée",
"œillet rouge",
"œillet rose",
"œillet blanc",
"lys blanc",
"lys jaune",
"lys rouge",
"lys orange",
"lys rose",
"lys noir",
"violette mauve",
"violette bleue",
"violette blanche",
"violette jaune",
"muguet",
"trèfle à 4 feuilles",
"pissenlit",
"tête de pissenlit"],

//Outside flowers (wilted)
"fanée",

//Fruit trees
[
"Pommier (taille 1)",
"Pommier (taille 2)",
"Pommier (taille 3)",
"Pommier (taille 4)",
"Pommier",
"Oranger (taille 1)",
"Oranger (taille 2)",
"Oranger (taille 3)",
"Oranger (taille 4)",
"Oranger",
"Poirier (taille 1)",
"Poirier (taille 2)",
"Poirier (taille 3)",
"Poirier (taille 4)",
"Poirier",
"Pêcher (taille 1)",
"Pêcher (taille 2)",
"Pêcher (taille 3)",
"Pêcher (taille 4)",
"Pêcher",
"Cerisier (taille 1)",
"Cerisier (taille 2)",
"Cerisier (taille 3)",
"Cerisier (taille 4)",
"Cerisier"
],

//More trees
[
"Bambou mort???",
"Arbre mort",
"Arbre coupé (taille 1)",
"Arbre coupé (taille 2)",
"Arbre coupé (taille 3)",
"Souche d'arbre",
"Souche d'arbre (coeur)",
"Souche d'arbre (papillon)",
"Souche d'arbre (agrûme)",
"Souche d'arbre (Ginkgo)",
"Souche d'arbre (croix)",
"Souche d'arbre (triforce)",
"Cèdre coupé (taille 1)",
"Cèdre coupé (taille 2)",
"Cèdre coupé (taille 3)",
"Souche de cèdre",
"Souche de cèdre (étoile)",
"Souche de cèdre (chat)",
"Souche de cèdre (fleur)",
"Souche de cèdre (feuille)",
"Souche de cèdre (note musicale)",
"Souche de cèdre",
,
,
,
,
,
,
,
"Arbre (taille 1)",
"Arbre (taille 2)",
"Arbre (taille 3)",
"Arbre (taille 4)",
"Arbre",
"Cèdre (taille 1)",
"Cèdre (taille 2)",
"Cèdre (taille 3)",
"Cèdre (taille 4)",
"Cèdre",
"Cocotier (taille 1)",
"Cocotier (taille 2)",
"Cocotier (taille 3)",
"Cocotier (taille 4)",
"Cocotier",
"Bananier (taille 1)",
"Bananier (taille 2)",
"Bananier (taille 3)",
"Bananier (taille 4)",
"Bananier",
"Bambou (taille 1)",
"Bambou (taille 2)",
"Bambou (taille 3)",
"Bambou"
],

//More trees (2)
[
"Arbre à durian (taille 1)",
"Arbre à durian (taille 2)",
"Arbre à durian (taille 3)",
"Arbre à durian (taille 4)",
"Durian",
"Citronnier (taille 1)",
"Citronnier (taille 2)",
"Citronnier (taille 3)",
"Citronnier (taille 4)",
"Citronnier",
"Arbre à litchi (taille 1)",
"Arbre à litchi (taille 2)",
"Arbre à litchi (taille 3)",
"Arbre à litchi (taille 4)",
"Arbre à litchi",
"Manguier (taille 1)",
"Manguier (taille 1)",
"Manguier (taille 1)",
"Manguier (taille 1)",
"Manguier",
"Abre à Kaki (taille 1)",
"Abre à Kaki (taille 2)",
"Abre à Kaki (taille 3)",
"Abre à Kaki (taille 4)",
"Arbre à Kaki",
"Arbre à clochettes (taille 1)",
"Arbre à clochettes (taille 2)",
"Arbre à clochettes (taille 3)",
"Arbre à clochettes (taille 4)",
"Arbre à clochettes",
"Arbre (objet)",
"Arbre (abeilles)",
"Arbre (clochettes 1)",
"Arbre (clochettes 2)",
"Arbre (oeuf)",
"Cèdre (objet)",
"Cèdre (abeilles)",
"Cèdre (clochettes 1)",
"Cèdre (clochettes 2)"],

//Bushes
[
"Houx (taille 1)",
"Houx (taille 2)",
"Houx",
"Azalée rose (taille 1)",
"Azalée rose (taille 2)",
"Azalée rose",
"Azalée blanche (taille 1)",
"Azalée blanche (taille 2)",
"Azalée blanche",
"Hortensia bleu (taille 1)",
"Hortensia bleu (taille 2)",
"Hortensia bleu",
"Hortensia rose (taille 1)",
"Hortensia rose (taille 2)",
"Hortensia rose",
"Hibiscus rouge (taille 1)",
"Hibiscus rouge (taille 2)",
"Hibiscus rouge",
"Hibiscus jaune (taille 1)",
"Hibiscus jaune (taille 2)",
"Hibiscus jaune",
"Osmanthus (taille 1)",
"Osmanthus (taille 2)",
"Osmanthus"
],

//Weeds
[],

//Weeds (2)
[],

//Rocks
[],

//Uncategorized
[],

//Fruit
[
"pomme",
,
"poire",
"pêche",
"cerise",
"noix de coco",
,
"citron",
"litchi",
"mangue",
"kaki",
"banane",
"pousse de bambou",
"pomme parfaite",
"orange parfaite",
"poire parfaite",
"pêche parfaite",
"cerise parfaite",
"pomme pourrie",
"orange pourrie",
"poire pourrie",
"pêche pourrie",
"cerise pourrie"
],

//Fruits
[
"lot de pommes",
"lot d'oranges",
"lot de poires",
"lot de pêches",
"lot de cerises",
"lot de noix de coco",
"lot de durians",
"lot de citrons",
"lot de litchis",
"lot de mangues",
"lot de kakis",
"lot de bananes",
"lot pousses bambou",
"lot pommes parfaites",
"lot orang. parfaites",
"lot poires parfaites",
"lot pêches parfaites",
"lot ceris. parfaites"
],

//Garden
[
"fossile",
"engrais",
"arbrisseau",
"jeune cèdre",
"pousse de houx",
"pousse d'azalée rose",
"pous. azalée blanche",
"pous. hortensia bleu",
"pous. hortensia rose",
"pous. hibiscus rouge",
"pous. hibiscus jaune",
"pousse d'osmanthus",
"cadeau",
,
"sac tulipes rouges",
"sac tulipes blanches",
"sac tulipes jaunes",
"sac de tulipes roses",
"sac tulipes mauves",
"sac tulipes noires",
"sac tulipes orange",
"sac pensées blanches",
"sac pensées jaunes",
"sac pensées rouges",
"sac pensées mauves",
"sac pensées orange",
"sac pensées bleues",
"sac de cosmos blancs",
"sac de cosmos rouges",
"sac de cosmos jaunes",
"sac de cosmos roses",
"sac de cosmos orange",
"sac de cosmos noirs",
"sac de roses rouges",
"sac roses blanches",
"sac de roses jaunes",
"sac de roses roses",
"sac de roses orange",
"sac de roses mauves",
"sac de roses noires",
"sac de roses bleues",
"sac de roses dorées",
"sac d'œillets rouges",
"sac d'œillets roses",
"sac d'œillets blancs",
"sac de lys blancs",
"sac de lys jaunes",
"sac de lys rouges",
"sac de lys orange",
"sac de lys roses",
"sac de lys noirs",
"sac violettes mauves",
"sac violettes bleues",
"sac violet. blanches",
"sac violettes jaunes"
],

//Items
[
"papier cadeau",
"remède",
"cœur choco",
"coq. huître perlière",
"coquille de conque",
"coq. bénitier géant",
"branche de corail",
"coq. peigne de vénus",
"coquille de pétoncle",
"coq. escargot de mer",
"coq. de porcelaine",
"clypéastre",
"coquille d'huître",
"bonbon",
"sucette",
"champignon élégant",
"champignon rond",
"champignon maigre",
"champignon plat",
"champignon rare",
"champignon célèbre",
"rayon de miel",
"piège",
"piège discret",
"pépite d'or",
"pépite d'argent",
"rubis",
"saphir",
"émeraude",
"améthyste",
"plaquette de beurre",
"bouteille de lait",
"bouteille vinaigre",
"paquet de farine",
"pot de sucre",
"pièce de 100",
"pièce de 200",
"pièce de 300",
"pièce de 400",
"pièce de 500",
"pièce de 600",
"pièce de 700",
"pièce de 800",
"pièce de 900",
"sac de 1 000",
"sac de 2 000",
"sac de 3 000",
"sac de 4 000",
"sac de 5 000",
"sac de 6 000",
"sac de 7 000",
"sac de 8 000",
"sac de 9 000",
"sac de 10 000",
"sac de 11 000",
"sac de 12 000",
"sac de 13 000",
"sac de 14 000",
"sac de 15 000",
"sac de 16 000",
"sac de 17 000",
"sac de 18 000",
"sac de 19 000",
"sac de 20 000",
"sac de 21 000",
"sac de 22 000",
"sac de 23 000",
"sac de 24 000",
"sac de 25 000",
"sac de 26 000",
"sac de 27 000",
"sac de 28 000",
"sac de 29 000",
"sac de 30 000",
"sac de 31 000",
"sac de 32 000",
"sac de 33 000",
"sac de 34 000",
"sac de 35 000",
"sac de 36 000",
"sac de 37 000",
"sac de 38 000",
"sac de 39 000",
"sac de 40 000",
"sac de 41 000",
"sac de 42 000",
"sac de 43 000",
"sac de 44 000",
"sac de 45 000",
"sac de 46 000",
"sac de 47 000",
"sac de 48 000",
"sac de 49 000",
"sac de 50 000",
"sac de 51 000",
"sac de 52 000",
"sac de 53 000",
"sac de 54 000",
"sac de 55 000",
"sac de 56 000",
"sac de 57 000",
"sac de 58 000",
"sac de 59 000",
"sac de 60 000",
"sac de 61 000",
"sac de 62 000",
"sac de 63 000",
"sac de 64 000",
"sac de 65 000",
"sac de 66 000",
"sac de 67 000",
"sac de 68 000",
"sac de 69 000",
"sac de 70 000",
"sac de 71 000",
"sac de 72 000",
"sac de 73 000",
"sac de 74 000",
"sac de 75 000",
"sac de 76 000",
"sac de 77 000",
"sac de 78 000",
"sac de 79 000",
"sac de 80 000",
"sac de 81 000",
"sac de 82 000",
"sac de 83 000",
"sac de 84 000",
"sac de 85 000",
"sac de 86 000",
"sac de 87 000",
"sac de 88 000",
"sac de 89 000",
"sac de 90 000",
"sac de 91 000",
"sac de 92 000",
"sac de 93 000",
"sac de 94 000",
"sac de 95 000",
"sac de 96 000",
"sac de 97 000",
"sac de 98 000",
"sac de 99 000",
"œuf terrestre",
"œuf végétal",
"œuf minéral",
"œuf aérien",
"ticket surprise",
"top-ticket surprise"
],

//Mushroomized furniture
[
"mur forêt (mushroomized)",
"sol forêt (mushroomized)",
"lit champi (mushroomized)",
"commode champi (mushroomized)",
"buffet champi (mushroomized)",
"chaise champi (mushroomized)",
"siège champi (mushroomized)",
"table champi (mushroomized)",
"table basse champi (mushroomized)",
"lampe champi (mushroomized)",
"lampe mur champi (mushroomized)",
"télé champi (mushroomized)",
"portemanteau champi (mushroomized)"
],

//Songs
[
"Chorale de Kéké",
"Marche de Kéké",
"Valse de Kéké",
"Swing de Kéké",
"Jazz de Kéké",
"Fusion Kéké",
"Étude de Kéké",
"Berceuse de Kéké",
"Aria de Kéké",
"Samba de Kéké",
"Bossa de Kéké",
"Calypso de Kéké",
"Salsa de Kéké",
"Mambo de Kéké",
"Reggae de Kéké",
"Ska Kéké",
"Tango de Kéké",
"Virelai Kéké",
"Ukulélé Kéké",
"Kéké le verni",
"El Condor Kéké",
"Kéké balalaïka",
"Kéké l'Empereur",
"Cheb Kéké",
"Ali Farka Kéké",
"Folk Kéké",
"Rock Kéké",
"Bouge avec Kéké",
"Ragtime Kéké",
"Gumbo Kéké",
"Le Kéké Funk",
"Kéké blues",
"Kéké soul",
"Soul de Kéké",
"Kéké R&B",
"Romance Kéké",
"Drum & bass Kéké",
"Technopop Kéké",
"DJ Kéké",
"Moi et juste moi",
"Country Kéké",
"Kéké à la plage",
"Ballade de Kéké",
"Tovaritch Kéké",
"Complainte Kéké",
"Kéké route 66",
"Requiem de Kéké",
"Far West Kéké",
"M. Kéké",
"Kéké café",
"Kéké académie",
"Señor Kéké",
"Rengaine de Kéké",
"Je vous aime",
"2 jours plus tôt",
"Chez moi",
"Vie de forêt",
"Limite",
"Réfléchir",
"Kéké Dixie",
"Kéké marathon",
"Kéké King",
"Chant montagnard",
"Chant marin",
"Napolitaine",
"La pente",
"Rockabilly Kéké",
"Agent Kéké",
"Parade Kéké",
"Kéké metal",
"Vieux biscuits",
"Floraison",
"Errance",
"Kéké House",
"Sonate Kéké",
"Psykéké",
"Flânerie Kéké",
"Kéké des îles",
"Space Kéké",
"Kéké star",
"Maharadjah Kéké",
"Kéké bohême",
"Milonga Kéké",
"Groove Kéké",
"Shamisen Kéké",
"Flamenco Kéké",
"Slow Kéké",
"Bubblegum Kéké",
"Synthé Kéké",
"Disco Kéké",
"Anniversaire Kéké"
],

//Songs (2)
,

//Songs (seashell player)
,

//Paper
[
"papier papillon",
"papier par avion",
"carte de vœux",
"papier dentelle",
"papier nuages",
"papier pétales",
"papier flocons",
"papier érable",
"papier lignes",
"papier calepin",
"papier fleuri",
"papier à pois",
"papier ancien",
"papier ruban",
"papier brillant",
"papier vigne",
"papier officiel",
"papier Yétiti",
"papier cartes",
"papier léopard",
"papier vache",
"papier treillis",
"papier hamburger",
"papier piano",
"papier Nook",
"papier anniversaire",
"papier trèfle",
"papier scolaire",
"papier cœur",
"papier irisé",
"papier égyptien",
"papier nénuphar",
"papier carreaux",
"papier mosaïque",
"papier sélect",
"papier ville",
"papier Chine",
"papier océan",
"papier d'usine",
"papier artifice",
"papier floral",
"papier champignon",
"papier étoile",
"papier musique",
"papier bains",
"papier SMB3",
"papier sympa",
"papier forêt",
"papier bulles",
"papier fleurs",
"papier tartan",
"papier plaid",
"papier citron",
"papier cratère",
"papier joyaux",
"papier géométrie",
"papier sud-ouest",
"papier astral",
"papier chic",
"papier poisson",
"papier Halloween",
"papier Rounard",
"papier Thibou",
"papier bureau poste",
"papier caravanerie",
"papier Nook Immo",
"papier Nintendo",
"papier musical"
],

//Turnips
[
"lot de 10 navets",
"lot de 20 navets",
"lot de 30 navets",
"lot de 40 navets",
"lot de 50 navets",
"lot de 60 navets",
"lot de 70 navets",
"lot de 80 navets",
"lot de 90 navets",
"lot de 100 navets",
"lot navets pourris"
],

//Bugs
[
"piéride de la rave",
"citrin",
"machaon",
"papilio bianor",
"monarque",
"morpho bleu",
"agrias",
"brookiana",
"ornithoptère",
"papillon de nuit",
"coscinocera hercules",
"abeille naine",
"abeille",
"acrida cinerea",
"criquet pèlerin",
"criquet",
"mante religieuse",
"mante orchidée",
"cigale cercope",
"cigale hyalessa",
"cigale géante",
"cigale cicadelle",
"cigale higurashi",
"mue de cigale",
"laternaria",
"demoiselle",
"anax napolitain",
"cordulégastre",
"libellule géante",
"fourmi",
"patineur",
"dytique",
"punaise",
"escargot",
"grillon des prés",
"grillon du Midi",
"sauterelle",
"taupe-grillon",
"phyllie",
"phasme",
"psyché",
"coccinelle",
"mormolyce",
"longicorne",
"cicindèle",
"bousier",
"ligie",
"bernard-l'ermite",
"luciole",
"nitidule",
"scarabée",
"bupreste",
"lucane miyama",
"lucane inclinatus",
"lucane cerf-volant",
"lucane copris irisé",
"lucane cyclommatus",
"lucane lamprima",
"scarabée kabuto",
"scarabée Atlas",
"scarabée éléphant",
"scarabée Hercule",
"scarabée Goliath",
"puce",
"cloporte",
"moustique",
"mouche",
"scutigère",
"mille-pattes",
"araignée",
"tarentule",
,
"flocon de neige",
"plume rouge",
"plume bleue",
"plume verte",
"plume jaune",
"plume violette",
"plume blanche",
"plume rose",
"plume irisée",
"amulette"
],

//Fish
[
"bouvière",
"chevaine",
"carassin",
"vandoise",
"barbeau",
"carpe",
"carpe koï",
"poisson rouge",
"cyprin doré",
"fondule barré",
"écrevisse",
"tortue trionyx",
"têtard",
"grenouille",
"gobie d'eau douce",
"loche d'étang",
"silure",
"anguille",
"tête-de-serpent",
"crapet",
"perche jaune",
"bar",
"brochet",
"éperlan",
"ayu",
"saumon rose",
"omble",
"truite",
"dai yu",
"saumon",
"saumon roi",
"crabe chinois",
,
"poisson docteur",
"poisson-ange",
"néon bleu",
,
,
"dorade",
,
"arapaïma",
"bichir",
"clione",
"hippocampe",
"poisson-clown",
"poisson chirurgien",
"poisson-papillon",
"napoléon",
"poisson-scorpion",
"poisson-ballon",
"poisson-porc-épic",
"chinchard",
"scarus",
"bar commun",
"vivaneau",
"limande",
"cardeau",
"calmar",
"murène",
"murène ruban bleue",
"poisson lanterne",
"thon",
"marlin bleu",
"carangue grosse tête",
"raie",
"lune de mer",
"requin marteau",
"requin",
"requin scie",
"requin-baleine",
"poisson-ruban",
"cœlacanthe",
"boîte vide",
"godasse",
"vieux pneu",
"œuf aquatique"
],

//Marine creatures
[
"wakame",
"algue raisin de mer",
"oursin",
"balane",
"huître",
"turbo",
"ormeau",
"oreille de mer",
"palourde",
"huître perlière",
"pétoncle",
"anémone de mer",
"étoile de mer",
"concombre de mer",
"limace de mer",
"ver plat",
"crevette-mante",
"crevette nordique",
"crevette tigrée",
"langouste",
"homard",
"crabe des neiges",
"crabe velu",
"crabe royal",
"crabe-araignée géant",
"poulpe",
"anguille de jardin",
"nautile",
"limule",
"bathynome géant",
"œuf marin"
],

//Wallpaper
[
"mur teck",
"mur cœur",
"mur chic",
"mur ranch",
"mur rotin",
"mur bleu",
"mur moderne",
"mur royal",
"mur vert",
"mur chalet",
"mur enfant",
"mur robot",
"mur Yétiti",
"mur forêt",
"mur carnaval",
"mur œuf",
"mur Halloween",
"mur dindon",
"mur festif",
"mur princesse",
"mur Carla",
"mur bonbons",
"mur somptueux",
"vue Far West",
"décor lunaire",
"bâche bleue",
"mur gymnase",
"clôture patio",
"mur salle de jeu",
"mur front de mer",
"mur labo",
"mur bicolore",
"mur de bain",
"mur pastel",
"mur petit salon",
"mur psyché",
"mur kitsch",
"mur groovy",
"mur backgammon",
"mur mosaïque",
"mur frise bleue",
"crépi jaune",
"mur rustique",
"mur ornementé",
"mur agrume",
"mur de roses",
"mur de briques",
"mur shôji",
"mur paravent",
"mur salon de thé",
"mur papier de riz",
"clôture bambous",
"mur mortier",
"mur de pierre",
"mur en béton",
"mur de cave",
"mur baraquement",
"mur en lambris",
"mur de fleurs",
"rideau de perles",
"mur studio",
"mur de manoir",
"mur pro",
"mur plaza",
"mur tonnelle",
"mur ouvragé",
"mur shogun",
"fenêtre cintrée",
"mur en bambou",
"mur de lierre",
"mur hiéroglyphe",
"mur magnifique",
"mur perse",
"mur d'usine",
"mur bibliothèque",
"mur illusion",
"vue prairie",
"vue tropiques",
"vue désert",
"mur grillagé",
"rangée d'arbres",
"mur ciel",
"mur ville",
"mur terreux",
"mur ordinaire",
"mur miteux",
"mur Mario",
"mur lugubre",
"mur à pois",
"mur délabré",
"mur sport",
"mur d'or",
"mur jungle",
"mur fonds marins",
"mur fossiles",
"mur paintball",
"mur marin pop",
"mur glace",
"mur négligé",
"mur science-fiction",
"mur rococo",
"mur papillons",
"mur bois moderne",
"mur sirène",
"mur design",
"mur cartes",
"mur rayures",
"mur nordique",
"mur neutre",
"mur piste de ski",
"mur ballons",
"mur astro",
"mur fleurs pop",
"mur fromage",
"mur carrelé rouge",
"mur labyrinthe",
"mur automne",
"mur palais",
"mur fête",
"mur pattes",
"mur montagnes",
"mur gratte-ciel",
"mur salle d'expo",
"mur musée",
"mur agenda",
"mur recyclage",
"mur supérette",
"mur supermarché",
"mur brico",
"mur Galeries",
"mur Galeries Carla",
"mur Galeries Carla (2)",
"mur Galeries Carla (3)",
"mur pans blancs",
"mur hall",
"mur carreaux blancs",
"mur stade",
"mur vitres de train",
"mur salle d'attente",
"mur poutres en fer",
"mur rideaux de café",
"mur briques blanches",
"mur forêt de bambou",
"mur rizière",
"mur volcan",
"mur horizon marin",
"mur Hello Kitty",
"mur My Melody",
"mur Pompompurin",
"mur Kiki & Lala",
"mur Cinnamoroll",
"mur Kerokerokeroppi",
"mur Zelda",
"mur encré",
"mur TV-Chromapolis",
"mur Puzzle League",
"mur Fueki",
,
"mur pois et nœuds"
],

//Carpets
[
"tapis teck",
"tapis cœur",
"tapis rustique",
"parquet ranch",
"sol rotin",
"moquette bleue",
"sol moderne",
"tapis royal",
"carpette verte",
"carpette chalet",
"tapis d'enfant",
"sol robot",
"tapis Yétiti",
"sol forêt",
"sol carnaval",
"sol œuf",
"tapis Halloween",
"tapis dindon",
"tapis festif",
"tapis princesse",
"tapis Carla",
"sol bonbons",
"parquet somptueux",
"sol Far West",
"sol lunaire",
"sol route barrée",
"tapis de ring",
"gazon patio",
"tapis de jeu",
"sol pont de navire",
"sol labo",
"marqueterie",
"carrelage bain",
"carpette pastel",
"carrelage pavés",
"sol céramique",
"carrelage damier",
"carrelage kitsch",
"carrelage rouge",
"sol mosaïque",
"tapis échiquier",
"carrelage plaza",
"dallage palais",
"sol shogun",
"lino cuisine",
"sol pavé",
"lino gris",
"sol tatamis",
"tatami",
"tapis moussu",
"jardin zen",
"sol ardoises",
"sol en béton",
"sol de cave",
"parquet ouvragé",
"sol vermoulu",
"sol de cuisine",
"sol studio",
"revêtement pro",
"carpette manoir",
"tapis fastueux",
"carpette décorée",
"tapis fantaisie",
"tapis magnifique",
"carpette perse",
"tapis en tartan",
"tapis rond",
"tapis agrume",
"peau de vache",
"parquet bouleau",
"parquet abîmé",
"sol en bambou",
"sol en acier",
"tapis de paille",
"sol hiéroglyphe",
"sol illusion",
"sol pâquerettes",
"sol tropical",
"sol désert",
"sol sable",
"sol trottoir",
"sol nuages",
"sol ordinaire",
"sol miteux",
"revêtement blocs",
"tapis lugubre",
"sol délabré",
"sol sport",
"tapis d'or",
"sol marelle",
"sol fleuri",
"sol jungle",
"sol fonds marins",
"sol fossiles",
"sol paintball",
"tapis coccinelle",
"sol glace",
"tapis négligé",
"sol science-fiction",
"sol bois moderne",
"tapis sirène",
"tapis design",
"tapis cartes",
"tapis rayures",
"sol neutre",
"sol piste de ski",
"sol ballons",
"sol astro",
"tapis fleur pop",
"sol marin pop",
"sol fromage",
"sol labyrinthe",
"sol automne",
"sol rococo",
"tapis nordique",
"sol agenda",
"tapis à pois",
"sol salle d'expo",
"sol musée",
"sol recyclage",
"sol supérette",
"sol supermarché",
"sol brico",
"sol Galeries",
"sol Galeries Carla",
"sol Galeries Carla (2)",
"sol Galeries Carla (3)",
"sol terrasse",
"sol jaune",
"sol bois mixte",
"sol bois rose",
"sol bois naturel",
"sol dalles pierre",
"parquet croisé",
"sol carreaux blancs",
"moquette dalles",
"sol arches briques",
"sol pierre naturelle",
"sol terre cuite",
"sol tatamis carrés",
"sol chevrons",
"sol couloir d'école",
"sol eau",
"sol ruelle",
"sol vestibule",
"sol champ",
"sol galaxie",
"sol lave",
"sol taches d'huile",
"sol carreaux luxe",
"parquet mosaïque",
"sol plage de sable",
"sol terre",
"sol planches",
"sol bois blanc",
"sol Hello Kitty",
"sol My Melody",
"sol Pompompurin",
"sol Kiki & Lala",
"sol Cinnamoroll",
"sol Kerokerokeroppi",
"sol Zelda",
"sol encré",
"sol TV-Chromapolis",
"sol Puzzle League",
"sol Fueki",
"carrelage musée",
"sol observatoire"
],

//Shirts
[
"t-shirt nº 1",
"t-shirt nº 2",
"t-shirt nº 3",
"t-shirt nº 4",
"t-shirt nº 5",
"t-shirt nº 6",
"t-shirt nº 7",
"t-shirt nº 8",
"t-shirt nº 9",
"t-shirt pattes",
"t-shirt marguerite",
"t-shirt tulipe",
"t-shirt cerises",
"t-shirt crâne",
"t-shirt flèche",
"t-shirt éclair",
"t-shirt MVP",
"t-shirt BB",
"t-shirt poisson",
"t-shirt rainette",
"t-shirt ours",
"t-shirt lapin",
"pull lapin",
"t-shirt éléphant",
"t-shirt pique",
"t-shirt carreau",
"t-shirt trèfle",
"t-shirt cœur",
"t-shirt étoile",
"t-shirt amibe",
"t-shirt A",
"pull 1",
"pull 2",
"pull 3",
"pull 4",
"pull 5",
"pull 23",
"pull 67",
"t-shirt Mario",
"t-shirt Luigi",
"t-shirt nuages",
"t-shirt nouveau",
"t-shirt aurore",
"t-shirt brume",
"t-shirt couchant",
"t-shirt abysse",
"t-shirt pêche",
"t-shirt irisé",
"t-shirt cône",
"t-shirt batik orange",
"t-shirt batik mauve",
"t-shirt batik vert",
"t-shirt batik bleu",
"t-shirt batik rouge",
"t-shirt pavé",
"t-shirt café",
"t-shirt damier",
"t-shirt carrés bleu",
"t-shirt carrés rouge",
"t-shirt pied de coq",
"t-shirt p. coq brun",
"t-shirt rugby",
"t-shirt raies vert",
"t-shirt raies orange",
"t-shirt raies mauve",
"t-shirt beatnik",
"t-shirt barre",
"t-shirt marin",
"pull marin",
"t-shirt Rome",
"t-shirt bagnard",
"t-shirt basque",
"t-shirt tartan jaune",
"t-shirt automne",
"t-shirt tartan bleu",
"t-shirt pimpant",
"t-shirt filet",
"t-shirt grille bleu",
"t-shirt grille rouge",
"t-shirt losange",
"t-shirt rouge & noir",
"t-shirt Toad",
"t-shirt noir à pois",
"t-shirt blanc à pois",
"t-shirt à pois roses",
"t-shirt points",
"t-shirt bonbons",
"t-shirt pois orange",
"t-shirt pois cyan",
"t-shirt rayures bleu",
"t-shirt ray. jaune",
"t-shirt rayures brun",
"t-shirt ray. blanc",
"t-shirt course",
"t-shirt berlingot",
"t-shirt rallye",
"t-shirt course 6",
"t-shirt vertige",
"t-shirt barbier",
"t-shirt nappe jade",
"t-shirt nappe bleu",
"t-shirt vichy menthe",
"t-shirt vichy sorbet",
"t-shirt vichy rose",
"t-shirt vichy jaune",
"t-shirt vichy vert",
"t-shirt tartan mauve",
"t-shirt tartan rose",
"t-shirt gaufre",
"t-shirt tartan gris",
"pull tartan gris",
"pull écossais rouge",
"t-shirt écos. rouge",
"pull écossais bleu",
"t-shirt écos. bleu",
"pull écossais rose",
"t-shirt écos. rose",
"pull écossais cyan",
"t-shirt écos. cyan",
"pull chevrons",
"pull givré",
"pull boréal",
"pull hiver",
"pull folklorique",
"pull écossais vert",
"pull original",
"pull confortable",
"pull beige",
"pull ocre",
"pull pastel",
"pull prairie",
"pull daim",
"pull singe",
"t-shirt choco-menthe",
"t-shirt fougère",
"t-shirt feuille",
"t-shirt automnal",
"pull paille",
"t-shirt herbe",
"pull neige",
"t-shirt amour",
"t-shirt bulles",
"t-shirt fractal",
"t-shirt corail",
"t-shirt funky",
"t-shirt flamme",
"t-shirt danger",
"débardeur Carla",
"débardeur futur",
"pull optique",
"t-shirt brillant",
"t-shirt étoiles",
"t-shirt astral",
"débardeur nébuleux",
"t-shirt galaxie",
"débardeur dés",
"t-shirt enfant",
"t-shirt aéré",
"pull croisé",
"t-shirt splendide",
"t-shirt dentelé",
"t-shirt atténué",
"t-shirt dièse",
"t-shirt peintre",
"t-shirt motif jungle",
"t-shirt motif glace",
"t-shirt motif désert",
"débardeur circuit",
"débardeur ECG",
"t-shirt zèbre",
"t-shirt tigre",
"t-shirt vache",
"t-shirt léopard",
"t-shirt girafe",
"débardeur coccinelle",
"t-shirt arachno",
"débardeur bombyx",
"pull magma",
"t-shirt agrume",
"t-shirt kiwi",
"t-shirt pastèque",
"t-shirt fraise",
"t-shirt raisin",
"t-shirt melon",
"débardeur vague rose",
"débardeur flan",
"débardeur hot-dog",
"débardeur sandwich",
"t-shirt oriental",
"débardeur moche",
"t-shirt dragon",
"t-shirt Asie",
"t-shirt iris mauve",
"t-shirt iris bleu",
"t-shirt canevas",
"t-shirt tropique",
"pull corset",
"pull noble",
"chemise Hawaï rouge",
"chemise Hawaï bleue",
"pull western",
"pull royal",
"pull pompier",
"blouse de docteur",
"pull os",
"pull zip",
"pull momie",
"pull militaire",
"t-shirt matelot",
"t-shirt reggae",
"pull chameau",
"pull hôtel",
"smoking",
"t-shirt aventure",
"t-shirt Brésil",
"doudoune rouge",
"doudoune bleue",
"pull équitation",
"pull lamé",
"pull lancier",
"débardeur catch",
"t-shirt sécurité",
"haut ours",
"haut grenouille",
"haut kappa",
"pull Chine",
"pull pilote",
"pull d'ouvrier",
"t-shirt métal",
"cuirasse d'écailles",
"cuirasse de plates",
"cuirasse plates or",
"t-shirt frappant",
"veste survêt rouge",
"pull baseball",
"t-shirt sport rouge",
"t-shirt sport bleu",
"pull spatial",
"débardeur caverne",
"t-shirt kung-fu",
"gilet en cuir",
"pull cycliste",
"t-shirt cycliste",
"tenue de chef",
"pull persan",
"tunique folklorique",
"pull de héros rouge",
"pull de héros bleu",
"pull de héros vert",
"cuirasse samouraï",
"pull rapiécé",
"tenue héroïque",
"veste Varia",
"t-shirt équipe NTDO",
"sweat gris",
"veste de pêcheur",
"tenue de capitaine",
"pull ninja",
"tenue de détective",
"manteau de père Noël",
"t-shirt poussins",
"t-shirt écailles",
"veste jinbei",
"t-shirt kanji",
"pull coupe raglan",
"t-shirt happi",
"veste collège rouge",
"veste collège bleue",
"veste collège grise",
"veste tigre",
"veste dragon",
"pull flanelle rouge",
"pull flanelle bleu",
"pull flanelle gris",
"débardeur fleur rose",
"débardeur jardin",
"débardeur dentelle",
"débardeur rose",
"pull hanten",
"chemise bureau",
"gilet molletonné",
"veste décontractée",
"blouse enfant",
"veste d'écolier",
"pull menthe",
"veste en jean",
"t-shirt prisme",
"veston en jean",
"t-shirt sport vert",
"blazer emblème vert",
"veste délavée",
"veste Loyal rouge",
"veston blanc",
"veste en jean noire",
"débardeur basketball",
"veste ibérique",
"sweat rose",
"pull jockey",
"veste survêt bleue",
"gilet de laine",
"gilet de smoking",
"veste survêt grise",
"blazer emblème beige",
"pull de vendeur",
"veste survêt verte",
"veste Loyal bleue",
"débardeur marathon",
"pull nordique",
"veste rouge",
"veste bleue",
"t-shirt floral",
"t-shirt de rêve",
"t-shirt pop",
"t-shirt en soie",
"t-shirt fleuri",
"t-shirt fleurs",
"t-shirt flashy",
"t-shirt rose ciel",
"pull jacquard",
"t-shirt nénuphar",
"t-shirt rose",
"pull soda",
"pull bouffon",
"pull chouette",
"pull go-go",
"débardeur carnaval",
"haut pyjama rose",
"haut pyjama bleu",
"pull canari",
"pull hôtesse",
"tenue de barista",
"duffel-coat",
"manteau fourré",
"veste bigarrée",
"pull montagnard",
"t-shirt tournesols",
"débardeur rayé vert",
"débardeur gris",
"pull distingué",
"t-shirt cerisier",
"t-shirt AJD",
"veste AJD",
"veste Ciboulot",
"t-shirt épicerie",
"t-shirt chouette",
"t-shirt jacquard",
"t-shirt coupe raglan",
"pull MVP",
"pull nappe jade",
"pull carrés rouge",
"pull rugby",
"pull peintre",
"pull ECG",
"pull Toad",
"pull matelot",
"pull rainette",
"pull grille bleu",
"pull kung-fu",
"pull pied coq brun",
"pull tartan mauve",
"pull fougère",
"pull motif glace",
"pull automnal",
"pull éléphant",
"pull grille rouge",
"pull bagnard",
"pull pied de coq",
"pull élimé",
"pull gaufre",
"pull rayures blanc",
"pull carrés bleu",
"pull vichy sorbet",
"pull filet",
"pull tartan rose",
"pull rouge & noir",
"pull noir à pois",
"pull vichy jaune",
"pull rayures brun",
"pull losange",
"pull galaxie",
"pull à pois roses",
"pull rayures bleu",
"pull blanc à pois",
"pull raies orange",
"pull tartan jaune",
"pull nébuleux",
"pull Brésil",
"pull raies mauve",
"pull barre",
"pull vichy rose",
"pull crâne",
"pull flamme",
"pull vertige",
"pull raies vert",
"pull Rome",
"pull pimpant",
"pull motif désert",
"pull motif jungle",
"pull beatnik",
"pull rayures jaune",
"pull automne",
"pull tartan bleu",
"pull vichy menthe",
"pull ours",
"pull vichy vert",
"pull nappe bleu",
"débardeur melon",
"débardeur pastèque",
"débardeur zip",
"débardeur brume",
"débard. batik mauve",
"débardeur bouffon",
"débardeur raisin",
"débardeur cône",
"débardeur pois cyan",
"débardeur fraise",
"débardeur pêche",
"débardeur reggae",
"débardeur écos. bleu",
"débardeur brillant",
"débardeur batik vert",
"débardeur sympa",
"débardeur optique",
"débardeur dentelé",
"débardeur rallye",
"débardeur bulles",
"débardeur abysse",
"débardeur lamé",
"débardeur corail",
"débardeur écos. rose",
"débardeur points",
"débardeur funky",
"débardeur nouveau",
"débardeur tropique",
"débardeur couchant",
"débardeur agrume",
"débardeur batik bleu",
"débardeur girafe",
"débard. batik orange",
"débardeur zèbre",
"débardeur tigre",
"débardeur kiwi",
"débard. batik rouge",
"débardeur soda",
"débardeur aurore",
"débardeur beatnik",
"débard. pois orange",
"débardeur irisé",
"débardeur léopard",
"débardeur vache",
"débardeur persan",
"débardeur écos. cyan",
"costume recrue homme",
"costume recrue femme",
"costume élégant",
"polo",
"tailleur",
"blouse d'infirmier",
"costume criard",
"tenue de chef sushi",
"tenue de comique",
"tablier caoutchouc",
"tablier à jabot",
"tenue Felyne",
"veste féminine AJD",
"tenue porte-bonheur",
"tenue de Link",
"tenue de Ganondorf",
"tenue de Ganon",
"tenue de Médolie",
"tenue Épona",
"tenue de Link loup",
"tenue nouveau Link",
"t-shirt ancre noir",
"gilet Cinnamoroll",
"haut Kerokerokeroppi",
"tenue Hello Kitty",
"tenue My Melody",
"tenue Kiki & Lala",
"tenue Pompompurin",
"tenue Cinnamoroll",
"vêt. Kerokerokeroppi",
"uniforme pluie AJD",
"chemisier Ayo",
"chemisier Oly",
"haut paillettes Ayo",
"haut radieux",
"tenue mairie (été)",
"tenue mairie (hiver)",
"chandail en polaire",
,
"tenue de Sheik"
],

//Dresses
[
"robe de mère Noël",
"robe d'été hawaïenne",
"robe à pois bleue",
"robe pied coq brune",
"ensemble soigné",
"robe salopette",
"robe à lacets rose",
"tenue académique",
"robe d'écolière",
"robe de soirée bleue",
"robe de soirée rose",
"robe à pois jaune",
"robe tablier",
"robe écossaise",
"robe verte",
"robe d'été papillon",
"robe flashy",
"manteau de pirate",
"tenue d'héroïne",
"robe en polaire",
"robe vogue",
"robe vichy citron",
"robe d'été florale",
"robe d'été de rêve",
"robe d'été en soie",
"robe d'été pop",
"robe d'été fleurie",
"robe d'été flashy",
"robe d'été rose",
"robe d'été rose ciel",
"robe d'été nénuphar",
"robe rétro turquoise",
"robe rétro orange",
"robe sympa",
"robe élimée",
"robe bourgeon",
"robe rubans",
"robe à lacets bleue",
"robe cirque orange",
"robe cirque verte",
"robe citron vert",
"robe navet",
"robe nordique",
"robe cavalière rouge",
"robe de sorcière",
"tenue de diplômée",
"robe ciel",
"robe tyrolienne",
,
"robe hollandaise",
"toge",
"robe de mariée",
"robe de serveuse",
"robe de princesse",
"robe fable",
"robe Espagne",
"robe d'été Nil",
,
"robe coton",
"robe chat",
"manteau prune",
"redingote",
"tenue cool",
"robe de servante",
"pardessus",
"tenue de pharaon",
"peignoir",
"robe à pois rouge",
"robe rapiécée",
"robe rouge & noire",
"robe losange",
"robe pied de coq",
"blouse d'infirmière",
"robe brodée",
"robe d'été carnaval",
"robe tartan",
"robe en laine",
"robe chemisier",
"robe rouge",
"ciré jaune",
"robe d'été poupée",
"robe d'été sapin",
"robe d'été ballet",
"robe classique",
"robe flèche",
"robe filet",
"robe pimpante",
"robe bonbons",
"robe chima chogori",
"kimono printanier",
"robe d'été caverne",
"robe d'été étoiles",
"robe d'été brillante",
"robe d'été berlingot",
"robe d'été chat",
"robe d'été de mariée",
"robe d'été coton",
"robe amour",
"tenue ballet bleue",
"tenue de musicienne",
"robe princesse Zelda",
"robe paillettes Oly",
"ensemble Hello Kitty",
"ensemble My Melody",
"robe Kiki & Lala",
"habit Pompompurin",
"robe églantine"
],

//Wet suits
[
"maillot (prêt)",
"maillot noir",
"maillot rose",
"maillot rayé",
"maillot vert",
"maillot orange",
"maillot rouge",
"maillot blanc",
"maillot bleu"
],

//Trousers
[
"short motif jungle",
"pantalon mot. jungle",
"pantalon cargo",
"pantalon pied de coq",
"pantalon p. coq brun",
"pantalon rapiécé",
"pantalon père Noël",
"pantalon héroïque",
"pantalon léopard",
"jupe léopard",
"jupe en jean",
"jupe blanche à pois",
"pantalon vache",
"pantalon girafe",
"pantalon tigre",
"pantalon zèbre",
"pantalon de plates",
"pantalon plates or",
"pantalon ibérique",
"pantalon baseball",
"pantalon os",
"pantalon motif glace",
"pantal. motif désert",
"short caverne",
"short de boxe bleu",
"short de boxe rouge",
"jupe soda",
"jupe iris bleue",
"jupe iris mauve",
"pantalon Chine",
"bas ours",
"bas grenouille",
"bas kappa",
"pantalon gris",
"pantalon western",
"jupe points",
"pantalon flamme",
"short tartan vert",
"pantalon dragon",
"short aventure",
"pantalon pompier",
"jupe rouge & noire",
"jupe vichy sorbet",
"short tartan brun",
"short arc-en-ciel",
"jupe vichy menthe",
"short à pois bleu",
"jupe corset",
"jupe grille bleue",
"pantalon renforcé",
"jupe grille rouge",
"short sport bleu",
"short sport vert",
"short sport rouge",
"pantalon héros bleu",
"pantalon héros vert",
"pantalon héros rouge",
"pantalon survêt bleu",
"pantalon survêt vert",
"pantal. survêt rouge",
"pantalon bouffon",
"pantalon kung-fu",
"pantalon en cuir",
"pantalon militaire",
"pantalon momie",
"pantalon Varia",
"pantalon ninja",
"pantalon persan",
"jupe noire à pois",
"pantalon pilote",
"jupe dentelle",
"jupe matelot",
"pantalon samouraï",
"short jinbei",
"pantalon spatial",
"pantalon à revers",
,
"pantalon rose",
"pantalon en toile",
"jupe tartan grise",
"pantalon bicolore",
"jupe filet",
"jupe pimpante",
"short Brésil",
"pantalon d'ouvrier",
"pantalon catch",
"pantalon survêt gris",
"pantalon footing",
"pantalon chic gris",
"pantalon chic marine",
"pantalon chic noir",
"pantalon chic blanc",
"pantalon rayé rouge",
"jupe losanges orange",
"jupe multicolore",
"jupe savane",
"pantal. tartan rouge",
"jupe à pois rouge",
"pantalon jean brut",
"jupe en jean noire",
"pantalon délavé",
"pantalon rayé gris",
"pantalon jean noir",
"pantalon jean usé",
"jupe à pois émeraude",
"jupe écossaise brune",
"jupe écossaise rose",
"pantalon tartan vert",
"jupe en jean brut",
"short Hawaï",
"pantalon rayé bleu",
"pantalon carnaval",
"pantalon pyj. rose",
"pantalon pyj. bleu",
"short basketball",
"short marathon",
"pantalon chic brun",
"short royal",
"pantalon d'écailles",
"jupe chic noire",
"jupe chic grise",
"jupe chic marine",
"pantalon Ganondorf",
"bas Kerokerokeroppi",
"short Ayo",
"short radieux",
"pantalon Sheik"
],

//Socks
[
"collant filet",
"paire chaus. rayées",
"paire de bas noirs",
"collant cœurs",
"collant irisé",
"paire socq. noires",
"collant étoiles",
"collant rayé",
"p. chausset. costume",
"collant gris",
"paire chauss. marine",
"paire chauss. rando",
"paire chaus. crochet",
"paire chauss. sport",
"paire chauss. écos",
"paire socq. simples",
"collant grenat",
"paire chaus. étoiles",
"legging gris",
"p. chauss. blanches",
"collant noir",
"collant brun",
"p. chauss. colorées",
"paire chauss. damier",
"paire chauss. brunes",
"collant écossais",
"paire chauss. vertes",
"paire de guêtres",
"paire socq. blanches",
"paire chausset. foot",
"legging noir",
"paire chauss. à pois",
"paire de bas blancs",
"paire chauss. grises",
"collant ray. bleues",
"collant vert",
"collant Ayo",
"collant Oly",
"p. chau. Kiki & Lala",
"p. chaus. étang"
],

//Shoes
[
"paire tennis bleues",
"p. sandales blanches",
"p. ballerines mauves",
"p. bottes fourrées",
"paire de baskets",
"p. bottes père Noël",
"p. bottes héroïques",
"paire bottes lacets",
"p. souliers blancs",
"paire bottes rando",
"p. sandales kimono",
"paire d'après-skis",
"paire de tongs",
"p. ballerines V pois",
"p. ballerin. léopard",
"paire tongs tropique",
"p. bottes pluie pois",
"p. bottes pluie J",
"p. souliers crampons",
"paire sabots décorés",
"p. mocassins bruns",
"paire de pantoufles",
"p. souliers N&B",
"p. sandales vertes",
"p. mocassins pompon",
"p. baskets montantes",
"p. mocassins fleurs",
"p. souliers rapiécés",
"paire de sabots",
"p. souliers escalade",
"paire de spartiates",
"paire de tongs ninja",
"p. bottes à coque",
"p. bottes de héros",
"p. bottes pluie N",
"p. ballerines rayées",
"p. chaussons danse",
"p. bottes cowboy",
"p. bottes bouffon",
"paire babies noires",
"paire de solerets",
"paire de solerets or",
"paire bottes catch B",
"paire bottes catch R",
"paire bottes Varia",
"p. souliers V boucle",
"p. mocassins noirs",
"p. pantoufles roses",
"p. ballerines bleues",
"p. tennis colorées",
"p. souliers rouges",
"paire babies rouges",
"p. sandales orange",
"p. pantoufles brunes",
"paire babies jaunes",
"p. souliers à pois",
"p. ballerines noires",
"p. souliers rayés V",
"paire tennis roses",
"p. ballerines brunes",
"paire tennis jaunes",
"paire tennis orange",
"p. de baskets Ayo",
"p. de baskets Oly",
"p. ball. Hello Kitty",
"p. bottes My Melody",
"p. ball. Kiki & Lala",
"p. bott. Pompompurin",
"p. tenn. Cinnamoroll",
"p. de sandales étang",
"p. bottes églantine"
],

//Umbrellas
[
"parapluie Rome",
"parapluie noir",
"ombrelle crochet",
"feuillapluie",
"ombrelle papier",
"ombrelle ruban",
"parapluie rouge",
"parapluie bleu",
"parapluie jaune",
"parapluie vert",
"parapluie vichy",
"parapluie melon",
"parapluie menthe",
"parapluie sorbet",
"parapluie citron",
"ombrelle à pois",
"ombrelle pois jaune",
"ombrelle pois bleue",
"parapluie à fleurs",
"parapluie pattes",
"ombrelle pétale",
"parapluie cassé",
"ombrelle soleil",
"parasol",
"parapluie sélect",
"parapluie psyché",
"parapluie léopard",
"parapluie zèbre",
"parapluie herbe",
"parapluie flammes",
"parapluie kaki",
"parapluie arachnide",
"parapluie Carla",
"parapluie Peach",
"parapluie bonze",
"parapluie érable",
"parap. Puzzle League"
],

//Hats
[
"casquette rouge",
"casquette jaune",
"casquette bleu clair",
"casquette verte",
"casquette étoile",
"casquette 1UP",
"casquette mauve",
"casquette bleu foncé",
"bonnet bleu",
"bonnet vert",
"bonnet orange",
"bonnet rose",
"bonnet mauve",
"pompon rouge",
"chapeau badge",
"chapeau de paille",
"chapeau de papi",
"casquette de livreur",
"béret",
"casquette de dandy",
"casquette de chasse",
"casquette détective",
"haut-de-forme",
"chapka",
"chapeau Carla",
"chapeau classe",
,
"chapeau tulipe",
"bandana triangle",
"bonnet de natation",
"chapeau de magicien",
"casque en papier",
"bonnet de père Noël",
"casquette Mario",
"casquette Luigi",
"casquette Wario",
"casque de vélo",
"toque",
"casque lourd",
"chapeau diplôme",
"casque de chantier",
"casquette de police",
"chapeau aventure",
"casquette capitaine",
"bonnet marin",
"chapeau en soie",
"feutre",
"chapeau hollandais",
,
"chapeau tyrolien",
"casque viking",
"chapeau d'équitation",
"chapeau de pirate",
"chapeau de bouffon",
"chapeau de sorcier",
"chapeau melon",
"chapeau fraise",
"chapeau kiwi",
"chapeau mandarine",
"chapeau pastèque",
"chapeau raisin",
"ruban rouge",
"ruban bleu",
"ruban jaune",
"épingle cœur",
"épingle étoile",
"épingle lune",
"auréole",
"chapeau trèfle",
"chapeau d'élève",
"chapeau flamenco",
"casquette des rouges",
"casquette des blancs",
"chapeau hot-dog",
"chapeau cérémoniel",
"chapeau impérial",
"chapeau glacé",
"casqu. écol. bleue",
"casqu. écol. blanche",
"casquette police B",
"couronne royale",
"couronne",
"chapeau rapiécé",
"chapeau anniv",
"chapeau nouvel an R",
"chapeau nouvel an J",
"chapeau nouvel an B",
"chapeau nouvel an V",
"casquette blanche",
"chapeau paille ruban",
"coiffe d'infirmière",
"bonnet de nuit rose",
"borsalino plaid bleu",
"épingle hibiscus",
"chapeau de bambou",
"chapeau conique",
"chapeau ibérique",
"chapeau ballons",
"bonnet de nuit bleu",
"canotier",
"bandana blanc",
"bonnet de bain",
"capeline",
"épingle luxueuse",
"coiffe de carnaval",
"chapeau cloche",
"chapeau de capitaine",
"chapeau d'écolier",
"serre-tête lumières",
"serre-tête fleurs",
"serre-tête cœurs",
"serre-tête étoiles",
"chapeau de facteur",
"casquette militaire",
"chapeau de cavalière",
"casquet. filet Cubic",
"bonnet Hello Kitty",
"casquette My Melody",
"broche Kiki & Lala",
"chapeau Cinnamoroll",
"clip Kerokerokeroppi",
"béret radieux",
"nœud de Céleste",
"casquette chauffeur",
,
"bonnet péruvien",
"casque de pilote",
"casque de pompier",
"chapeau de bébé",
,
"coiffe d'indien",
"keffieh",
"casque préhistorique",
"coiffe de samouraï",
"coiffe de geisha",
"cagoule de ninja",
"perruque noble",
"perruque afro",
"perruque banane",
"perruque iroquoise",
"natte",
"perruque beignet",
"diadème",
"voile de mariée",
"bandeau de sport",
"cagoule lapin",
"cagoule chat",
"cagoule ours",
"cagoule grenouille",
"cagoule kappa",
"casque de samouraï",
"coiffe héroïque",
"casque de course",
"casque de motocross",
"casque de football",
"casque de chevalier",
"casque romain",
"casque de scaphandre",
"casque spatial",
"cagoule",
"masque de catch",
"casque rétro",
"casque héros rouge",
"casque de héros bleu",
"casque de héros vert",
"casque d'héroïne",
"masque d'ogre rouge",
"masque d'ogre bleu",
"masque Majora",
"casque Varia",
"masque Midona",
"chapeau Toad",
"citrouille",
"masque de pharaon",
"masque de fantôme",
"masque de zombistein",
"masque d'insecte",
"masque de momie",
"Pikmin feuille",
"Pikmin bourgeon",
"Pikmin fleuri",
"coiffe fête poupées",
"casque de boxe vert",
"casque de boxe rouge",
"cagoule neige",
"coiffe de mariée",
"perruque Kintaro",
"béret écossais",
"chapeau cornu",
"chaperon rouge",
"perruque funky",
"masque de Dumoria",
"masque d'escrime",
"perruque à chignon",
"casque de DJ",
"masque danse du lion",
"perruque nœud pap",
"capuche Tingle",
"capuche de diablotin",
"chapeau machiniste",
"perruque de matrone",
"masque de squelette",
"voile noir",
"coiffe afro",
"masque de loup-garou",
"perruque d'ogre",
"cagoule de plongeur",
"foulard vert",
"masque de Fay",
"parure de sultane",
"casque de batteur",
"casque de jockey",
"masque de receveur",
"casque de boxe bleu",
"perruque à nattes",
"citrouille violette",
"citrouille jaune",
"citrouille verte",
"citrouille rouge",
"monture anniv",
"bonnet de Link",
"perruque Ganondorf",
"masque de Sheik",
"perruque Zelda",
"perr. nouveau Link",
"perruque Ayo",
"perruque Oly",
"perr. lunettes (♂)",
"perr. écouteurs (♀)",
"perruque églantine",
"masque de Navirou",
"béret Pompompurin",
"perruque de Lou"
],

//Accesories
[
"monture bleue",
"monture rouge",
"monture jaune",
"monture menthe",
"monture mauve",
"monture verte",
"monture marron",
"monture rose",
"monture forte",
"monture argent",
"monture intello",
"monture funky",
"monture tortue",
"monture Carla",
"monture pilote",
"monture sport",
"monture maxi",
"monture triangle",
"monture mini",
"monture cœur",
"monture étoiles",
"monture 3D",
"masque de bal",
"masque héros",
"monture piscine",
"masque plongée",
"masque repos",
"visiocasque",
,
"monture docteur",
"cache-œil",
"bandeau",
"masque à gaz",
"masque de hockey",
"masque de clown",
"nez rouge",
"kit rigolo",
"moustache Mario",
"moustache Wario",
"moustache élégante",
"barbe de roi",
"masque",
"tétine",
"bec",
"masque citron",
"masque concombre",
"pansement",
"monture stores",
"barbe de père Noël",
"monture ronde",
"monture futuriste",
"loup",
"monture farceuse",
"feuille",
"monture steampunk",
"monture aviateur",
"masque de beauté",
"monture ovale",
"tulipe rouge",
"tulipe blanche",
"tulipe jaune",
"tulipe rose",
"tulipe mauve",
"tulipe noire",
"tulipe orange",
"pensée blanche",
"pensée jaune",
"pensée rouge",
"pensée mauve",
"pensée orange",
"pensée bleue",
"cosmos blanc",
"cosmos rouge",
"cosmos jaune",
"cosmos rose",
"cosmos orange",
"cosmos noir",
"rose rouge",
"rose blanche",
"rose jaune",
"rose rose",
"rose orange",
"rose mauve",
"rose noire",
"rose bleue",
"rose dorée",
"œillet rouge",
"œillet rose",
"œillet blanc",
"lys blanc",
"lys jaune",
"lys rouge",
"lys orange",
"lys rose",
"lys noir",
"violette mauve",
"violette bleue",
"violette blanche",
"violette jaune",
"muguet",
"trèfle à 4 feuilles",
"pissenlit",
"tête de pissenlit"
],

//Gyroids
[
"méga-glingoïde",
"glingoïde",
"mini-glingoïde",
"super-glingoïde",
"dingloïde trapu",
"méga-dingloïde",
"dingloïde",
"mini-dingloïde",
"dingloïde minus",
"super-dingloïde",
"méga-percoloïde",
"super-percoloïde",
"méga-tamboïde",
"tamboïde",
"mini-tamboïde",
"super-tamboïde",
"rythmoïde",
"mini-rythmoïde",
"méga-fumoïde",
"mini-fumoïde",
"super-fumoïde",
"méga-berçoïde",
"berçoïde",
"mini-berçoïde",
"super-berçoïde",
"méga-jamoïde",
"jamoïde",
"mini-jamoïde",
"super-jamoïde",
"méga-jazzoïde",
"jazzoïde",
"mini-jazzoïde",
"super-jazzoïde",
"méga-tuutoïde",
"tuutoïde",
"mini-tuutoïde",
"méga-plonkoïde",
"plonkoïde",
"mini-plonkoïde",
"méga-pointoïde",
"pointoïde",
"mini-pointoïde",
"méga-bourdoïde",
"bourdoïde",
"mini-bourdoïde",
"super-bourdoïde",
"méga-perçoïde",
"perçoïde",
"mini-perçoïde",
"méga-échoïde",
"mini-échoïde",
"super-échoïde",
"méga-lamentoïde",
"lamentoïde",
"mini-lamentoïde",
"super-lamentoïde",
"méga-guitaroïde",
"guitaroïde",
"mini-guitaroïde",
"super-guitaroïde",
"méga-coassoïde",
"coassoïde",
"mini-coassoïde",
"super-coassoïde",
"méga-pétilloïde",
"mini-pétilloïde",
"méga-ploufoïde",
"ploufoïde",
"mini-ploufoïde",
"méga-hurloïde",
"hurloïde",
"mini-hurloïde",
"méga-nébuloïde",
"nébuloïde trapu",
"nébuloïde",
"mini-nébuloïde",
"super-nébuloïde",
"nebuloïde menu",
"méga-gongoïde",
"gongoïde",
"mini-gongoïde",
"super-gongoïde",
"méga-spectroïde",
"spectroïde",
"mini-spectroïde",
"super-spectroïde",
"métatoïde",
"mini-métatoïde",
"méga-bovoïde",
"super-bovoïde",
"méga-oboïde",
"oboïde",
"super-oboïde",
"méga-roboïde",
"mini-roboïde",
"méga-harmonoïde",
"harmonoïde",
"mini-harmonoïde",
"super-harmonoïde",
"super-pourproïde",
"méga-postilloïde",
"postilloïde",
"mini-postilloïde",
"super-postilloïde",
"méga-alloïde",
"mini-alloïde",
"super-alloïde",
"méga-timbaloïde",
"timbaloïde",
"mini-timbaloïde",
"super-timbaloïde",
"glouglouïde",
"mini-glouglouïde",
"super-glouglouïde",
"guerroïde",
"mini-guerroïde",
"super-guerroïde",
"méga-monstroïde",
"mini-monstroïde",
"méga-rayoïde",
"rayoïde",
"mini-rayoïde",
"super-rayoïde",
"rayoïde menu",
"méga-rouilloïde",
"rouilloïde",
"mini-rouilloïde",
"méga-robustoïde",
"mini-robustoïde",
"super-robustoïde",
"robustoïde"
],

//Furniture
[
"lit teck",
"commode teck",
"armoire teck",
"banc teck",
"chaise teck",
"table teck",
"mini-table teck",
"lampe teck",
"paravent teck",
"coffre teck",
"étagère mur teck",
"lit ranch",
"commode ranch",
"armoire ranch",
"canapé ranch",
"fauteuil ranch",
"chaise ranch",
"table ranch",
"table basse ranch",
"étagère ranch",
"buffet ranch",
"étagère mur ranch",
"lit rustique",
"coiffeuse rustique",
"armoire rustique",
"chaise rustique",
"canapé rustique",
"table rustique",
"étagère rustique",
"console rustique",
"bureau rustique",
"horloge rustique",
"étagère mur rustique",
"lit royal",
"commode royale",
"armoire royale",
"chaise royale",
"canapé royal",
"table royale",
"lampe royale",
"horloge royale",
"vitrine royale",
"coiffeuse royale",
"lampe mur royale",
"lit bleu",
"commode bleue",
"penderie bleue",
"chaise bleue",
"banc bleu",
"table bleue",
"étagère bleue",
"armoire bleue",
"horloge bleue",
"buffet bleu",
"étagère mur bleue",
"lit rotin",
"commode rotin",
"armoire rotin",
"chaise rotin",
"fauteuil rotin",
"table rotin",
"lampe rotin",
"étagère rotin",
"coiffeuse rotin",
"paravent rotin",
"radio mur rotin",
"lit vert",
"commode verte",
"armoire verte",
"chaise verte",
"banc vert",
"table verte",
"secrétaire vert",
"lampe verte",
"console verte",
"buffet vert",
"horloge mur verte",
"lit chalet",
"commode chalet",
"armoire chalet",
"chaise chalet",
"fauteuil chalet",
"canapé chalet",
"table chalet",
"table basse chalet",
"étagère chalet",
"horloge chalet",
"horloge mur chalet",
"lit moderne",
"commode moderne",
"armoire moderne",
"chaise moderne",
"canapé moderne",
"table moderne",
"bureau moderne",
"table basse moderne",
"vitrine moderne",
"lampe moderne",
"horloge mur moderne",
"lit enfant",
"commode enfant",
"penderie enfant",
"canapé enfant",
"chaise enfant",
"table enfant",
"armoire enfant",
"étagère enfant",
"horloge enfant",
"hi-fi enfant",
"horloge mur enfant",
"lit cœur",
"commode cœur",
"armoire cœur",
"chaise cœur",
"canapé cœur",
"guéridon cœur",
"table basse cœur",
"coiffeuse cœur",
"cuisine cœur",
"lampe cœur",
"horloge mur cœur",
"lit robot",
"commode robot",
"armoire robot",
"sofa robot",
"fauteuil robot",
"table robot",
"chaîne robot",
"télé robot",
"horloge robot",
"lampe robot",
"horloge mur robot",
"lit à pois rouge",
"commode à pois rouge",
"armoire à pois rouge",
"fauteuil pois rouge",
"canapé à pois rouge",
"table à pois rouge",
"lampe à pois rouge",
"tabouret pois rouge",
"table b. pois rouge",
"télé à pois rouge",
"horloge à pois rouge",
"lit Yétiti",
"commode Yétiti",
"armoire Yétiti",
"chaise Yétiti",
"canapé Yétiti",
"table Yétiti",
"frigo Yétiti",
"télé Yétiti",
"horloge Yétiti",
"lampe Yétiti",
"coiffeuse Yétiti",
"lit champi",
"commode champi",
"buffet champi",
"chaise champi",
"siège champi",
"table champi",
"table basse champi",
"lampe champi",
"lampe mur champi",
"télé champi",
"portemanteau champi",
"lit carnaval",
"coffre carnaval",
"buffet carnaval",
"canapé carnaval",
"chaise carnaval",
"table carnaval",
"guéridon carnaval",
"étagère carnaval",
"coiffeuse carnaval",
"lampe carnaval",
"horloge carnaval",
"lit œuf",
"commode œuf",
"bahut œuf",
"chaise œuf",
"banc œuf",
"table œuf",
"chaîne œuf",
"jouet œuf",
"cadran œuf",
"lampe œuf",
"télé œuf",
"lit Halloween",
"buffet Halloween",
"bahut Halloween",
"sofa Halloween",
"chaise Halloween",
"table Halloween",
"coiffeuse Halloween",
"étagère Halloween",
"cadran Halloween",
"lampe Halloween",
"lampe mur Halloween",
"lit dindon",
"commode dindon",
"armoire dindon",
"canapé dindon",
"chaise dindon",
"table dindon",
"coiffeuse dindon",
"télé dindon",
"horloge dindon",
"lampe dindon",
"lampe mur dindon",
"lit festif",
"commode festive",
"armoire festive",
"canapé festif",
"chaise festive",
"table festive",
"étagère festive",
"piano festif",
"horloge festive",
"lampe festive",
"télé festive",
"lit princesse",
"commode princesse",
"buffet princesse",
"canapé princesse",
"chaise princesse",
"table princesse",
"vitrine princesse",
"coiffeuse princesse",
"cage princesse",
"lampe princesse",
"horloge princesse",
"lit Carla",
"commode Carla",
"armoire Carla",
"banc Carla",
"chaise Carla",
"table basse Carla",
"bureau Carla",
"chariot Carla",
"étagère Carla",
"lampe Carla",
"horloge mur Carla",
"lit bonbons",
"commode bonbons",
"armoire bonbons",
"canapé bonbons",
"chaise bonbons",
"table bonbons",
"petite table bonbons",
"étagère bonbons",
"lampe bonbons",
"petite lampe bonbons",
"lecteur bonbons",
"lit somptueux",
"commode somptueuse",
"armoire somptueuse",
"canapé somptueux",
"fauteuil somptueux",
"siège somptueux",
"table somptueuse",
"bureau somptueux",
"bar somptueux",
"lampe somptueuse",
"horl. mur somptueuse",
"lit minimaliste",
"canapé minimaliste",
"chaise minimaliste",
"commode minimaliste",
"armoire minimaliste",
"horloge minimaliste",
"lampe minimaliste",
"pouf minimaliste",
"table minimaliste",
"table b. minimaliste",
"coiffeu. minimaliste",
"lit d'or",
"commode d'or",
"armoire d'or",
"chaise d'or",
"banc d'or",
"table d'or",
"horloge d'or",
"totem homme d'or",
"totem femme d'or",
"paravent d'or",
"flambeau mur d'or",
"crâne de vache",
"cactus cierge",
"barrière western",
"porte-selle",
"devanture",
"chariot bâché",
"abreuvoir",
"boule de ronces",
"puits",
"roue de chariot",
"astéroïde",
"lune",
"module lunaire",
"fusée",
"véhicule lunaire",
,
"navette spatiale",
"spationaute",
"station spatiale",
"soucoupe volante",
"flèche détour",
"brouette",
"poutre en fer",
"plaque d'égout",
"cône orange",
"cône bicolore",
"barrière travaux",
"pan. chau. glissante",
"compacteur",
"marteau-piqueur",
"cône rayé",
"bétonneuse",
"baril de pétrole",
"barrière de ring",
"coin rouge",
"coin bleu",
"coin neutre",
"gong",
"tapis de boxe",
"table d'arbitrage",
"banc de muscu",
"sac de frappe",
"ballon vitesse",
"abri à oiseaux",
"M. Flamingo",
"Mme Flamingo",
"nain de jardin",
"anti-moustiques",
"hamac",
"bassin à oiseaux",
"table de pique-nique",
"mangeoire à oiseaux",
"chaise de jardin",
"tondeuse à gazon",
,
"piscine de jardin",
"arroseur",
"flambeau",
"éléphoboggan",
"landau",
"berceau",
"lit bébé",
"chariot",
"manège",
"cheval à bascule",
"train miniature",
"culbutine",
"poupée",
"lit labo",
"chaise labo",
"étagère labo",
"alambic",
"machine extra",
"machine inconnue",
"machine complexe",
"barre à roue",
"tonneau",
"tonnelet",
"canon",
"ancre",
"compas",
"squelette lugubre",
"chaudron lugubre",
"tombe lugubre",
"stèle lugubre",
"cercueil lugubre",
"boule lugubre",
"horloge lugubre",
"statue lugubre",
"pion",
"fou",
"roi",
"cavalier",
"reine",
"tour",
"grand tableau droit",
"grand tableau gauche",
"bureau de professeur",
"bureau du maître",
"chaise du maître",
"pupitre",
"chaise d'écolier",
"casier",
"tableau noir",
"balai-éponge",
"squelette",
"modèle musculaire",
"modèle circulation",
"cage à hamster",
"paillasse",
"cheval sautoir",
"porte-ballons",
"matelas sport",
"haie",
"compte-points",
"chaise pliante",
"test de vision",
"mesureur",
"toise",
"balance",
"lit d'hôpital",
"panneau d'hôpital",
"perfusion",
"bassine",
"secrétaire",
"siège secrétaire",
"globe terrestre",
"bureau pro",
"chaise pro",
"casier pro",
"cafetière",
"comptoir",
"caisse",
"juke-box",
"percolateur",
"daruma XL",
"daruma",
"mini-daruma",
"papa ours",
"maman ours",
"bébé ours",
"maman ours polaire",
"papa panda",
"maman panda",
"bébé panda",
"grand cactus",
,
"cactus boule",
"sac de golf",
"fauteuil standard",
"canapé standard",
"totem ours",
"totem aigle",
"totem rainette",
"totem corbeau",
"lampe à lave",
"table à thé",
"âtre",
"paravent",
,
"meuble à thé",
"lampion",
"lampe mur papier",
"buffet paulownia",
"commode escalier",
"panneau bas",
"tigre en papier",
"rainette fétiche",
"épée",
"arc",
"armure de samouraï",
"katana noir",
"katana blanc",
"épée de ninja",
"jeu d'eau",
"lanterne haute",
"tas de tabourets",
"tapis de bain",
"seau",
"baignoire",
"présentoir à lait",
"congélo glaces",
"lavabo",
"pot à thé",
"vase rouge",
"vase bleu",
"chat fétiche",
"chat fétiche gaucher",
"chat fétiche noir",
"chat fétiche doré",
"table pomélo",
"table citron",
"chaise mandarine",
"tabouret kiwi",
"armoire poire",
"commode poire",
"chaise pastèque",
"table pastèque",
"télé pomme",
"horloge pomme",
"table nénuphar",
"siège rainette",
"chaise en pin",
"table en pin",
"chaise fleur",
"table fleur",
"bonsaï pin russe",
"bonsaï pin",
"bonsaï pin mugho",
"bonsaï prunier",
"bonsaï houx",
"bonsaï azalée",
"bonsaï érable",
"bonsaï aubépine",
"bonsaï cydonia",
"bonsaï jasmin",
,
"cocotier",
,
,
,
"dragonnier",
"palmier chanvre",
"aloès",
"caoutchouc",
"sansevieria",
"palmier d'Arec",
"yucca",
"guzmania",
"figuier pleureur",
"conga",
"djembé",
"timpano",
"violon",
"violoncelle",
"contrebasse",
"guitare folk",
"guitare country",
"guitare rock",
"guitare jazz",
"ukulélé",
"piano à queue",
"piano droit",
"tambour taiko",
,
"luth biwa",
"harpe",
"métronome",
"corbeille",
"conteneur à ordures",
"poubelle",
"boîte à ordures",
"colonne Panthéon",
"colonne Ionie",
"colonne Corinthe",
"colonne brisée",
"pyramide",
"sphinx",
"sarcophage",
"poterie jomon",
"set tennis de table",
"jeu de quilles",
"renvoi boules",
"panneau de basket",
"billard",
"table de mah-jong",
"jeu de fléchettes",
"flipper",
"borne d'arcade",
"table de jeux",
"tabouret",
"plateau de shogi",
"table de go",
,
"armure",
"Tour de Pise",
"boussole",
"boîte de chocolats",
"sac à dos",
"VTT",
"barbecue à gaz",
,
"lanterne",
"sac de couchage",
"feu de camp",
"feu de joie",
"télé-magnéto",
"télé 16/9",
"télé rétro",
"meuble évier",
"évier de coin",
"four luxe",
"four",
"cuisinière",
"évier",
"service à thé",
"râpe-glace",
"réfrigérateur",
"réfrigérateur vert",
"micro-ondes",
"grille-pain",
"mixeur",
"étendoir",
"niche",
"transat",
"brise-lames",
"planche de surf",
"scaphandre",
"table de plage",
"coffre au trésor",
"bouée de sauvetage",
,
"luge",
"Yétiti",
"tournesol",
"jonquille",
,
"WC",
"super WC",
"vespasienne",
"étagère en plastique",
"coffre-fort",
"lave-linge luxe",
"lave-linge auto",
"lave/sèche-linge",
"poêle à charbon",
"chauffage",
"cheminée",
"radiateur",
"phonographe",
"tourne-disque",
"magnétophone",
"hi-fi rétro",
"hi-fi dorée",
"chaîne hi-fi",
"hi-fi stéréo",
"chaîne stéréo dé",
"cassettophone",
"lecteur CD",
"lecteur de cassettes",
"horloge ronde",
"horloge kitsch",
"horloge ancienne",
"horloge cube",
"horloge bizarre",
"horloge ovale",
"horloge chouette",
"réveil",
"chaise ordinaire",
"rocking-chair",
"tablette gauche",
"tablette droite",
"pompe à essence",
"extincteur",
"borne d'incendie",
"raton laveur",
"enseigne barbier",
"distributeur bonbons",
"épouvantail",
"cage à oiseaux",
"cabine téléphonique",
"bain extérieur",
"champ de blé",
"ordinateur",
"lit ananas",
"table en verre",
,
"canapé crème",
"casier de rangement",
"penderie en tissu",
"baignoire à pieds",
"douche",
"siège de massage",
"aspirateur",
"bateau bouteille",
"oiseau aquatique",
"gadget de bureau",
"télescope",
"pilon à riz",
"machine coudre rétro",
"boîte en carton",
"boîte en bois",
"ventilateur",
"bougeoir",
"petite lampe",
"lampe de bureau",
"lampe de table",
"trône",
"lit ordinaire",
"bloc",
"pièce",
"drapeau Mario",
"fleur de feu",
"super champignon",
"carapace verte",
"super étoile",
"champignon 1UP",
"bloc ?",
"tuyau",
"barre de feu",
"Bill Boum",
"œuf de Yoshi",
"triple banane",
"triple carapa. rouge",
,
,
,
"Excalibur",
,
,
,
"maquette du Dolphin",
"boîte à malice",
,
,
,
"grand sapin",
"sapin",
"fanion de fête",
"chandelier de fête",
"téléphone cœur",
"mouchoir",
"tirelire cochon",
"DAC",
"mallette aluminium",
"gâteau de riz",
"plat de dangos",
"bambou à vœux",
"mini Resetti",
"globe cool",
"panier-repas",
"maquette de bateau",
"botte de blé",
"machine à café",
"chaussette",
"boule à neige",
"panier de légumes",
"yut",
,
,
"couronne de sapin",
"pot marron",
"pot blanc",
"tapisserie",
"toupie",
"alcôve",
"bannière carpe",
"veaubergine",
"belle-de-jour",
"tas de feuilles",
"château de sable",
"chariot Nook",
"raquette nippone",
"lampe fleurie",
"cheval concombre",
"chaise borsalino",
"plat de tteok",
"plat de gimbap",
"lampe glacée",
"bouquet fleuri",
"banc de Cupidon",
"socle",
"vitrine verticale",
"vitrine horizontale",
"vitrine murale",
"tabouret de musée",
"panneau fléché",
"cadre luxueux",
"thermo-hygromètre",
"table d'accueil",
"porte-affiche",
"panneau d'exposition",
"lampe méduse",
"climatiseur",
"horloge à balancier",
"affichage LED",
"trophée de pêche or",
"trophée pêche argent",
"trophée pêche bronze",
"trophée insecte or",
"trophée insecte arg",
"trophée insecte brze",
"maquette de musée",
"set correspondance",
"soupe du nouvel an",
"cloche en bronze",
"tabouret tube",
"corne d'abondance",
"tarte à la courge",
"dinde",
"présentoir à gâteaux",
"bibliothèque massive",
"marchepied",
,
"orchidée",
,
"cabine de douche",
"pied pour microphone",
"lit tatami",
"clavecin",
"chaise réalisateur",
"thérémine",
"lit superposé",
"poupée japonaise",
"filet de volleyball",
"siège velours rose",
"bûche au chocolat",
"poupée de princesse",
"panier de fruits",
,
"plaque chauffante",
"lapin en neige",
"téléphone d'époque",
"platine",
"rouet",
"livre en relief",
"seau anti-fuite",
"lampe à pétrole",
"bouilloire moderne",
"gâteau de mariage",
"pot à bonbons",
"chandelle de fête",
"gril à poissons",
"lampe muguet",
"projecteur sur pied",
"projecteur",
"lampe vitrail",
"casserole de camping",
"mini-igloo",
"roue colorée",
"caméra d'époque",
"mini-affichage LED",
"fanion de l'AJD",
"plaque AJD argent",
"plaque AJD or",
"trophée AJD argent",
"trophée AJD or",
"modèle maison or",
"arbre à chat",
"lave-vaisselle",
"tabouret en bois",
"étagère à CD",
"guitare électrique",
"porte-revues XXL",
"malle",
"pot à lait",
"portemanteau",
"lampe nénuphar",
"machine à coudre",
"maison de poupée",
"machine à granités",
"bureau avec PC",
"pot pour enfant",
"bouilloire",
"lot livres scolaires",
"bar à salade",
"balisage à corde",
"machine à laver",
"brûle-parfum",
"pupitre de quiz",
"vitrine à sodas",
"tabouret beignet",
"vitrine vapeur",
"four en terre cuite",
"télé à écran plat",
"sphère pour tirage",
"chaise de rédacteur",
"set de peinture",
"bureau de rédacteur",
"tourniquet à épices",
"meuble lavabo",
"porte-encens",
"porte-revues",
"cuiseur de riz",
"projecteur d'étoiles",
"tapis roulant sushis",
"globe céleste",
"tableau blanc",
"fauteuil paon",
"bain à remous",
"îlot de cuisine",
"coussin",
,
"sono",
"humidificateur",
"pointeuse",
"attrape-peluche",
"pupitre à partition",
"set de repassage",
"valise à roulettes",
"jardinière",
"fauteuil de dentiste",
"ampli",
"métier à tisser",
"table plat. tournant",
"bocal de pickles",
"caméra de télévision",
"chauffe-plat",
"congélateur",
"appareil à fondue",
"fait-tout",
"ordinateur portable",
"serveur informatique",
"photocopieuse",
"batterie classique",
"fontaine à sodas",
"fontaine à eau",
"aspirateur balai",
"coffret à maquillage",
"guitare à 2 manches",
,
"machine à pop-corn",
"platine de DJ",
"panneau fleuri",
"lampe cornet glace",
"meuble informatique",
"orgue",
"équipement karaoké",
"bouilloire standard",
"cadre numérique",
"porte-casseroles",
"pot de fleurs mural",
"étagère",
"vitrail",
"haut-parleur",
"diplôme bleu",
"mini-télévision",
"horloge coucou",
"ventilateur mural",
,
"disjoncteur",
"diplôme jaune",
"aérateur",
"bouée",
"lampion blanc",
"caméra surveillance",
"panneau de sortie",
"enceinte murale",
"applique ancienne",
"cabine de WC fixe",
"cabine de WC mobile",
"masque de sage",
"masque d'ogre",
"masque de femme",
"horloge arachno",
"canapé bombyx",
"chaise scarabée",
"chaise lucane",
"coffre abeille naine",
"lampe luciole",
"table papillon",
"siège coccinelle",
"horloge escargot",
"hi-fi cigale",
"lit anémone de mer",
"chaise calmar",
"horloge crabe",
"lampe pois. lanterne",
"siège poulpe",
"fauteuil vivaneau",
"télé pois. porc-épic",
"table limande",
"table cardeau",
"horlo. mur r. laveur",
"mini-cactus haut",
"mini-cactus",
"mini-cactus rond",
"vélo d'appartement",
"station papillon",
"station poulie haute",
"tapis roulant",
"boîte à pain",
"méridienne",
"fontaine de chocolat",
"module de canapé",
"angle de canapé",
"plateau-repas",
"sablier",
"figurine jouet",
"modèle voiture",
"circuit miniature",
"distributeur jouets",
,
"baby-foot",
"taquin",
"panier d'œufs",
"paravent gris",
"machine à écrire",
"buffet design",
"hi-fi design",
"lit design",
"canapé design",
"chaise design",
"commode design",
"armoire design",
"horloge design",
"lampe design",
"table design",
"table ronde design",
"lit bois moderne",
"canapé bois moderne",
"chaise bois moderne",
"commo. bois moderne",
"armoire bois moderne",
"horloge bois moderne",
"lampe bois moderne",
"siège bois moderne",
"table bois moderne",
"étagère bois moderne",
"télé bois moderne",
"lit sirène",
"canapé sirène",
"chaise sirène",
"commode sirène",
"armoire sirène",
"horloge sirène",
"coiffeuse sirène",
"lampe sirène",
"paravent sirène",
"étagère sirène",
"table sirène",
"commode glace",
"armoire glace",
"table glace",
"chaise glace",
"desserte glace",
"lampe glace",
"étagère glace",
"canapé glace",
"lit glace",
"horloge glace",
"coiffeuse glace",
"chandelier rococo",
"lit rococo",
"bibliothèque rococo",
"canapé rococo",
"fauteuil rococo",
"commode rococo",
"penderie rococo",
"horloge rococo",
"coiffeuse rococo",
"lampe rococo",
"table rococo",
"lit nordique",
"canapé nordique",
"chaise nordique",
"commode nordique",
"armoire nordique",
"lampe nordique",
"tableau nordique",
"étagère nordique",
"table ronde nordique",
"table basse nordique",
"desserte nordique",
"lecteur CD astro",
"lit astro",
"canapé astro",
"fauteuil astro",
"commode astro",
"armoire astro",
"horloge astro",
"table astro",
"télé astro",
"étagère astro",
"lampe astro",
"tour de cartes",
"lit cartes",
"canapé cartes",
"chaise cartes",
"commode cartes",
"armoire cartes",
"horloge cartes",
"lampe cartes",
"paravent cartes",
"étagère cartes",
"table cartes",
"commode rayures",
"lampe rayures",
"armoire rayures",
"télé rayures",
"table rayures",
"canapé rayures",
"étagère rayures",
"horloge rayures",
"lit rayures",
"lavabo rayures",
"chaise rayures",
"lit négligé",
"canapé négligé",
"horloge négligée",
"chaise négligée",
"table négligée",
"armoire négligée",
"évier négligé",
"lampe négligée",
"hi-fi négligée",
"télé négligée",
"commode négligée",
"brasero",
"étendard",
"éventail de samouraï",
"buisson en carton",
"herbe en carton",
"colline en carton",
"arbre en carton",
"cacaoyer",
"fontaine eau potable",
"lierre en pot",
"lampe à génie",
,
"enseigne lumineuse",
"coq de Barcelos",
"cheval de Dala",
"attrapeur de rêves",
"statuette squelette",
"affiche bureau poste",
"horloge trèfle",
"lanterne Chine",
"poupée hawaïenne",
"statue Moai",
"masque tribal",
,
"pagode",
"statue de sirène",
"Bouche de Vérité",
,
"série matriochka",
"bol de samgyetang",
"tour Eiffel",
"drapeau pirate",
"télescope d'époque",
"armure de pirate",
"pouf guimauve",
"table carton",
"siège carton",
"canapé carton",
"armoire carton",
"lit carton",
"figurine de rat",
"figurine de buffle",
"figurine de tigre",
"figurine de lièvre",
"figurine de dragon",
"figurine de serpent",
"figurine de cheval",
"figurine de mouton",
"figurine de singe",
"figurine de coq",
"figurine de chien",
"figurine de cochon",
"écran mural",
"créateur hologrammes",
"fauteuil capitaine",
"siège équipage",
"radar de bord",
"ordinateur de bord",
"mini-ordinateur bord",
"moniteur capitaine",
"moniteur équipage",
"radar 3D",
"gâteau au chocolat",
"pot de lait et sucre",
"tasse de café",
"vitrine à desserts",
"moulin à café",
"table d'anniv",
"lot bougies d'anniv",
"panneau d'anniv",
"gâteau d'anniv",
"télésiège",
"famille de neige",
,
"pierre de curling",
"moulin à poivre",
"carnet de croquis",
"appareil photo jouet",
"moulin de Kinderdijk",
,
"carte du monde",
"bobsleigh",
"obstacle de slalom",
"réchaud de camping",
"rangement pour skis",
,
"maquette d'Uluru",
"fumoir",
"lézard de Gaudi",
"plat de songpyeons",
"cornemuse",
"maquette de Big Ben",
"canon à neige",
"assiette de raisins",
"boule aquarium",
"casse-noisettes",
,
"chaussette de fête",
"assiette de beignets",
"scooter des neiges",
"Love Tester",
"statue de la Liberté",
"fauteuil patchwork",
"commode patchwork",
"lampe patchwork",
"table patchwork",
"canapé patchwork",
"siège de shogun",
"pièce de shogi",
"pièce de reversi",
"télé ballons",
"canapé ballons",
"horloge ballons",
"lampe ballons",
"table ballons",
"lit ballons",
"chaise ballons",
"commode ballons",
"lampe-chien ballons",
"armoire ballons",
"coiffeuse ballons",
"phonographe lys",
"canapé rose",
"hi-fi tournesol",
"commode tulipe",
"paravent violette",
"lit hortensia",
"tabouret azalée",
"table pensée",
"ventilateur cosmos",
"horloge hibiscus",
,
,
,
"règle girafe",
"radio d'époque",
"lampe 0",
"lampe 1",
"lampe 2",
"lampe 3",
"lampe 4",
"lampe 5",
"lampe 6",
"lampe 7",
"lampe 8",
"lampe 9",
"Bélier à bascule",
"baignoire Taureau",
"armoire Gémeaux",
"table Cancer",
"sculpture Lion",
"harpe Vierge",
"Balance à plateaux",
"lampe Scorpion",
"arc Sagittaire",
"statue Capricorne",
"vase Verseau",
"lampe Poissons",
"lampe aurore",
"paravent aurore",
"table germe",
"horloge cerisier",
"lit feuille",
"paravent arc-en-ciel",
"lampe palmier",
"table feu d'artifice",
"coiffeuse lune",
"lit paille de riz",
"chaise automnale",
"pouf tronc d'arbre",
"tableau en liège",
"balance de cuisine",
"plateau de sushis",
"poupée kokeshi",
"maquette d'épicerie",
"DAC d'épicerie",
"rayon boissons",
"rayon sandwichs",
"enseigne d'épicerie",
"caisse d'épicerie",
"lit lasagnes",
"armoire agenda",
"canapé gomme",
"lit agenda",
"paravent stylos",
"roller de colle",
"table équerre",
"piano jouet",
"table d'examen",
"téléphone pro",
"sonnette réception",
"seau en bois",
"jus de noix de coco",
"boîte de ramen",
"tas de bûches",
"menu de fast-food",
"chandelier fantaisie",
"boîte à en-cas",
"lavabo chic",
"bague en diamant",
"ventilation",
"paravent classique",
"planche de sushis",
"synthétiseur",
"caisse à outils",
"panier à serviettes",
"barre à poignées",
"corbeille à laine",
"bureau du prof",
"banquette de train",
"pizza",
"jardinière haute",
"soupe de ramen",
"tarte",
"service fantaisie",
"jeu lancer d'anneaux",
"boule de mousse",
"dévidoir",
"étagère à plantes",
"tracteur",
"ours en bois",
"poupée porte-bonheur",
"écritoire japonais",
"composition florale",
"chariot à roulettes",
"étagère à bibelots",
"tapis mécanique",
"pompe à vélo",
"pile de livres",
"corbeille à pain",
"petit déjeuner léger",
"petit déjeuner riche",
"pile de pancakes",
"vitrine à glaces",
"arrosoir d'étain",
"trousse de soins",
"bidon à lait",
"plat d'onigiris",
"pile de billets",
"pichet en inox",
"sélection de sushis",
"lot de balles de riz",
"népenthès suspendu",
"futon",
"plateau de thé",
"b.-de-jour grimpante",
"sac Boston",
"trottinette",
"boîte à casse-croûte",
"boisson en brique",
"table parasol",
"jerrican",
"chariot élévateur",
"ensemble de plots",
"haltère",
"capsule de recherche",
"armoire à classeurs",
"placard à classeurs",
"chariot à classeurs",
"paravent accordéon",
"chaise alu et bois",
"grille de prison",
"caisse enregistreuse",
"cabine d'essayage",
"viande rôtie de dino",
"statue de villageois",
"caillebotis",
"nid d'hirondelles",
"balancelle",
"télé de bureau",
"estrade",
"poutre gymnastique",
"ballon gymnastique",
"table nappée",
"ensemble vaisselle",
"table à dessin",
"portant",
"table basse pastel",
"poisson sur planche",
"tableau menu du jour",
"comptoir en bois",
"monocycle",
"porte-serviettes",
"table alu et bois",
"armoire à roulettes",
"mât en métal",
"plant de maïs",
"vasque lavabo",
"ballon",
"panneau en verre",
"cyprès",
"vitrine de fleurs",
"buffet plateaux",
"gratin",
"porte-parapluie chic",
"bidon métallique",
"coiffeuse salon",
"ch. jardin plastique",
"sac de courses",
"meuble téléphone zen",
"parterre de fleurs",
"bac à sable",
"table d'extérieur",
"panneau interdiction",
"lavabo public",
"serre-livres",
"chariot médical",
"lit hôpital moderne",
"fauteuil pro",
"duo de sacs poubelle",
"double siège d'amphi",
"table d'amphi",
"table de réunion",
"tabouret cubique",
"établi",
"mini-réfrigérateur",
"brancard",
"caisson pro",
"boîte de crayons",
"téléphone noir",
"touret",
"équipement baseball",
"horloge pro",
"couronne de fleurs",
"pot de succulentes",
"chaise de réunion",
"téléphone public",
"chariot esthéticien",
"caisse à monnaie",
"table basse zen",
"table d'opération",
"table à marchandises",
"bureau d'hôpital",
"raquette de tennis",
"ramasse-monnaie",
"microphone de bureau",
"pile de pneus",
"casier d'écolier",
"consigne automatique",
"pupitre microphone",
"pile de cadeaux",
"cartable japonais",
"vitrine luxueuse",
"seau de pop-corn",
"tabouret de bar",
"chaise de bar zen",
"paravent vitré",
"poubelle fast-food",
"table nappée ronde",
"banc salle d'attente",
"mini-table carrée",
"table carrée métal",
"filet vert",
"table en bois brut",
"boîte d'archivage",
"chaise de jardin fer",
"table de jardin fer",
"menu enfant",
"télé murale",
"panneau d'annonces",
"bouteille thermos",
"pile de vêtements",
"distributeur en-cas",
"saxophone alto",
"lavabo rétro",
"lot de parfums",
"lot de conserves",
"duo bouteilles gaz",
"paravent shôji",
"palissade bambou",
"fauteuil massant",
"baquet",
"siège sal. réception",
"distribut. boissons",
"caisse claire",
"Wii U",
"pile de documents",
"chaise Chine",
"boisson fraîche",
"granité",
"fauteuil hall",
"poubelle roulettes",
"range-pantoufles",
"plaque à teppanyaki",
"caisse colorée",
"four en pierre",
"sac à main",
"microphone argenté",
"console d'orgue",
,
"trompette",
"table de mixage",
"plan travail resto",
"réfrigérateur resto",
"menu japonais",
"basse électrique",
"table de café",
"chariot de service",
"comptoir réception",
"enseigne d'extérieur",
"lot de magazines",
"horloge ciseaux",
"siège porte-crayons",
"socle expo planches",
"socle expo commun",
"socle expo chic",
"socle expo simple",
"rayon de magasin",
"spot de sol",
"banc en cuir",
"boîte repas",
"menu du jour",
"présentoir à skates",
"bureau pro courbe",
"corbeille ordinaire",
"fauteuil coiffeur",
"plateau de daimyo",
"rose simple",
,
"boîte à vinyles",
"vélo de ville",
"grand ampli",
"caméscope",
"baffle",
"lave-vaisselle resto",
"meuble de pharmacie",
"plat de saucisses",
"chaîne de balisage",
"ensemble jardinage",
"servante d'atelier",
"but de football",
"enseigne électrique",
"enseigne élec. ronde",
"miroir de table",
"armoire 4 casiers",
"robinet de jardin",
"jardinière tonneau",
"petit rocher jardin",
"grand rocher jardin",
"banc naturel",
"fauteuil naturel",
"table naturelle",
"table bas. naturelle",
"lampe naturelle",
"chaise élégante",
"banc élégant",
"voiture compacte",
"voiture de sport",
,
"plat de pâtes",
"plateau de fromages",
"plat de tacos",
"plateau kaiseki",
"paravent lierre",
"tasse de thé",
"bol de donburi",
"cloison simple",
"planche à découper",
"nécessaire à pain",
"cuisinière resto",
"vitrine d'exposition",
"table de comptoir",
"vitrine à bijoux",
"faux canard",
"curry indien",
"douche moderne",
"série d'autographes",
"assiette ornementale",
"paravent mosaïque",
"enceinte retour",
"jeu livres sanglés",
"plateau de jeu",
"étagère à outils",
"bassine s. de bains",
"électrocardiographe",
"commode basse zen",
"lys casablanca",
"bol d'udon",
"boîte de donuts",
"sashimi pois.-ballon",
"pastèque",
"homard cuit",
"omelette",
"paëlla",
"paravent rétro",
"banc en bambou",
"panneau arrêt de bus",
"casier à chaussures",
"guichet de réception",
"buffet garni",
,
"théière en verre",
"machine à expresso",
"chaise au sol",
"plat Chine",
"console à tiroirs",
"coussin circulaire",
"chaise suspendue",
"lampe de jardin",
"tablette salle d'eau",
,
"coussin rond",
"chaise en osier",
"zabuton",
"tas de papiers",
"grande table à thé",
,
,
,
,
"rayon Wii U",
"rayon Nintendo 3DS",
"rayon amiibo",
,
"Game Boy géante",
"broche BBQ",
"nid wyverne volante",
"chasseur",
"Aile rouge",
"statue Felyne",
"charrette Felyne",
"tableau Felyne",
"coffre à objets",
"poogie",
"ruche",
"banc maki",
"congélateur à glaces",
"panier d'épicerie",
"drapeau d'épicerie",
"vitrine plats chauds",
"mach. café épicerie",
"gâteau géant",
"maison bonbons",
"OVNI",
"fourmi géante",
"montagne",
,
"soleil",
"montagne de billets",
"fait-tout géant",
"calèche",
"tasse de café géante",
"nounours géant",
"robot géant",
"tour d'écrans",
"tente",
"avion à hélices",
"sous-marin",
"voiture de luxe",
"œuf géant",
"personnage gonflable",
"horloge arbre",
"super coquillage",
"panneau TV-Chromap.",
"table TV-Chromapolis",
"stand mobile",
"obstacle gonflable",
"siège TV-Chromapolis",
"Liquidateur griffé",
"panneau festival (G)",
"panneau festival (D)",
"point de déploiement",
"ensemble TV & meuble",
"carte île déserte",
"poêle à frire",
"table île déserte",
"tabouret île déserte",
"commode Hello Kitty",
"arbuste Hello Kitty",
"lit Hello Kitty",
"table Hello Kitty",
"chaise Hello Kitty",
"horloge Hello Kitty",
"horloge Hello Kitty",
"lit My Melody",
"horloge My Melody",
"horloge My Melody",
"chaise My Melody",
"coiffeuse My Melody",
"table My Melody",
"lit Pompompurin",
"chaise Pompompurin",
"buffet Pompompurin",
"table Pompompurin",
"gâteau Pompompurin",
"télé Pompompurin",
"télé Pompompurin",
"lit Kiki & Lala",
"horloge Kiki & Lala",
"horloge Kiki & Lala",
"table Kiki & Lala",
"canapé Kiki & Lala",
"machine à nuages",
"table Cinnamoroll",
"parasol Cinnamoroll",
"canapé Cinnamoroll",
"menu Cinnamoroll",
"tabouret Cinnamoroll",
"plateau Cinnamoroll",
"table basse étang",
"friandise étang",
"lampe étang",
"pont étang",
"porte coul. étang",
"poupée en papier",
"New 3DS XL HHD",
"New 3DS Marie",
"New 3DS Layette",
"New 3DS Cousette",
"New 3DS Kéké",
"New 3DS Méli et Mélo",
"auto Nook Immobilier",
"scooter Marie",
"bombe",
"fée en flacon",
"coffre trés. Hyrule",
"statuette de cocotte",
"pierre à potins",
"cœur",
"réceptacle de cœur",
"fragment de cœur",
"lait Lon Lon",
"lune de Termina",
"bouclier d'Hyrule",
"parc. Héros du temps",
"rubis",
"maquette de bus",
"figurine d'Amiral",
"banc Nintendo",
"statuette chihuahua",
"statuette dalmatien",
"statuette teckel",
"statuette labrador",
"commode GameCube",
"placard télécom. Wii",
"banc DS Lite",
"banc Nintendo DSi",
"étang aux nénuphars",
"horloge 7-Eleven",
"coussin donut",
"œuf d'Otomon",
"statuette de Navirou",
"fait-tout Fueki",
"chaise Fueki",
"armoire Fueki",
"hi-fi Fueki",
"table Fueki",
"couss. Puzzle League",
,
,
,
,
,
"kit de couture",
"tapisserie à frises",
"bouquet tropical A",
"bouquet tropical B",
"enseigne Mélimélo",
"rangée de chariots",
"carton de casques",
"reste de pizza",
"poubelle débordante",
"valise de Charly",
,
,
"gâteau 2017",
"sapin enneigé",
"livre épais",
"horloge musée",
"équipement électron.",
"tas de clochettes",
"graphique ventes",
"paillasson Nook Immo",
"horloge mur R&R",
"paillasson R&R",
"set de charpenterie",
"meuble rangement R&R",
"paillasson Blaise",
"lot boîtes à chauss.",
"équipement de cireur",
"microphone annonces",
"panneau de plans",
"platine DJ Kéké",
"étui à guitare",
"paillasson Mélimélo",
"paillasson musée",
"maquette Nook Immo",
"tableau de Morsicus",
"manuel instructions"
],

//Mannequins
[],

//Art
[
"toile déferlante",
"toile solennelle",
"toile charmante",
"toile classique",
"toile célèbre",
"toile parfaite",
"toile incroyable",
"toile magnifique",
"toile émouvante",
"toile commune",
"toile florale",
"toile radieuse",
"toile potagère",
"toile réussie",
"toile effrayante",
"toile austère",
"toile neutre",
"toile précieuse",
"toile apaisante",
"toile puissante",
"toile nacrée",
"toile royale",
"toile hivernale",
"toile sauvage",
"toile gracieuse",
"statue féminine",
"statue héroïque",
"statue majestueuse",
"statue athlétique",
"statue imposante",
"statue mystérieuse",
"statue antique",
"statue maternelle",
"toile déferlante (contrefaçon)",
"toile solennelle (contrefaçon)",
"toile charmante (contrefaçon)",
"toile classique (contrefaçon)",
"toile célèbre (contrefaçon)",
"toile incroyable (contrefaçon)",
"toile émouvante (contrefaçon)",
"toile potagère (contrefaçon)",
"toile effrayante (contrefaçon)",
"toile neutre (contrefaçon)",
"toile nacrée (contrefaçon)",
"toile royale (contrefaçon)",
"toile sauvage (contrefaçon)",
"toile gracieuse (contrefaçon)",
"statue féminine (contrefaçon)",
"statue héroïque (contrefaçon)",
"statue majestueuse (contrefaçon)",
"statue athlétique (contrefaçon)",
"statue imposante (contrefaçon)",
"statue mystérieuse (contrefaçon)",
"statue antique (contrefaçon)",
"statue maternelle (contrefaçon)"
],

//Fossils
[
"ambre",
,
"crotte de dinosaure",
"œuf de dinosaure",
"fossile de fougère",
"empreinte de dino",
"archéoptéryx",
"homme de Pékin",
"dent de requin",
,
"crâne de T. rex",
"corps de T. rex",
"queue de T. rex",
"crâne de tricératops",
"corps de tricératops",
"queue de tricératops",
"crâne de mammouth",
"corps de mammouth",
"crâne d'ankylosaure",
"torse d'ankylosaure",
"queue d'ankylosaure",
"crâne d'apatosaure",
"corps d'apatosaure",
"queue d'apatosaure",
"crâne de dimétrodon",
"corps de dimétrodon",
"queue de dimétrodon",
"crâne d'iguanodon",
"torse d'iguanodon",
"queue d'iguanodon",
"crâne de smilodon",
"torse de smilodon",
"crâne de pachycéphal",
"torse de pachycéphal",
"queue de pachycéphal",
"crâne de parasauro",
"torse de parasauro",
"queue de parasauro",
"crâne de séismo",
"cou de séismo",
"torse de séismo",
"hanche de séismo",
"queue de séismo",
"crâne de plésiosaure",
"cou de plésiosaure",
"corps de plésiosaure",
"crâne de stégosaure",
"corps de stégosaure",
"queue de stégosaure",
"crâne de ptéra",
"aile gauche de ptéra",
"aile droite de ptéra",
"crâne d'ichtyosaure",
"corps d'ichtyosaure",
"crâne de raptor",
"corps de raptor",
"crâne de styraco",
"corps de styraco",
"queue de styraco",
"crâne de spinosaurus",
"corps de spinosaurus",
"queue de spinosaurus",
"crâne de bronto",
"corps de bronto",
"queue de bronto",
"crâne d'archelon",
"corps d'archelon",
"maquette de T. rex",
"maquette tricératops",
"maquette mammouth",
"maquette ankylosaure",
"maquette apatosaure",
"maquette dimétrodon",
"maquette d'iguanodon",
"maquette de smilodon",
"maquette pachycéphal",
"maquette parasauro",
"maquette séismosaure",
"maquette plésiosaure",
"maquette stégosaure",
"maquette ptéranodon",
"maquette ichtyosaure",
"maquette de raptor",
"maquette de styraco",
"maquette spinosaurus",
"maquette de bronto",
"maquette d'archelon"
],

//Pics
[
"photo de Cyrano",
"photo d'Antonio",
"photo de Mathilda",
"photo d'Anabelle",
"photo de Tarina",
"photo de Roberta",
"photo de Blair",
"photo de Teddy",
"photo de Rosine",
"photo de Curt",
"photo de Chulin",
"photo de Nathan",
"photo de Ronchon",
"photo de Tutu",
"photo d'Oursula",
"photo de Grizzly",
"photo de Wendy",
"photo d'Isaac",
"photo de Zabou",
"photo d'Eustache",
"photo de Klaus",
"photo de Gérard",
"photo de Robie",
"photo de Miguel",
"photo de Titi",
"photo de Gilbert",
"photo de Neige",
"photo de Maréchal",
"photo de Michèle",
"photo de Jacob",
"photo de Condor",
"photo de Jacky",
"photo de Pec",
"photo de Darius",
"photo de Médolie",
"photo d'Angus",
"photo de Flèche",
"photo de Beubeu",
"photo de Steakos",
"photo d'Arnold",
"photo de Toto",
"photo de Robert",
"photo de Mistigri",
"photo de Rosie",
"photo d'Olivia",
"photo de Kiki",
"photo de Marine",
"photo de Cédric",
"photo de Perle",
"photo de Momo",
"photo de Kabuki",
"photo de Câlin",
"photo de Monique",
"photo de Tigri",
"photo de Tupux",
"photo de Kitty",
"photo de Tom",
"photo de Suzy",
"photo de Maud",
"photo de Linette",
"photo de Neferti",
"photo de Rougepif",
"photo de Kat",
"photo de Felyne",
"photo de Myrtille",
"photo de Léa",
"photo de Théo",
"photo de Gradub",
"photo de Bill",
"photo de Miro",
"photo de Vladimir",
"photo d'Eddie",
"photo de Grisa",
"photo de Rosalie",
"photo d'Agnès",
"photo de Pauline",
"photo de Placide",
"photo de Manu",
"photo de Vanessa",
"photo de Marty",
"photo de Pouli",
"photo de Dimitri",
"photo d'Herbert",
"photo d'Eva",
"photo de Sonya",
"photo de Poulette",
"photo de Wolfram",
"photo de Jo",
"photo de Ken",
"photo de Margaux",
"photo de Valé",
"photo de Norma",
"photo de Maiko",
"photo d'Alphonse",
"photo d'Allie",
"photo de Croko",
"photo d'Hector",
"photo de Chuck",
"photo d'Odile",
"photo de Drago",
"photo de Bibi",
"photo de Nacer",
"photo de Régis",
"photo de Boubou",
"photo de Bichoune",
"photo de Jon",
"photo de Rosanne",
"photo de Stefaon",
"photo de Didi",
"photo d'Abraham",
"photo de Chelsea",
"photo de Mirza",
"photo d'Avril",
"photo de Ramsès",
"photo de Crocket",
"photo de Nonos",
"photo de Dalma",
"photo de George",
"photo de Naomie",
"photo de Cookie",
"photo d'Olympe",
"photo de Béa",
"photo de Brutus",
"photo d'Ismaël",
"photo de Bernardo",
"photo d'Anna",
"photo de Mehdi",
"photo de Choco",
"photo de Joseph",
"photo de Terrine",
"photo de Maëlle",
"photo de Mina",
"photo de Pompon",
"photo de Mallory",
"photo de Caro",
"photo de Prof",
"photo de Colvert",
"photo de Scooter",
"photo de Bébert",
"photo de Maëllis",
"photo de Ketchup",
"photo de Déborah",
"photo de Molly",
"photo de Narcisse",
"photo d'Opaline",
"photo de Pachy",
"photo de Miles",
"photo d'Éloïse",
"photo de Maguy",
"photo de Paolo",
"photo d'Axel",
"photo d'Ella",
"photo de Barry",
"photo de Fanny",
"photo de Chaï",
"photo de Raina",
"photo de Crabot",
"photo de Verbert",
"photo de Milos",
"photo de Gordon",
"photo de Crakos",
"photo de Rénata",
"photo de Jérémie",
"photo de Rénato",
"photo de Figaro",
"photo de Bajoue",
"photo de Prince",
"photo de Gambette",
"photo de Fabien",
"photo de Gloria",
"photo de Carlos",
"photo de Violette",
"photo d'Henri",
"photo de Biquette",
"photo de Nana",
"photo de Seguin",
"photo de Grognon",
"photo de Véra",
"photo de Moktar",
"photo de Chavrina",
"photo de César",
"photo de Gogo",
"photo de Babouin",
"photo de Louis",
"photo de Primo",
"photo de Gaëlle",
"photo de Gustave",
"photo de Gertrude",
"photo de Loran",
"photo de Rilla",
"photo de Jojo",
"photo d'Esther",
"photo de Graham",
"photo de Chico",
"photo de Stella",
"photo de Guido",
"photo d'Emma",
"photo de Charles",
,
"photo de Bebel",
"photo d'Hippy",
"photo de Bertha",
"photo de Biff",
"photo de Potama",
"photo de Bob",
"photo de Paulito",
"photo de Daniel",
"photo de Victoria",
"photo de Savana",
"photo de Martin",
"photo de Rosco",
"photo d'Anne",
"photo d'Édouard",
"photo de Cléa",
"photo de Prune",
"photo d'Âne-lise",
"photo de Dorian",
"photo de Tony",
"photo de Bourrico",
"photo de Lico",
,
"photo d'Épona",
"photo de Calypso",
"photo d'Alice",
"photo de Melba",
"photo de Koaline",
"photo de Gonzo",
"photo de Koko",
"photo de Kolala",
"photo de Kalyptus",
"photo de Jamy",
"photo de Poquette",
"photo de Mathilde",
"photo de Kanga",
"photo de Rhona",
"photo de Madsi",
"photo de Walt",
"photo de Mike",
"photo de Selma",
"photo de Léonard",
"photo d'Elvis",
"photo de Léo",
"photo de Leandro",
"photo d'Aimé",
"photo d'Hercule",
"photo de Léopold",
"photo de Mireille",
"photo de Simon",
"photo de Lili",
"photo de Lourant",
"photo d'Élise",
"photo de Rudy",
"photo de Luna",
"photo de Magogo",
"photo de Dora",
"photo de Gruyère",
"photo de Belle",
"photo de Quenotte",
"photo de Samson",
"photo de Marcel",
"photo de Sucrette",
"photo de Sourizzi",
"photo d'Annie",
"photo de Steven",
"photo de Joachim",
"photo de Sabrina",
"photo de Greta",
"photo de Missy",
"photo de Mozzar",
"photo d'Octave",
"photo de Marina",
"photo de Marvin",
"photo de Pigmento",
"photo de Reine",
"photo de Gladys",
"photo d'Ottie",
"photo de Laflèche",
"photo de Julie",
"photo de Gabin",
"photo de Phil",
"photo de Sophie",
"photo de Justine",
"photo de Faustine",
"photo d'Apollon",
"photo d'Aurélie",
"photo de Napoléon",
"photo de Phébus",
"photo de Faust",
"photo de Greggae",
"photo de Manfred",
"photo d'Enzo",
"photo de Garance",
"photo d'Aurore",
"photo de Reynald",
"photo de Cube",
"photo de Victor",
"photo de Friga",
"photo de Gwen",
"photo d'Hervé",
"photo de Miglou",
"photo d'Ethan",
"photo d'Urbain",
"photo d'Émilien",
"photo de Nora",
"photo de Laurie",
"photo de Tirbou",
"photo de Trufa",
"photo de Salami",
"photo de Bonno",
"photo de Lucie",
"photo de Justin",
"photo de Porken",
"photo de Boris",
"photo de Marjorie",
"photo de Rose",
"photo de Camille",
"photo d'Aaron",
"photo de Jean-Bon",
"photo de Lydie",
"photo de Pansy",
"photo de Ganon",
"photo de Clara",
"photo de Dorothée",
"photo de Coco",
"photo de Jeannot",
"photo de Gaston",
"photo de Gaby",
"photo de Nadia",
"photo de Tiphaine",
"photo de Kali",
"photo de Rubis",
"photo de Doc",
"photo de Claude",
"photo de Nadine",
"photo de Kristine",
"photo de Grignote",
"photo de Civet",
"photo de Zoé",
"photo de Sylvette",
"photo d'Épicure",
"photo de Grisette",
"photo de Toby",
"photo de Ben",
"photo de Renée",
"photo de Rhino",
"photo de Cornio",
"photo de Patty",
"photo de Rina",
"photo d'Hélaine",
"photo de Bêêtty",
"photo de Bérénice",
"photo de Bigoudi",
"photo de Cashmir",
"photo de Maï",
"photo de Tonton",
"photo de Karen",
"photo de Sélène",
"photo de Clarabêl",
"photo de Charlène",
"photo de Pietro",
"photo d'Étoile",
"photo de Rachida",
"photo de Cachou",
"photo de Filibert",
"photo de Pécan",
"photo de Lola",
"photo de Ninjette",
"photo d'Isabelle",
"photo de Damia",
"photo d'Électro",
"photo d'Amande",
"photo de Rocky",
"photo de Célia",
"photo de Nadeige",
"photo de Mounia",
"photo d'Irène",
"photo de Roy",
"photo de Mathéo",
"photo de Pamela",
"photo de Kala",
"photo de Mara",
"photo de Ralf",
"photo de Marito",
"photo de Jeff",
"photo de Bengale",
"photo de Dolph",
"photo de Vanina",
"photo de Noémie",
"photo de Chef",
"photo de Lobo",
"photo de Wolfgang",
"photo de Blanche",
"photo de Loupiot",
"photo de Luppa",
"photo de Pierrot",
"photo de Viviane",
"photo de Marilou",
"photo de Gary",
"photo de Link loup"
],

//Pics (special)
[
"photo de Blanca",
"photo d'Albin",
"photo de Rodolphe",
"photo de Resetti",
"photo de Don",
"photo de Cathie",
"photo de Kéké"
],

//Pics (special)
[
"photo de Serge",
"photo de Risette",
"photo de Castor",
"photo d'Hélium",
"photo de Porcella",
"photo d'Astrid",
"photo de Djarod",
"photo de Sarah",
"photo de Kéké",
"photo de Rounard",
"photo de Carla",
"photo de Maria",
"photo de Layette",
"photo de Cousette",
"photo de Mamiral",
"photo de Liliane",
"photo d'Amiral",
"photo de Lila",
"photo de Mélo",
"photo de Méli",
"photo de Lazare",
"photo de Don",
"photo de Resetti",
"photo de Lionel",
"photo de Thibou",
"photo de Céleste",
"photo de Roberto",
"photo d'Opélie",
"photo d'Élisabec",
"photo de Robusto",
"photo de Jacqu'O",
"photo de Chausset",
"photo d'Antoine",
"photo de Maret",
"photo de Ginette",
"photo de Tom Nook",
"photo de Gulliver",
"photo de Pascal",
"photo de Blaise",
"photo de Marie",
"photo de Tortimer",
"photo de Dindou",
"photo de Ciboulot",
"photo de Charly",
"photo de Racine",
"photo de Blanca",
"photo de Serena",
"photo de DJ Kéké",
"photo de Cathie",
"photo d'Albin",
"photo de Rodolphe",
"photo de Max",
"photo de Morsicus",
"photo de Lou"
],

//Tools & wearables
[
"hache (prêt)",
"hache",
"hache d'argent",
"hache dorée",
"filet (prêt)",
"filet",
"filet d'argent",
"filet doré",
"canne à pêche (prêt)",
"canne à pêche",
"canne à pêche argent",
"canne à pêche dorée",
"pelle (prêt)",
"pelle",
"pelle d'argent",
"pelle dorée",
"arrosoir (prêt)",
"arrosoir",
"arrosoir d'argent",
"arrosoir doré",
"lance-pierre (prêt)",
"lance-pierre",
"lance-pierre argent",
"lance-pierre doré",
"marteau plas. (prêt)",
"marteau en plastique",
"mégaphone",
"chrono",
"cierge magique",
"chandelle romaine",
"pétard",
"lance-bulles",
"ballon lapin rouge",
"ballon lapin orange",
"ballon lapin jaune",
"ballon lapin vert",
"ballon lapin b. ciel",
"ballon lapin bleu",
"ballon lapin violet",
"ballon lapin rose",
"ballon rouge",
"ballon orange",
"ballon jaune",
"ballon vert",
"ballon bleu ciel",
"ballon bleu",
"ballon violet",
"ballon rose",
"ballon cœur rouge",
"ballon cœur orange",
"ballon cœur jaune",
"ballon cœur vert",
"ballon cœur b. ciel",
"ballon cœur bleu",
"ballon cœur violet",
"ballon cœur rose",
"moulin rouge",
"moulin orange",
"moulin jaune",
"moulin vert",
"moulin bleu ciel",
"moulin bleu",
"moulin mauve",
"moulin rose"
],

//Uncategorized 2
[
"café",
"cocktail de fruits",
"panier de haricots",
"maki porte-bonheur",
"cornet vanille",
"cornet chocolat",
"cornet pistache",
"cornet fraise",
"glace fruits confits",
"glace à la framboise",
"glace citron-menthe",
"glace tropical-melon",
"baguette fluo bleue",
"baguette fluo verte",
"baguette fluo rose",
"baguette fluo jaune",
"baguette églantine",
"baguette Kiki & Lala",
"sans-gêne",
"fontaine d'artifice",
"feu d'artifice usagé",
"sac de père Noël",
"sac mystère",
"sachet de café banal",
"sachet de bon café",
"sachet de café extra",
"pièce en chocolat"],

//Uncategorized 3
[
"pétition",
"pétition",
"vieux document",
"objet perdu (livre)",
"objet perdu (bourse)",
"objet perdu (moufle)",
"objet perdu (sac en papier)",
"serviette"
],

//Fortune cookies
[
"gâteau de la chance",
"prédiction nº 1",
"prédiction n° 2",
"prédiction n° 3",
"prédiction n° 4",
"prédiction n° 5",
"prédiction n° 6",
"prédiction n° 7",
"prédiction n° 8",
"prédiction n° 9",
"prédiction n° 10",
"prédiction n° 11",
"prédiction n° 12",
"prédiction n° 13",
"prédiction n° 14",
"prédiction n° 15",
"prédiction n° 16",
"prédiction n° 17",
"prédiction n° 18",
"prédiction n° 19",
"prédiction n° 20",
"prédiction n° 21",
"prédiction n° 22",
"prédiction n° 23",
"prédiction n° 24",
"prédiction n° 25",
"prédiction n° 26",
"prédiction n° 27",
"prédiction n° 28",
"prédiction n° 29",
"prédiction n° 30",
"prédiction n° 31",
"prédiction n° 32",
"prédiction n° 33",
"prédiction n° 34",
"prédiction n° 35",
"prédiction n° 36",
"prédiction n° 37",
"prédiction n° 38",
"prédiction n° 39",
"prédiction n° 40",
"prédiction n° 41",
"prédiction n° 42",
"prédiction n° 43",
"prédiction n° 44",
"prédiction n° 45",
"prédiction n° 46",
"prédiction n° 47",
"prédiction n° 48",
"prédiction n° 49",
"prédiction n° 50"
],

//Fortune cookies
[
"gâteau de la chance",
"prédiction nº 1",
"prédiction nº 2",
"prédiction nº 3",
"prédiction nº 46",
"prédiction nº 5",
"prédiction nº 49",
"prédiction nº 7",
"prédiction nº 8",
"prédiction nº 9",
"prédiction nº 10",
"prédiction nº 11",
"prédiction nº 12",
"prédiction nº 13",
"prédiction nº 14",
"prédiction nº 15",
"prédiction nº 50",
"prédiction nº 17",
"prédiction nº 18",
"prédiction nº 19",
"prédiction nº 20",
"prédiction nº 21",
"prédiction nº 22",
"prédiction nº 23",
"prédiction nº 24",
"prédiction nº 25",
"prédiction nº 26",
"prédiction nº 27",
"prédiction nº 28",
"prédiction nº 29",
"prédiction nº 48",
"prédiction nº 31",
"prédiction nº 32",
"prédiction nº 33",
"prédiction nº 34",
"prédiction nº 35",
"prédiction nº 36",
"prédiction nº 37",
"prédiction nº 47",
"prédiction nº 39",
"prédiction nº 40",
"prédiction nº 41",
"prédiction nº 42",
"prédiction nº 43",
"prédiction nº 44",
"prédiction nº 45",
"prédiction nº 4",
"prédiction nº 38",
"prédiction nº 30",
"prédiction nº 6",
"prédiction nº 16",
"prédiction nº 51",
"prédiction nº 52",
"prédiction nº 53",
"prédiction nº 54",
"prédiction nº 55",
"prédiction nº 56",
"prédiction nº 57"
],

//Tickets
[
"rounardise",
"ticket perdant",
"ticket boum",
"ticket bang",
"ticket driiiing",
"ticket crakboum",
"ticket poiiiing",
"ticket badabim",
"ticket vroum-vroum",
"ticket hip-hip-hip"
],

//In-game events
[
"grille de bingogo",
"grille périmée",
"capsule temporelle",
"liste de meubles"
],

//Unused furniture (only inside)
[],

//HRA exhibition (only inside)
[
"boîte lettres rouge",
"boîte lettres métal",
"boîte lettres bleue",
"boîte lettres jaune",
"boîte lettres orange",
"boîte lettres verte",
"boîte lettres d'or",
"boîte lettres bois",
"b. lettres blanche",
"boîte lettres rose",
"boîte lettres zen",
"boîte lettres récup",
"boîte lettres inox",
"boîte lettres carrée",
"b. lettres bleu ciel",
"boîte lettres cyan",
"boîte lettres sirène",
"boîte lettres rotin",
"boîte lettres fable",
"boîte lettres royale",
"boîte lettres baril",
"b. lettres bonbons",
"porte arc à hublot",
"porte arc poisson",
"porte arc astro",
"porte arc à fenêtre",
"porte arc jaune",
"porte arc en métal",
"porte arc rafistolée",
"porte arc bonbons",
"porte arc sirène",
"porte arc zen",
"porte arc chalet",
"porte arc fable",
"porte arc marron",
"porte arc verte",
"porte arc massive",
"porte arc bleue",
"porte arc beige",
"porte arc Chine",
"porte arc rose",
"porte arc enfant",
"porte arc bambou sec",
"porte arc d'or",
"porte à hublot",
"porte poisson",
"porte astro",
"porte à fenêtre",
"porte jaune",
"porte en métal",
"porte rafistolée",
"porte bonbons",
"porte sirène",
"porte zen",
"porte chalet",
"porte fable",
"porte marron",
"porte verte",
"porte massive",
"porte bleue",
"porte beige",
"porte Chine",
"porte rose",
"porte enfant",
"porte en bambou sec",
"toit rouge",
"toit en tuile verte",
"toit en bardeau bleu",
"toit astro",
"toit enfant",
"toit noir moderne",
"toit en paille",
"toit en tuile noire",
"toit fable",
"toit ranch",
"toit baraquement",
"toit en béton",
"toit bonbons",
"toit blanc",
"toit bardeau mauve",
"toit en paille noire",
"toit sirène",
"toit simple bleu",
"toit mauve",
"toit rose",
"toit noir",
"toit jaune paille",
"toit fuchsia",
"toit en bardeau noir",
"toit marron",
"toit en herbe",
"toit en pierre",
"toit vert fable",
"toit pierre rustique",
"toit simple vert",
"toit simple gris",
"toit d'or",
"toit bleu",
"toit jaune",
"toit vert",
"clôture de corde",
"clôture de piquets",
"clôture de rondins",
"clôture végétale",
"clôture sirène rose",
"clôture sirène bleue",
"clôture brique rouge",
"clôture brique grise",
"clôture rose",
"clôture fable",
"clôture de ferme",
"clôture ondulation",
"clôture bleue",
"clôture fantaisie",
"clôture zen",
"clôture de barbelés",
"clôture bonbons",
"clôture en béton",
"clôture baraquement",
"clôture bambou sec",
"clôture vég. taillée",
"clôture de parpaing",
"clôture d'or",
"façade en brique",
"façade exotique",
"façade pierre taille",
"façade astro",
"façade enfant",
"façade simple",
"façade rotin",
"façade zen",
"façade fable",
"façade chalet",
"façade baraquement",
"façade en béton",
"façade bonbons",
"façade briq. blanche",
"façade chaumière",
"façade brique marron",
"façade sirène",
"façade grange rouge",
"façade chaumière B",
"façade rose",
"façade bleue",
"façade orange",
"façade jardin",
"façade jaune",
"façade blanche",
"façade en stuc",
"façade en pierre",
"façade verte",
"façade en terre",
"façade royale",
"façade noire",
"façade d'or",
"terrasse colorée",
"terrasse en pierre",
"terrasse en brique",
"terrasse de galets",
"terrasse dalle jaune",
"terrasse en béton",
"terrasse briq. bleue",
"terrasse dalle rose",
"terrasse marron",
"maison de campagne",
"château zen",
"château",
"villa moderne"
],

//Presents
[],

//New furniture (update)
[
"lampe magique",
,
,
,
"trophée radeau"
]];