/* Animal Crossing: New Leaf (Welcome amiibo) item list (DE) for Save Editor */

var ITEM_GROUPS_TRANSLATED=[

//Patterns
[],

//Outside flowers
[
"Papageitulpe",
"Triumphtulpe",
"Viridifloratulpe",
"Grengjer-Tulpe",
"Wildtulpe",
"Römertulpe",
"Flachlandtulpe",
"Pfingstveilchen",
"Hornveilchen",
"Alpenveilchen",
"Hainveilchen",
"Stiefmütterchen",
"Duftveilchen",
"Gartenprimel",
"Kissenprimel",
"Aurikel",
"Sumpfprimel",
"Zwergprimel",
"Kugelprimel",
"Liebesrose",
"Unschuldsrose",
"Bernsteinrose",
"Pinkrose",
"Sonnenrose",
"Lilarose",
"Schwarzrose",
"Blaurose",
"Goldrose",
"Bartnelke",
"Heidenelke",
"Federnelke",
"Osterlilie",
"Pyrenäenlilie",
"Rotlilie",
"Feuerlilie",
"Türkenbundlilie",
"Dunkellilie",
"Waldveilchen",
"Blauveilchen",
"Grabenveilchen",
"Galmeiveilchen",
"Maiglöckchen",
"Glückskleeblatt",
"Löwenzahn",
"Pusteblume"],

//Outside flowers (wilted)
,

//Fruit trees
[],

//More trees
[],

//More trees (2)
[],

//Bushes
[],

//Weeds
[],

//Weeds (2)
[],

//Rocks
[],

//Uncategorized
[],

//Fruit
[
"Apfel",
"Orange",
"Birne",
"Pfirsich",
"Kirsche",
"Kokosnuss",
"Durianfrucht",
"Zitrone",
"Litschi",
"Mango",
"Persimone",
"Banane",
"Bambussprosse",
"1a-Apfel",
"1a-Orange",
"1a-Birne",
"1a-Pfirsich",
"1a-Kirsche",
"Wurm-Apfel",
"Wurm-Orange",
"Wurm-Birne",
"Wurm-Pfirsich",
"Wurm-Kirsche"
],

//Fruits
[
"Apfelkorb",
"Orangenkorb",
"Birnenkorb",
"Pfirsichkorb",
"Kirschenkorb",
"Kokosnusskorb",
"Durianfruchtkorb",
"Zitronenkorb",
"Litschikorb",
"Mangokorb",
"Persimonenkorb",
"Bananenkorb",
"Bambussprossenkorb",
"1a-Apfelkorb",
"1a-Orangenkorb",
"1a-Birnenkorb",
"1a-Pfirsichkorb",
"1a-Kirschenkorb"
],

//Garden
[
"Fossil",
"Dünger",
"Bäumchen",
"Zedernbäumchen",
"Stechpalme",
"Heckenazalee",
"Gartenazalee",
"Seehortensie",
"Abendhortensie",
"Bluthibiskus",
"Sommerhibiskus",
"Duftblütenbusch",
"Geschenk",
,
"Papageitulpe (bag)",
"Triumphtulpe (bag)",
"Viridifloratulpe (bag)",
"Grengjer-Tulpe (bag)",
"Wildtulpe (bag)",
"Römertulpe (bag)",
"Flachlandtulpe (bag)",
"Pfingstveilchen (bag)",
"Hornveilchen (bag)",
"Alpenveilchen (bag)",
"Hainveilchen (bag)",
"Stiefmütterchen (bag)",
"Duftveilchen (bag)",
"Gartenprimel (bag)",
"Kissenprimel (bag)",
"Aurikel (bag)",
"Sumpfprimel (bag)",
"Zwergprimel (bag)",
"Kugelprimel (bag)",
"Liebesrose (bag)",
"Unschuldsrose (bag)",
"Bernsteinrose (bag)",
"Pinkrose (bag)",
"Sonnenrose (bag)",
"Lilarose (bag)",
"Schwarzrose (bag)",
"Blaurose (bag)",
"Goldrose (bag)",
"Bartnelke (bag)",
"Heidenelke (bag)",
"Federnelke (bag)",
"Osterlilie (bag)",
"Pyrenäenlilie (bag)",
"Rotlilie (bag)",
"Feuerlilie (bag)",
"Türkenbundlilie (bag)",
"Dunkellilie (bag)",
"Waldveilchen (bag)",
"Blauveilchen (bag)",
"Grabenveilchen (bag)",
"Galmeiveilchen (bag)"
],

//Items
[
"Geschenkpapier",
"Medizin",
"Schokoladenherz",
"Perlmuschelschale",
"Tritonshorn",
"Riesenmuschelschale",
"Koralle",
"Stachelschneckenhaus",
"Kammmuschelschale",
"Kreiselschneckenhaus",
"Kaurischneckenhaus",
"Sanddollar",
"Austernschale",
"Bonbon",
"Lolli",
"Elegantpilz",
"Rundpilz",
"Dürrpilz",
"Flachpilz",
"Seltenpilz",
"Berühmtpilz",
"Honigwabe",
"Falle",
"Superfalle",
"Golderz",
"Silbererz",
"Rubin",
"Saphir",
"Smaragd",
"Amethyst",
"Butter",
"Milch",
"Essig",
"Mehl",
"Zucker",
"100-Sterni-Münze",
"200-Sterni-Münze",
"300-Sterni-Münze",
"400-Sterni-Münze",
"500-Sterni-Münze",
"600-Sterni-Münze",
"700-Sterni-Münze",
"800-Sterni-Münze",
"900-Sterni-Münze",
"1.000-Sterni-Sack",
"2.000-Sterni-Sack",
"3.000-Sterni-Sack",
"4.000-Sterni-Sack",
"5.000-Sterni-Sack",
"6.000-Sterni-Sack",
"7.000-Sterni-Sack",
"8.000-Sterni-Sack",
"9.000-Sterni-Sack",
"10.000-Sterni-Sack",
"11.000-Sterni-Sack",
"12.000-Sterni-Sack",
"13.000-Sterni-Sack",
"14.000-Sterni-Sack",
"15.000-Sterni-Sack",
"16.000-Sterni-Sack",
"17.000-Sterni-Sack",
"18.000-Sterni-Sack",
"19.000-Sterni-Sack",
"20.000-Sterni-Sack",
"21.000-Sterni-Sack",
"22.000-Sterni-Sack",
"23.000-Sterni-Sack",
"24.000-Sterni-Sack",
"25.000-Sterni-Sack",
"26.000-Sterni-Sack",
"27.000-Sterni-Sack",
"28.000-Sterni-Sack",
"29.000-Sterni-Sack",
"30.000-Sterni-Sack",
"31.000-Sterni-Sack",
"32.000-Sterni-Sack",
"33.000-Sterni-Sack",
"34.000-Sterni-Sack",
"35.000-Sterni-Sack",
"36.000-Sterni-Sack",
"37.000-Sterni-Sack",
"38.000-Sterni-Sack",
"39.000-Sterni-Sack",
"40.000-Sterni-Sack",
"41.000-Sterni-Sack",
"42.000-Sterni-Sack",
"43.000-Sterni-Sack",
"44.000-Sterni-Sack",
"45.000-Sterni-Sack",
"46.000-Sterni-Sack",
"47.000-Sterni-Sack",
"48.000-Sterni-Sack",
"49.000-Sterni-Sack",
"50.000-Sterni-Sack",
"51.000-Sterni-Sack",
"52.000-Sterni-Sack",
"53.000-Sterni-Sack",
"54.000-Sterni-Sack",
"55.000-Sterni-Sack",
"56.000-Sterni-Sack",
"57.000-Sterni-Sack",
"58.000-Sterni-Sack",
"59.000-Sterni-Sack",
"60.000-Sterni-Sack",
"61.000-Sterni-Sack",
"62.000-Sterni-Sack",
"63.000-Sterni-Sack",
"64.000-Sterni-Sack",
"65.000-Sterni-Sack",
"66.000-Sterni-Sack",
"67.000-Sterni-Sack",
"68.000-Sterni-Sack",
"69.000-Sterni-Sack",
"70.000-Sterni-Sack",
"71.000-Sterni-Sack",
"72.000-Sterni-Sack",
"73.000-Sterni-Sack",
"74.000-Sterni-Sack",
"75.000-Sterni-Sack",
"76.000-Sterni-Sack",
"77.000-Sterni-Sack",
"78.000-Sterni-Sack",
"79.000-Sterni-Sack",
"80.000-Sterni-Sack",
"81.000-Sterni-Sack",
"82.000-Sterni-Sack",
"83.000-Sterni-Sack",
"84.000-Sterni-Sack",
"85.000-Sterni-Sack",
"86.000-Sterni-Sack",
"87.000-Sterni-Sack",
"88.000-Sterni-Sack",
"89.000-Sterni-Sack",
"90.000-Sterni-Sack",
"91.000-Sterni-Sack",
"92.000-Sterni-Sack",
"93.000-Sterni-Sack",
"94.000-Sterni-Sack",
"95.000-Sterni-Sack",
"96.000-Sterni-Sack",
"97.000-Sterni-Sack",
"98.000-Sterni-Sack",
"99.000-Sterni-Sack",
"Erd-Glücksei",
"Baum-Glücksei",
"Fels-Glücksei",
"Luft-Glücksei",
"Gewinn-Coupon",
"Hauptgewinn-Coupon"
],

//Mushroomized furniture
[
"Waldtapete (mushroomized)",
"Waldteppich (mushroomized)",
"Pilzbett (mushroomized)",
"Pilzkommode (mushroomized)",
"Pilzschrank (mushroomized)",
"Pilzstuhl (mushroomized)",
"Pilzhocker (mushroomized)",
"Pilztisch (mushroomized)",
"Pilztischchen (mushroomized)",
"Pilzlampe (mushroomized)",
"Pilzwandleuchte (mushroomized)",
"Pilzfernseher (mushroomized)",
"Pilzgarderobe (mushroomized)"
],

//Songs
[
"K.K. Choral",
"K.K. Marsch",
"K.K. Walzer",
,
,
,
"K.K. Etüde",
"K.K. Schlaflied",
"K.K. Arie",
,
,
,
,
,
,
,
,
"K.K. Jahrmarkt",
"K.K. Südseetraum",
"K.K. Glückspilz",
"K.K. Kondor",
"K.K. Steppensong",
"Super-K.K.",
"K.K. Orientsong",
,
,
,
"K.K. Rocksong",
,
,
"K. Funk",
,
"K.K. mit Gefühl",
,
,
"K.K. Liebeslied",
"K.K. D & B",
,
,
"Ganz allein",
,
,
"K.K. Ballade",
"K.K. Freundelied",
"K.K. Klagelied",
"Go K.K. Rider!",
"K.K. Trauerlied",
,
"Herr K.K.",
"K.K. Kaffeeblues",
,
"K.K. Combo",
,
"Ich liebe dich",
"Vorgestern",
"Mein Zuhause",
"Waldlichtung",
"Am Rande",
"Nachdenklich",
,
,
,
"Berglied",
"Seefahrerlied 2001",
"Neapolitaner",
"Bergsteigung",
,
,
"K.K. Parade 2",
,
"Alter Kuchen",
"Frühlingsblüten",
"Ich wandere",
,
"K.K. Sonate",
"Schlummerlied",
"Spaziergang",
"Die Insel der Tiere",
"Minimal Music",
"K.K. Filmmusik",
"K.K. Maharadscha",
"K.K. Basar",
,
,
"K.K. Melodie",
,
"K.K. Sonnenuntergang",
"K.K. Pop",
"K.K. Synthiepop",
,
"Geburtstagslied"
],

//Songs (2)
,

//Songs (seashell player)
,

//Paper
[
"Falterpapier",
"Luftpostpapier",
"Neujahrskarte",
"Spitzenpapier",
"Wölkchenpapier",
"Tulpenpapier",
"Schneepapier",
"Ahornpapier",
"Linienpapier",
"Ringheftpapier",
"Blümchenpapier",
"Punktepapier",
"Uraltpapier",
"Bändchenpapier",
"Kristallpapier",
"Rankenpapier",
"Formalpapier",
"Schneemannpapier",
"Pokerpapier",
"Leopardenpapier",
"Kuhpapier",
"Tarnpapier",
"Hamburgerpapier",
"Klavierpapier",
"Nook-Papier",
"Feierpapier",
"Kleeblattpapier",
"Schwingenpapier",
"Herzchenpapier",
"Regenbogenpapier",
"Pharaopapier",
"Lotuspapier",
"Kachelpapier",
"Mosaikpapier",
"Eleganzpapier",
"Skyline-Papier",
"Fernost-Papier",
"Ozeanpapier",
"Zahnradpapier",
"Feuerwerkpapier",
"Rosenpapier",
"Pilzpapier",
"Sternenpapier",
"Notenpapier",
"Schwimmbadpapier",
"SMB3-Papier",
"Himmelpapier",
"Waldpapier",
"Bläschenpapier",
"Blütenpapier",
"Kiltpapier",
"Holzfällerpapier",
"Zitruspapier",
"Kraterpapier",
"Juwelenpapier",
"Geometriepapier",
"Präriepapier",
"Nachtsternpapier",
"Tapetenpapier",
"Goldfischpapier",
"Halloweenpapier",
"Galeriepapier",
"Museumspapier",
"Postamtspapier",
"Wohnmobilplatzpapier",
"ImmoNook-Papier",
"Nintendo-Papier",
"Melodiekarte"
],

//Turnips
[
"10 Rüben",
"20 Rüben",
"30 Rüben",
"40 Rüben",
"50 Rüben",
"60 Rüben",
"70 Rüben",
"80 Rüben",
"90 Rüben",
"100 Rüben",
"Rüben (verdorben)"
],

//Bugs
[
"Kohlweißling",
"Zitronenfalter",
"Schwalbenschwanz",
"Pfaufalter",
"Monarchfalter",
"Himmelsfalter",
"Agrias-Falter",
"Rajah Brooke",
"Vogelflügler",
"Motte",
"Seidenspinner",
"Honigbiene",
"Biene",
"Nasenschrecke",
"Wanderschrecke",
"Heuschrecke",
"Gottesanbeterin",
"Orchideenmantis",
"Erdzikade",
"Mannazikade",
"Riesenzikade",
"Bergzikade",
"Abendzikade",
"Zikadenlarvenhaut",
"Laternenträger",
"Feuerlibelle",
"Königslibelle",
"Quelljungfer",
"Riesenlibelle",
"Ameise",
"Wasserläufer",
"Schwimmkäfer",
"Stinkwanze",
"Schnecke",
"Grille",
"Singgrille",
"Grashüpfer",
"Maulwurfsgrille",
"Blattschrecke",
"Stabschrecke",
"Sackträger",
"Marienkäfer",
"Laufkäfer",
"Fichtenbock",
"Sandlaufkäfer",
"Mistkäfer",
"Strandassel",
"Einsiedlerkrebs",
"Leuchtkäfer",
"Smaragdkäfer",
"Skarabäus",
"Prachtkäfer",
"Hirschkäfer",
"Sägezahn-Hirschkäfer",
"Riesen-Hirschkäfer",
"Pracht-Hirschkäfer",
"Cyclommatus",
"Lamprima aurata",
"Nashornkäfer",
"Atlaskäfer",
"Elefantenkäfer",
"Herkuleskäfer",
"Goliathkäfer",
"Floh",
"Kugelassel",
"Mücke",
"Fliege",
"Spinnenläufer",
"Hundertfüßer",
"Spinne",
"Tarantel",
"Skorpion",
"Schneeflocke",
"Rubinfeder",
"Azurfeder",
"Smaragdfeder",
"Bernsteinfeder",
"Lilafeder",
"Schneefeder",
"Flamingofeder",
"Regenbogenfeder",
"Glücksarmband"
],

//Fish
[
"Bitterling",
"Döbel",
"Karausche",
"Hasel",
"Barbe",
"Karpfen",
"Koi-Karpfen",
"Goldfisch",
"Teleskopauge",
"Killifisch",
"Flusskrebs",
"Weichschildkröte",
"Kaulquappe",
"Frosch",
"Flussgrundel",
"Bachschmerle",
"Katzenwels",
"Aal",
"Schlangenkopf",
"Sonnenbarsch",
"Flussbarsch",
"Barsch",
"Hecht",
"Stint",
"Ayu-Fisch",
"Masulachs",
"Saibling",
"Regenbogenforelle",
"Huchen",
"Lachs",
"Königslachs",
"Wollhandkrabbe",
"Guppy",
"Doktorfisch",
"Skalar",
"Neonsalmler",
"Piranha",
"Arowana",
"Goldmakrele",
"Knochenhecht",
"Arapaima",
"Flösselhecht",
"See-Engel",
"Seepferdchen",
"Anemonenfisch",
"Paletten-Doktorfisch",
"Falterfisch",
"Napoleonfisch",
"Rotfeuerfisch",
"Kugelfisch",
"Igelfisch",
"Makrele",
"Zebrabuntbarsch",
"Seebarsch",
"Kaiserschnapper",
"Kliesche",
"Flunder",
"Kalmar",
"Muräne",
"Nasenmuräne",
"Anglerfisch",
"Thunfisch",
"Marlin",
"Pferdemakrele",
"Rochen",
"Mondfisch",
"Hammerhai",
"Hai",
"Sägehai",
"Walhai",
"Riemenfisch",
"Quastenflosser",
"Dose",
"Stiefel",
"Reifen",
"Wasser-Glücksei"
],

//Marine creatures
[
"Wakame-Alge",
"Kriechspross-Alge",
"Seeigel",
"Seepocke",
"Auster",
"Turbanschnecke",
"Seeohr",
"Ohrschnecke",
"Venusmuschel",
"Perlmuschel",
"Kammmuschel",
"Seeanemone",
"Seestern",
"Seegurke",
"Nacktkiemer",
"Meerstrudelwurm",
"Fangschreckenkrebs",
"Eismeergarnele",
"Kuruma-Garnele",
"Languste",
"Hummer",
"Schneekrabbe",
"Kegani-Krabbe",
"Königskrabbe",
"Riesenkrabbe",
"Oktopus",
"Röhrenaal",
"Perlboot",
"Pfeilschwanzkrebs",
"Riesenassel",
"Tiefsee-Glücksei"
],

//Wallpaper
[
"Orient-Tapete",
"Herzchentapete",
"Klassiktapete",
"Western-Tapete",
"Korbtapete",
"Azurtapete",
"Schachtapete",
"Royaltapete",
"Smaragdtapete",
"Blockhauswand",
"Kindertapete",
"Robo-Tapete",
"Schneemanntapete",
"Waldtapete",
"Karnevalstapete",
"Eiertapete",
"Kürbistapete",
"Herbsttapete",
"Festtagstapete",
"Prachttapete",
"Graziatapete",
"Süßtapete",
"Luxustapete",
"Wüstenausblick",
"Sternenhimmel",
"Plane",
"Publikum",
"Gartenzaun",
"Spieltapete",
"Seeblicktapete",
"Laborwand",
"Schulraumwand",
"Badwand",
"Pastelltapete",
"Salontapete",
"Modetapete",
"70er-Tapete",
"Irrsinnstapete",
"Backgammonwand",
"Mosaikwand",
"Bortentapete",
"Gipswand",
"Omatapete",
"Schmucktapete",
"Zitrustapete",
"Rosentapete",
"Backsteinwand",
"Shoji-Wand",
"Goldtür-Tapete",
"Teezimmerwand",
"Shoji-Wand (modern)",
"Gartentapete",
"Ziegelmauer",
"Steinwand",
"Betonwand",
"Kellerwand",
"Wellblechwand",
"Holzverkleidung",
"Ornamenttapete",
"Verandatapete",
"Dämmwand",
"Herrenhauswand",
"Fenstertapete",
"Gitterwand",
"Pavillonwand",
"Wandverkleidung",
"Samuraitapete",
"Bogenfensterwand",
"Bambuswand",
"Efeumauer",
"Antikwand",
"Feudaltapete",
"Nomadentapete",
"Industriewand",
"Bücherwand",
"3D-Tapete",
"Alpenblick",
"Tropenausblick",
"Wüstenweitblick",
"Sandplatzmauer",
"Baumtapete",
"Himmeltapete",
"Großstadttapete",
"Schmutzwand",
"Normaltapete",
"Bröckelwand",
"Pilztapete",
"Gruseltapete",
"Pünktchentapete",
"Ruinentapete",
"Sportwand",
"Goldtapete",
"Dschungeltapete",
"Meerestapete",
"Fossilientapete",
"Farbkleckstapete",
"Aquatapete",
"Eistapete",
"Schlampertapete",
"Raumschifftapete",
"Rokoko-Tapete",
"Schmetterlingstapete",
"Buntholzwand",
"Nixentapete",
"Designertapete",
"Kartentapete",
"Streifentapete",
"Nordtapete",
"Minimaltapete",
"Skipistentapete",
"Ballontapete",
"Astrotapete",
"Blumentapete",
"Käsetapete",
"Tonkachelwand",
"Labyrinthtapete",
"Herbstlaubtapete",
"Palasttapete",
"Partytapete",
"Pfötchentapete",
"Gipfeltapete",
"Wolkenkratzertapete",
"Ausstellungstapete",
"Museumstapete",
"Notizbuchwand",
"Fundgrubentapete",
"Mini-Supermarktwand",
"Supermarkttapete",
"Baumarkttapete",
"Kaufhaustapete",
"Grazia-Ladentapete",
"Grazia-Ladentapete (2)",
"Grazia-Ladentapete (3)",
"Minimalwand",
"Dielentapete",
"Fliesentapete",
"Stadiontapete",
"Zugabteiltapete",
"Wartezimmertapete",
"Eisengittertapete",
"Ladentapete",
"Weißziegeltapete",
"Bambuswaldtapete",
"Savannentapete",
"Vulkantapete",
"Ozeantapete",
"Hello-Kitty-Tapete",
"My-Melody-Tapete",
"Pompompurin-Tapete",
"Kiki-&-Lala-Tapete",
"Cinnamoroll-Tapete",
"Teich-Wand",
"Hyrule-Tapete",
"Tintenkleckstapete",
"Inkopolis-Tapete",
"Puzzleopolis-Tapete",
"Fueki-Wand",
,
"Pünktchenbandtapete"
],

//Carpets
[
"Orient-Teppich",
"Herzchenteppich",
"Klassikteppich",
"Western-Teppich",
"Korbteppich",
"Azurteppich",
"Schachteppich",
"Royalteppich",
"Smaragdteppich",
"Blockhausteppich",
"Kinderteppich",
"Robo-Teppich",
"Schneemannteppich",
"Waldteppich",
"Karnevalsboden",
"Eierteppich",
"Kürbisteppich",
"Herbstteppich",
"Festtagsteppich",
"Prachtteppich",
"Graziateppich",
"Süßteppich",
"Luxusteppich",
"Wüstengrund",
"Mondlandschaft",
"Straßenbauboden",
"Boxmatte",
"Wiesenteppich",
"Spielteppich",
"Schiffsdeck",
"Laborboden",
"Schulraumparkett",
"Badkachelboden",
"Pastellteppich",
"Karokachelboden",
"Keramikfliesenboden",
"Imbisskachelboden",
"70er-Kachelboden",
"Tonkachelboden",
"Mosaikboden",
"Schachbrettboden",
"Musterboden",
"Palastkachelboden",
"Samuraiboden",
"Küchenfliesenboden",
"Steinboden",
"Kohleboden",
"Tatamiboden",
"Dielen-Tatamiboden",
"Moosteppich",
"Sandgarten",
"Schieferboden",
"Betonboden",
"Kellerboden",
"Parkettboden",
"Schmutzboden",
"Verandaboden",
"Dämmteppich",
"Linoleumboden",
"Perserteppich",
"Edelteppich",
"Schmuckteppich",
"Rosenteppich",
"Feudalteppich",
"Nomadenteppich",
"Tartanteppich",
"Kreisteppich",
"Zitrusteppich",
"Kuhfellteppich",
"Birkenboden",
"Dielenboden",
"Bambusboden",
"Eisenbelag",
"Flechtmatte",
"Antikboden",
"3D-Teppich",
"Alpengrund",
"Tropengrund",
"Saharagrund",
"Sandplatz",
"Musterweg",
"Wolkenteppich",
"Normalboden",
"Bröckelboden",
"Bruchsteinboden",
"Gruselboden",
"Ruinenboden",
"Sportboden",
"Goldboden",
"Hüpfkästchenboden",
"Wildblumenboden",
"Dschungelboden",
"Meeresboden",
"Fossilienboden",
"Farbklecksboden",
"Marienkäferteppich",
"Eisteppich",
"Schlamperboden",
"Raumschiffboden",
"Buntholzboden",
"Nixenboden",
"Designerteppich",
"Kartenboden",
"Streifenboden",
"Minimalboden",
"Skipistenboden",
"Ballonboden",
"Astroboden",
"Blumenteppich",
"Aquaboden",
"Käseboden",
"Labyrinthboden",
"Herbstlaubboden",
"Rokoko-Boden",
"Nordteppich",
"Notizbuchteppich",
"Pünktchenteppich",
"Ausstellungsboden",
"Museumsboden",
"Fundgrubenboden",
"Mini-Supermarktboden",
"Supermarktboden",
"Baumarktboden",
"Kaufhausboden",
"Grazia-Ladenboden",
"Grazia-Ladenboden (2)",
"Grazia-Ladenboden (3)",
"Orient-Boden",
"Gelbboden",
"Holzdielenboden",
"Herbstboden",
"Eichenboden",
"Steinfliesenboden",
"Laminat",
"Weiß-Kachelboden",
"Paneelboden",
"Kopfsteinpflaster",
"Sandsteinboden",
"Terrakotta-Boden",
"Binsenboden",
"Grätenboden",
"Schulgangboden",
"Wasseroberfläche",
"Gehweg",
"Lobby-Boden",
"Feld",
"Weltraumboden",
"Vulkanboden",
"Beizboden",
"Dunkelfliesenboden",
"Quadratboden",
"Sandboden",
"Matschboden",
"Rustikalboden",
"Prachtboden",
"Hello-Kitty-Boden",
"My-Melody-Boden",
"Pompompurin-Boden",
"Kiki-&-Lala-Boden",
"Cinnamoroll-Boden",
"Teich-Boden",
"Zelda-Boden",
"Tintenklecksboden",
"Inkopolis-Boden",
"Puzzleopolis-Boden",
"Fueki-Boden",
"Museumsfoyer-Boden",
"Planetariumsteppich"
],

//Shirts
[
"1er-Shirt",
"2er-Shirt",
"3er-Shirt",
"4er-Shirt",
"5er-Shirt",
"6er-Shirt",
"7er-Shirt",
"8er-Shirt",
"9er-Shirt",
"Tatzenshirt",
"Blümchenshirt",
"Seerosenshirt",
"Kirschenshirt",
"Schädelshirt",
"Pfeilshirt",
"Blitz-Shirt",
"MVP-Shirt",
"BB-Shirt",
"Fischgrät-Shirt",
"Quak-Shirt",
"Teddy-Shirt",
"Hasenshirt",
"Hasenpulli",
"Elefantenshirt",
"Shirt „Pik“",
"Shirt „Karo“",
"Shirt „Kreuz“",
"Shirt „Herz“",
"Nachtshirt",
"08/15-Shirt",
"A-Shirt",
"Nr.-1-Pulli",
"Nr.-2-Pulli",
"Nr.-3-Pulli",
"Nr.-4-Pulli",
"Nr.-5-Pulli",
"Nr.-23-Pulli",
"Nr.-67-Pulli",
"Mario-Shirt",
"Luigi-Shirt",
"Wolkenshirt",
"Sorbet-Shirt",
"Aurora-Shirt",
"Nebelshirt",
"Sonnenshirt",
"Tiefseeshirt",
"Pfirsichshirt",
"Iris-Shirt",
"Bonbonshirt",
"Batikshirt",
"Ökoshirt",
"Festivalshirt",
"Meershirt",
"Naturshirt",
"Quadratshirt",
"Caféshirt",
"Schachshirt",
"Blauweiß-Shirt",
"Rotweiß-Shirt",
"Pepita-Shirt",
"Schokoshirt",
"Rugby-Shirt",
"Apfelshirt",
"Aprikosenshirt",
"Lutschershirt",
"Beatnik-Shirt",
"Ferienshirt",
"Matrosenshirt",
"Matrosenpulli",
"3-Farben-Shirt",
"Gefängnisshirt",
"Rennbahnshirt",
"Kanarienshirt",
"Herbstshirt",
"Sittichshirt",
"Alpaka-Shirt",
"Mohair-Shirt",
"Gittershirt",
"Käfigshirt",
"Wohlfühlshirt",
"Spielshirt",
"Pilzshirt",
"Ballonshirt",
"Konfettishirt",
"Pünktchenshirt",
"Funky-Shirt",
"Kaugummishirt",
"Eiscreme-Shirt",
"Tüpfelshirt",
"Gärtnershirt",
"Ruderershirt",
"Lieblingsshirt",
"Streifenshirt",
"Jockeyshirt",
"Pastellshirt",
"Rallye-Shirt",
"Fußballshirt",
"3D-Shirt",
"Friseurshirt",
"Aktiv-Shirt",
"Angora-Shirt",
"Mint-Karo-Shirt",
"Rosa-Karo-Shirt",
"Picknickshirt",
"Gelb-Karo-Shirt",
"Künstlershirt",
"Cool-Shirt",
"Schweinchenshirt",
"Waffelshirt",
"Tartanshirt",
"Tartanpulli",
"Rot-Argyle-Pulli",
"Rot-Argyle-Shirt",
"Blau-Argyle-Pulli",
"Blau-Argyle-Shirt",
"Rosa-Argyle-Pulli",
"Rosa-Argyle-Shirt",
"Türkis-Argyle-Pulli",
"Türkis-Argyle-Shirt",
"Musterpulli",
"Eispulli",
"Wellenpulli",
"Winterpulli",
"Folklorepulli",
"Argyle-Pulli",
"Ethnopulli",
"Wollpulli",
"Schurwolljacke",
"Polarpulli",
"Frühlingspulli",
"Nordik-Pulli",
"Rentierpulli",
"Baumpulli",
"Minzshirt",
"Farnshirt",
"Tannenshirt",
"Blättershirt",
"Strohpulli",
"Rasenshirt",
"Schneepulli",
"Herzchenshirt",
"Wassershirt",
"Rankenshirt",
"Korallenshirt",
"Schneckenshirt",
"Feuershirt",
"Linienshirt",
"Graziatop",
"Kreis-Top",
"Optik-Pulli",
"Sternchenshirt",
"Buntstern-Shirt",
"Sternbild-Shirt",
"Amethyst-Top",
"Funkelshirt",
"Würfeltop",
"Kindershirt",
"Edelshirt",
"Kreuzpulli",
"Tipptopp-Shirt",
"Zackenshirt",
"Leinenshirt",
"Rautenshirt",
"Malershirt",
"Dschungelshirt",
"Arktik-Shirt",
"Wüstenshirt",
"Platinentop",
"EKG-Top",
"Zebrashirt",
"Tigershirt",
"Kuhshirt",
"Leopardenshirt",
"Giraffenshirt",
"Käfertop",
"Spinnwebenshirt",
"Raupentop",
"Wabenpulli",
"Mandarinenshirt",
"Kiwishirt",
"Melonenshirt",
"Erdbeershirt",
"Traubenshirt",
"Papayashirt",
"Himbeertop",
"Puddingtop",
"Hotdog-Top",
"Sandwich-Top",
"Nudelshirt",
"Pfui-Top",
"Drachenshirt",
"Östlich-Shirt",
"Seidenshirt",
"Satinshirt",
"Stickshirt",
"Tropik-Shirt",
"Korsettbluse",
"Adelspulli",
"Inselshirt",
"Aloha-Shirt",
"Western-Hemd",
"Königswams",
"Feuerwehrjacke",
"Arztkittel",
"Knochenpulli",
"Zipp-Jacke",
"Mumienpulli",
"Militärjacke",
"Marineshirt",
"Reggae-Shirt",
"Kameljacke",
"Portierjacke",
"Smokingjackett",
"Safarishirt",
"WM-Shirt",
"Erdbeerpulli",
"Blaubeerpulli",
"Edelmann-Hemd",
"Paillettenpulli",
"Bänderkittel",
"Wrestlingtrikot",
"Polizeishirt",
"Bärenpulli",
"Froschshirt",
"Käpten-Pulli",
"Rotseidenpulli",
"Rennfahrerjacke",
"Arbeitsjacke",
"Blechshirt",
"Schuppenpanzerhemd",
"Silberrüstungshemd",
"Goldrüstungshemd",
"Kombishirt",
"Trainingsjacke",
"Baseballtrikot",
"Fitness-Shirt",
"Joggingshirt",
"Astronautenjacke",
"Steinzeittop",
"Kung-Fu-Hemd",
"Kunstlederweste",
"Radlerjacke",
"Radlershirt",
"Kochshirt",
"Orient-Pulli",
"Folklorekittel",
"Rotheldenpulli",
"Blauheldenpulli",
"Grünheldenpulli",
"Samurairüstung",
"Flickenpulli",
"Heldenjacke",
"Varia-Jacke",
"Rotsaumshirt",
"Grauparka",
"Angelweste",
"Pilotenjacke",
"Ninjapulli",
"Detektivjacke",
"Weihnachtsmannjacke",
"Kükenshirt",
"Schuppenshirt",
"Jimbei-Shirt",
"Motiv-Shirt",
"Raglan-Pulli",
"Fernost-Jacke",
"Collegejacke „C“",
"Collegejacke „K“",
"Collegejacke „B“",
"Tigerjacke",
"Drachenjacke",
"Holzfällerhemd",
"Holzhackerhemd",
"Flanellhemd",
"Knospentop",
"Gartentop",
"Blau-Spitzentop",
"Pink-Spitzentop",
"Lockerweste",
"Bürohemd",
"Daunenweste",
"Rowdy-Schuljacke",
"Malkittel",
"Streber-Schuljacke",
"Rundkragenpulli",
"Bluejeansjacke",
"Ausgehshirt",
"Jeansweste",
"Sportshirt",
"Grün-Blazer",
"Bleichjeansjacke",
"Dompteursjacke",
"Yachtjackett",
"Schwarzjeansjacke",
"Basketballtrikot",
"Matadorjacke",
"Pink-Parka",
"Jockeypulli",
"Läuferjacke",
"Pullunder mit Hemd",
"Weste mit Hemd",
"Aufwärmjacke",
"Landhaus-Blazer",
"Verkäuferhemd",
"Waldlaufjacke",
"Zirkusdirektorjacke",
"Staffellauf-Top",
"Winterstrickjacke",
"Windjacke",
"Regenjacke",
"Primelshirt",
"Frotteeshirt",
"Blumenbeetshirt",
"Kunstseidenshirt",
"Blütenshirt",
"Romantik-Shirt",
"Nachtblumenshirt",
"Tulpenshirt",
"80er-Pulli",
"Lotusshirt",
"Rosenshirt",
"Cheerleader-Pulli",
"Narrenpulli",
"70er-Pulli",
"Disco-Pulli",
"Karnevals-Top",
"Mädchen-Pyjamajacke",
"Jungen-Pyjamajacke",
"Schleifentop",
"Stewardessjacke",
"Kellnerweste",
"Dufflecoat",
"Felljacke",
"Buntpunkt-Jacke",
"Strickweste mit Hemd",
"Sonnenblumenshirt",
"Grünstreifentop",
"Logo-Top",
"Umhängepullover",
"Kirschblütenshirt",
"AdsH-Shirt",
"AdsH-Jacke",
"Samselt-Jacke",
"Supermarktkittel",
"70er-Shirt",
"80er-Shirt",
"Raglan-Shirt",
"MVP-Pulli",
"Aktiv-Pulli",
"Rotweiß-Pulli",
"Rugby-Pulli",
"Malerpulli",
"EKG-Pulli",
"Pilzpulli",
"Marinepulli",
"Quak-Pulli",
"Gitterpulli",
"Kung-Fu-Jacke",
"Schokopulli",
"Cool-Pulli",
"Farnpulli",
"Arktik-Pulli",
"Blätterpulli",
"Elefantenpulli",
"Käfigpulli",
"Gefängnispulli",
"Pepita-Pulli",
"Schimmelpulli",
"Waffelpulli",
"Streifenpulli",
"Blauweiß-Pulli",
"Rosa-Karo-Pulli",
"Mohair-Pulli",
"Schweinchenpulli",
"Spielpulli",
"Ballonpulli",
"Gelb-Karo-Pulli",
"Lieblingspulli",
"Wohlfühlpulli",
"Funkelpulli",
"Pünktchenpulli",
"Gärtnerpulli",
"Konfettipulli",
"Aprikosenpulli",
"Kanarienpulli",
"Amethyst-Pulli",
"WM-Pulli",
"Lutscherpulli",
"Ferienpulli",
"Picknickpulli",
"Schädelpulli",
"Feuerpulli",
"3D-Pulli",
"Apfelpulli",
"3-Farben-Pulli",
"Alpaka-Pulli",
"Wüstenpulli",
"Dschungelpulli",
"Beatnik-Pulli",
"Rudererpulli",
"Herbstpulli",
"Sittichpulli",
"Mint-Karo-Pulli",
"Teddy-Pulli",
"Künstlerpulli",
"Angora-Pulli",
"Papayatop",
"Melonentop",
"Zipp-Top",
"Nebeltop",
"Ökotop",
"Narrentop",
"Traubentop",
"Bonbontop",
"Tüpfeltop",
"Erdbeertop",
"Pfirsichtop",
"Reggae-Top",
"Blau-Argyle-Top",
"Sternchentop",
"Festivaltop",
"Flammentop",
"Optik-Top",
"Zackentop",
"Rallye-Top",
"Wassertop",
"Tiefseetop",
"Paillettentop",
"Korallentop",
"Rosa-Argyle-Top",
"Funky-Top",
"Schneckentop",
"Sorbet-Top",
"Tropik-Top",
"Sonnentop",
"Mandarinentop",
"Meertop",
"Giraffentop",
"Batiktop",
"Zebratop",
"Tigertop",
"Kiwitop",
"Naturtop",
"Cheerleader-Top",
"Aurora-Top",
"Beatnik-Top",
"Eiscreme-Top",
"Iris-Top",
"Leopardentop",
"Kuhtop",
"Orient-Top",
"Türkis-Argyle-Top",
"AdsH-Neulings-Jacke",
"AdsH-Neulings-Blazer",
"Fashion-Jacke",
"Polohemd",
"Büroblazer",
"Krankenhauskittel",
"Imponierhemd",
"Sushikochjacke",
"Komikerjacke",
"Kunststoffschürze",
"Dienstmädchenschürze",
"Felyne-Outfit",
"AdsH-Blazer",
"Glücks-Outfit",
"Link-Outfit",
"Ganondorf-Outfit",
"Ganon-Outfit",
"Medolie-Outfit",
"Epona-Outfit",
"Wolf-Link-Outfit",
"Neuhelden-Outfit",
"Schwarzanker-Shirt",
"Cinnamoroll-Jacke",
"Teich-Pulli",
"Hello-Kitty-Outfit",
"My-Melody-Outfit",
"Kiki-&-Lala-Outfit",
"Pompompurin-Outfit",
"Cinnamoroll-Outfit",
"Teich-Outfit",
"AdsH-Regenjacke",
"Aioli-Pulli",
"Limone-Pulli",
"Aioli-Style-Top",
"Übermut-Pulli",
"Rathaus-Sommeroutfit",
"Rathaus-Winteroutfit",
"Jacquard-Outfit",
,
"Shiek-Outfit"
],

//Dresses
[
"Festtagskleid",
"Strandkleid",
"Tüpfelkleid",
"Schokokleid",
"Adrett-Kleid",
"Jeanskleid",
"Prinzessinnenkleid",
"Sonntagskleid",
"Schulkleid",
"Tanzkleid",
"Landpartiekleid",
"Eiscreme-Kleid",
"Küchenkleid",
"Flanellkleid",
"Tunikakleid",
"Falter-Trägerkleid",
"Kontrastkleid",
"Piratenmantel",
"Heldinnenkleid",
"Fleece-Kleid",
"En-Vogue-Kleid",
"Ausflugskleid",
"Primel-Trägerkleid",
"Frottee-Trägerkleid",
"Velours-Trägerkleid",
"Blumenbeetkleid",
"Blüten-Trägerkleid",
"Nachtblumenkleid",
"Rosen-Trägerkleid",
"Tulpen-Trägerkleid",
"Lotus-Trägerkleid",
"Retro-Kleid",
"Glamour-Kleid",
"Flammenkleid",
"Schimmelkleid",
"Wiesenkleid",
"Schleifenkleid",
"Schnürkleid",
"Clownskleid",
"Smaragdkleid",
"Maikleid",
"Lodenkleid",
"Jodelkleid",
"Reitkleid",
"Hexenumhang",
"Uni-Robe",
"Himmelskleid",
"Alpenkleid",
"Kimono",
"Trachtenkleid",
"Toga",
"Brautkleid",
"Pastellkleid",
"Rüschenkleid",
"Märchenkleid",
"Flamencokleid",
"Oasen-Trägerkleid",
"Poncho",
"Hasenkleid",
"Katzenkleid",
"Lederkleid",
"Purpurkleid",
"Freizeitkleid",
"Magdkleid",
"Trenchcoat",
"Pharao-Robe",
"Bademantel",
"Fliegenpilzkleid",
"Flickenkleid",
"Samtkleid",
"Wohlfühlkleid",
"Pepita-Kleid",
"Schwesternkittel",
"Stickkleid",
"Karnevalskleid",
"Schottenkarokleid",
"Strickkleid",
"Hemdkleid",
"Gute-Laune-Kleid",
"Regenmantel",
"Püppchenkleid",
"Baumschmuck-Kleid",
"Ballett-Trägerkleid",
"Klassik-Kleid",
"Pfeilkleid",
"Mohair-Kleid",
"Alpaka-Kleid",
"Kaugummikleid",
"Hanbok-Kleid",
"Frühlings-Kimono",
"Steinzeitkleid",
"Buntstern-Kleid",
"Sternchenkleid",
"Pastell-Trägerkleid",
"Katzen-Trägerkleid",
"Braut-Trägerkleid",
"Hasen-Trägerkleid",
"Herzchenkleid",
"Tänzerinnenkleid",
"Pianistinnenkostüm",
"Zelda-Kleid",
"Limone-Kleid",
"Hello-Kitty-Kleid",
"My-Melody-Kleid",
"Kiki-&-Lala-Kleid",
"Pompompurin-Kleid",
"Blumenelfenkleid"
],

//Wet suits
[
"Leih-Taucheranzug",
"Anker-Taucheranzug",
"Palmen-Taucheranzug",
"Ringel-Taucheranzug",
"Hobby-Taucheranzug",
"Sport-Taucheranzug",
"Einsatz-Taucheranzug",
"Kronen-Taucheranzug",
"Nacht-Taucheranzug"
],

//Trousers
[
"Dschungel-Sporthose",
"Dschungelhose",
"Cargohose",
"Pepita-Hose",
"Schokohose",
"Flickenhose",
"Weihnachtsmannhose",
"Heldenhose",
"Leopardenhose",
"Leopardenrock",
"Bluejeansrock",
"Konfettirock",
"Kuhhose",
"Giraffenhose",
"Tigerhose",
"Zebrahose",
"Silberrüstungshose",
"Goldrüstungshose",
"Matadorhose",
"Baseballhose",
"Knochenhose",
"Arktik-Hose",
"Wüstenhose",
"Steinzeithose",
"Blauboxerhose",
"Rotboxerhose",
"Cheerleader-Rock",
"Satinrock",
"Seidenrock",
"Rotseidenhose",
"Bärenhose",
"Froschhose",
"Käpten-Hose",
"Sofahose",
"Western-Hose",
"Funky-Rock",
"Flammenhose",
"Grün-Karo-Hose",
"Drachenhose",
"Safarihose",
"Feuerwehrhose",
"Spielrock",
"Rosa-Karo-Rock",
"Braun-Karo-Hose",
"Regenbogenhose",
"Mint-Karo-Rock",
"Blaupünktchenhose",
"Korsettrock",
"Gitterrock",
"Spielplatzhose",
"Käfigrock",
"Jogginghose",
"Sporthose",
"Fitnesshose",
"Blauheldenhose",
"Grünheldenhose",
"Rotheldenhose",
"Läuferhose",
"Waldlaufhose",
"Trainingshose",
"Narrenhose",
"Kung-Fu-Hose",
"Kunstlederhose",
"Militärhose",
"Mumienhose",
"Varia-Hose",
"Ninjahose",
"Orient-Hose",
"Ballonrock",
"Rennfahrerhose",
"Spitzenrock",
"Marinerock",
"Samuraihose",
"Jimbei-Hose",
"Astronautenhose",
"Umkrempelhose",
"Kilt",
"Aerobic-Hose",
"Khaki-Hose",
"Tartanrock",
"Zweifarbhose",
"Mohair-Rock",
"Alpaka-Rock",
"WM-Hose",
"Arbeitshose",
"Wrestlinghose",
"Aufwärmhose",
"Sprinterhose",
"Bundfaltenhose",
"Nachtblauhose",
"Bürohose",
"Yachthose",
"Rotringelhose",
"Bernsteinrock",
"Gute-Laune-Rock",
"Baströckchen",
"Schottenkarohose",
"Fliegenpilzrock",
"Stonewashed-Hose",
"Schwarzjeansrock",
"Bleichjeanshose",
"Grauringelhose",
"Schwarzjeanshose",
"Fetzenjeanshose",
"Türkis-Pünktchenrock",
"Braun-Argyle-Rock",
"Rosa-Argyle-Rock",
"Kontrast-Karo-Hose",
"Stonewashed-Rock",
"Aloha-Hose",
"Blauringelhose",
"Karnevalshose",
"Mädchen-Pyjamahose",
"Jungen-Pyjamahose",
"Basketballhose",
"Radlerhose",
"Cordhose",
"Königshose",
"Schuppenpanzerhose",
"Schwarzrock",
"Graurock",
"Nachtblaurock",
"Ganondorf-Hose",
"Teich-Hose",
"Aioli-Hose",
"Übermut-Hose",
"Shiek-Hose"
],

//Socks
[
"Modestrumpfhose",
"Braunringelsocke",
"Schwarzstrumpf",
"Herzchenstrumpfhose",
"Vielfarbstrumpfhose",
"Schwarzsöckchen",
"Sternstrumpfhose",
"Ringelstrumpfhose",
"Schwarzsocke",
"Graustrumpfhose",
"Nachtblausocke",
"Wanderstrumpf",
"Spitzensöckchen",
"Sportsocke",
"Argyle-Socke",
"Bündchensocke",
"Weinrotstrumpfhose",
"Sternchensocke",
"Baumwollgamasche",
"Tennissocke",
"Schwarzstrumpfhose",
"Braunstrumpfhose",
"Buntsocke",
"Karosocke",
"Braunsocke",
"Argyle-Strumpfhose",
"Grünringelsocke",
"Beinwärmer",
"Weißsöckchen",
"Fußballstutzen",
"Nylongamasche",
"Fliegenpilzsocke",
"Weißstrumpf",
"Grausocke",
"Blauringelstrumpf",
"Grünstrumpfhose",
"Aioli-Strumpfhose",
"Limone-Strumpfhose",
"Kiki-&-Lala-Socke",
"Teich-Socke"
],

//Shoes
[
"Leinenturnschuh",
"Lackschuh",
"Lila-Damenschuh",
"Fellstiefel",
"Basketballschuh",
"Weihnachtsmannschuh",
"Heldenstiefel",
"Schnürstiefel",
"Kunstlederschuh",
"Wanderschuh",
"Kimono-Sandale",
"Schneestiefel",
"Badesandale",
"Tüpfel-Damenschuh",
"Leopardenschuh",
"Tropensandale",
"Fliegenpilzstiefel",
"Gummistiefel",
"Fußballschuh",
"Holzpantoffel",
"Wildlederslipper",
"Gartenpantoffel",
"Zweifarb-Lederschuh",
"Grünsandale",
"Lederhalbschuh",
"Basketballstiefel",
"Blümchenslipper",
"Flickenschuh",
"Holzschuh",
"Kletterschuh",
"Gladiator-Sandale",
"Ninjasandale",
"Stahlkappenschuh",
"Superheldenstiefel",
"Regenstiefel",
"Zebra-Damenschuh",
"Ballettschuh",
"Cowboystiefel",
"Narrenschuh",
"Riemchenschuh",
"Silberrüstungsschuh",
"Goldrüstungsschuh",
"Blau-Wrestlingschuh",
"Rot-Wrestlingschuh",
"Varia-Schuh",
"Grün-Schnallenschuh",
"Lederslipper",
"Girlie-Schuh",
"Azur-Damenschuh",
"Vielfarbturnschuh",
"Segelschuh",
"Rotschuh",
"Sommersandale",
"Hauspantoffel",
"Gelb-Schnallenschuh",
"Pünktchenturnschuh",
"Kostüm-Damenschuh",
"Streifenturnschuh",
"Girlie-Turnschuh",
"Wildleder-Damenschuh",
"Gelbturnschuh",
"Orangeturnschuh",
"Aioli-Schuh",
"Limone-Schuh",
"Hello-Kitty-Schuh",
"My-Melody-Schuh",
"Kiki-&-Lala-Schuh",
"Pompompurin-Schuh",
"Cinnamoroll-Schuh",
"Teich-Schuh",
"Blumenelfenstiefel"
],

//Umbrellas
[
"3-Farben-Schirm",
"Flederschirm",
"Damenschirmchen",
"Blättchenschirm",
"Papierschirmchen",
"Bänderschirm",
"Rubinschirm",
"Aquaschirm",
"Bernsteinschirm",
"Smaragdschirm",
"Karoschirm",
"Melonenschirm",
"Minzschirm",
"Picknickschirm",
"Zitrusschirm",
"Punkteschirm",
"Eigelbschirm",
"Wolkenschirm",
"Blümchenschirm",
"Tatzenschirm",
"Margeritenschirm",
"Antikschirm",
"Sommerschirm",
"Strandschirm",
"Sonntagsschirm",
"Retroschirm",
"Leopardenschirm",
"Zebraschirm",
"Waldschirm",
"Feuerschirm",
"Tarnschirm",
"Spinnwebenschirm",
"Graziaschirm",
"Peach-Schirm",
"Geisterschirm",
"Ahornschirm",
"Puzzleopolis-Schirm"
],

//Hats
[
"Tankstellenkappe",
"Streifenkappe",
"Haikappe",
"Smaragdkappe",
"Sternkappe",
"1-Up-Kappe",
"Lilakappe",
"Blaumütze",
"Schneemütze",
"Smaragdmütze",
"Strickmütze",
"Wollmütze",
"Streifenmütze",
"Puschelmütze",
"Klecksmütze",
"Strohhut",
"Spionhut",
"Botenmütze",
"Barett",
"Dandymütze",
"Jägermütze",
"Detektivhut",
"Zylinder",
"Flauschmütze",
"Graziahut",
"Schmuckhut",
"Kopftuch",
"Tulpenhut",
"Bandana",
"Schwimmkappe",
"Zauberhut",
"Papierhut",
"Weihnachtsmannhut",
"Mario-Mütze",
"Luigi-Mütze",
"Wario-Mütze",
"Fahrradhelm",
"Kochmütze",
"Soldatenhelm",
"Abschlusshut",
"Baustellenhelm",
"Polizeimütze",
"Safarihut",
"Kapitänsmütze",
"Matrosenmütze",
"Seidenmütze",
"Western-Hut",
"Trachtenhaube",
"Sombrero",
"Gebirgshut",
"Wikingerhelm",
"Edelmann-Hut",
"Piratenhut",
"Narrenkappe",
"Hexenhut",
"Papayahut",
"Erdbeerhut",
"Kiwihut",
"Mandarinenhut",
"Melonenhut",
"Traubenhut",
"Rubinband",
"Azurband",
"Bernsteinband",
"Herzhaarnadel",
"Sternhaarnadel",
"Mondhaarnadel",
"Lichtkranz",
"Kleehut",
"Schülermütze",
"Flamencohut",
"Rotteamkappe",
"Weißteamkappe",
"Hotdog-Hut",
"Zeremonienhut",
"Kaiserhut",
"Bananensplit-Hut",
"Schulmütze (blau)",
"Schulmütze (weiß)",
"Polizeimütze (weiß)",
"Königskrone",
"Königinnenkrone",
"Flickenmütze",
"Geburtstagshut",
"Neujahrshut (rot)",
"Neujahrshut (gelb)",
"Neujahrshut (blau)",
"Neujahrshut (grün)",
"N-Kappe",
"Schleifchen-Strohhut",
"Schwesternhaube",
"Mädchen-Nachtmütze",
"Karo-Filzhut",
"Hibiskus-Haarspange",
"Flach-Reishut",
"Kegel-Reishut",
"Matadorhut",
"Ballonhut",
"Jungen-Nachtmütze",
"Kreissäge",
"Handtuch",
"Duschhaube",
"Schlapphut",
"Blumenspange",
"Karnevalsschmuck",
"Glockenhut",
"Pilotenmütze",
"Schülerhut",
"Leuchtkugelfühler",
"Leuchtblumenfühler",
"Leuchtherzchenfühler",
"Leuchtsternfühler",
"Briefträgermütze",
"Schirmmütze",
"Mini-Seidenhut",
"Kalamati-Mütze",
"Hello-Kitty-Hut",
"My-Melody-Hut",
"Kiki-&-Lala-Hut",
"Cinnamoroll-Hut",
"Teich-Spange",
"Übermut-Hut",
"Eufemia-Schleife",
"Lokführerkappe",
,
"Streifenpudelmütze",
"Pilotenkappe",
"Feuerwehrhut",
"Babyhütchen",
"Turban",
"Federschmuck",
"Kufiya",
"Kuhschädelhelm",
"Samuraiperücke",
"Geishaperücke",
"Ninjakapuze",
"Richterperücke",
"Afroperücke",
"Schlapp-Perücke",
"Irokesenperücke",
"Khan-Perücke",
"Dutt",
"Diadem",
"Brautschleier",
"Haarturban",
"Hasenkapuze",
"Katzenmütze",
"Bärenmütze",
"Froschmütze",
"Käpten-Mütze",
"Samuraihelm",
"Heldenhut",
"Rennfahrerhelm",
"Motorradhelm",
"Football-Helm",
"Ritterhelm",
"Legionärshelm",
"Taucherhelm",
"Astronautenhelm",
"Skimaske",
"Wrestlingmaske",
"Retro-Helm",
"Rotheldenhelm",
"Blauheldenhelm",
"Grünheldenhelm",
"Heldinnenhelm",
"Ogermaske (rot)",
"Ogermaske (blau)",
"Majoramaske",
"Samusmaske",
"Midnamaske",
"Toad-Mütze",
"Kürbiskopf",
"Pharaomaske",
"Gespenstermaske",
"Monstermaske",
"Insektenmaske",
"Mumienmaske",
"Blatt-Pikmin",
"Knospen-Pikmin",
"Blüten-Pikmin",
"Mädchentag-Perücke",
"Grünboxerhelm",
"Rotboxerhelm",
"Schneemannhut",
"Hochzeitshaube",
"Kintaro-Perücke",
"Schottenmütze",
"Hörnerhelm",
"Rothaube",
"Strähnchenperücke",
"Makorusmaske",
"Fechtmaske",
"Hochsteckperücke",
"DJ-Kappe",
"Löwentanzmaske",
"Haarknotenperücke",
"Tingle-Mütze",
"Lila-Kobold-Mütze",
"Kabuki-Hut",
"Großmutterperücke",
"Skelettkapuze",
"Schwarzschleier",
"Afromütze",
"Werwolfmütze",
"Oger-Perücke",
"Taucherkappe",
"Wanderkopftuch",
"Phai-Maske",
"Münzen-Stirnband",
"Baseballhelm",
"Jockeyhelm",
"Eishockeyhelm",
"Blauboxerhelm",
"Zöpfchenperücke",
"Kürbiskopf (lila)",
"Kürbiskopf (gelb)",
"Kürbiskopf (grün)",
"Kürbiskopf (rot)",
"Geburtstagsbrille",
"Link-Hut",
"Ganondorf-Perücke",
"Shiek-Perücke",
"Zelda-Perücke",
"Neuheld-Perücke",
"Aioli-Perücke",
"Limone-Perücke",
"Pilotenbrille",
"Studio-Kopfhörer",
"Blumenelfenperücke",
"Navirou-Maske",
"Pompompurin-Hut",
"Karlotta-Dutt"
],

//Accesories
[
"Azurbrille",
"Rubinbrille",
"Bernsteinbrille",
"Minzbrille",
"Lilabrille",
"Smaragdbrille",
"Streberbrille",
"Girlie-Brille",
"Hornbrille",
"Silberbrille",
"Laborbrille",
"Omabrille",
"Krötenbrille",
"Graziabrille",
"Pilotenbrille",
"Sportbrille",
"Riesenbrille",
"Dreiecksbrille",
"Sonnenbrille",
"Herzchenbrille",
"Sternenbrille",
"3D-Brille",
"Karnevalsmaske",
"Heldenmaske",
"Schwimmbrille",
"Taucherbrille",
"Augenmaske",
"Cyberhelm",
"Monokel",
"Arztspiegel",
"Augenklappe",
"Augenverband",
"Gasmaske",
"Hockeymaske",
"Clownsmaske",
"Clownsnase",
"Schnauzerbrille",
"Mario-Schnauzer",
"Wario-Schnauzer",
"Schnauzbart",
"Königsbart",
"Mundschutz",
"Schnuller",
"Schnabel",
"Zitronenmaske",
"Gurkenmaske",
"Pflaster",
"Lamellenbrille",
"Weihnachtsmannbart",
"Retro-Brille",
"Cyberbrille",
"Ballmaske",
"Scherzbrille",
"Blatt",
"Steampunkbrille",
"Spiegelbrille",
"Kosmetikmaske",
"Ovalbrille",
"Papageitulpe",
"Triumphtulpe",
"Viridifloratulpe",
"Grengjer-Tulpe",
"Wildtulpe",
"Römertulpe",
"Flachlandtulpe",
"Pfingstveilchen",
"Hornveilchen",
"Alpenveilchen",
"Hainveilchen",
"Stiefmütterchen",
"Duftveilchen",
"Gartenprimel",
"Kissenprimel",
"Aurikel",
"Sumpfprimel",
"Zwergprimel",
"Kugelprimel",
"Liebesrose",
"Unschuldsrose",
"Bernsteinrose",
"Pinkrose",
"Sonnenrose",
"Lilarose",
"Schwarzrose",
"Blaurose",
"Goldrose",
"Bartnelke",
"Heidenelke",
"Federnelke",
"Osterlilie",
"Pyrenäenlilie",
"Rotlilie",
"Feuerlilie",
"Türkenbundlilie",
"Dunkellilie",
"Waldveilchen",
"Blauveilchen",
"Grabenveilchen",
"Galmeiveilchen",
"Maiglöckchen",
"Glückskleeblatt",
"Löwenzahn",
"Pusteblume"
],

//Gyroids
[
"Mega-Klirroid",
"Klirroid",
"Mini-Klirroid",
"Maxi-Klirroid",
"Kompakt-Klingoid",
"Mega-Klingoid",
"Klingoid",
"Mini-Klingoid",
"Mikro-Klingoid",
"Maxi-Klingoid",
"Mega-Trommloid",
"Maxi-Trommloid",
"Mega-Uumbloid",
"Uumbloid",
"Mini-Uumbloid",
"Maxi-Uumbloid",
"Rhythmoid",
"Mini-Rhythmoid",
"Mega-Pustoid",
"Mini-Pustoid",
"Maxi-Pustoid",
"Mega-Schlafloid",
"Schlafloid",
"Mini-Schlafloid",
"Maxi-Schlafloid",
"Mega-Federoid",
"Federoid",
"Mini-Federoid",
"Maxi-Federoid",
"Mega-Beugoid",
"Beugoid",
"Mini-Beugoid",
"Maxi-Beugoid",
"Mega-Hupoid",
"Hupoid",
"Mini-Hupoid",
"Mega-Blinkoid",
"Blinkoid",
"Mini-Blinkoid",
"Mega-Dekoid",
"Dekoid",
"Mini-Dekoid",
"Mega-Summoid",
"Summoid",
"Mini-Summoid",
"Maxi-Summoid",
"Mega-Bohroid",
"Bohroid",
"Mini-Bohroid",
"Mega-Echoid",
"Mini-Echoid",
"Maxi-Echoid",
"Mega-Jammeroid",
"Jammeroid",
"Mini-Jammeroid",
"Maxi-Jammeroid",
"Mega-Klimperoid",
"Klimperoid",
"Mini-Klimperoid",
"Maxi-Klimperoid",
"Mega-Krächzoid",
"Krächzoid",
"Mini-Krächzoid",
"Maxi-Krächzoid",
"Mega-Sprudloid",
"Mini-Sprudloid",
"Mega-Knarroid",
"Knarroid",
"Mini-Knarroid",
"Mega-Heuloid",
"Heuloid",
"Mini-Heuloid",
"Mega-Flötoid",
"Sitz-Flötoid",
"Flötoid",
"Mini-Flötoid",
"Maxi-Flötoid",
"Mager-Flötoid",
"Mega-Gongoid",
"Gongoid",
"Mini-Gongoid",
"Maxi-Gongoid",
"Mega-Poltergoid",
"Poltergoid",
"Mini-Poltergoid",
"Maxi-Poltergoid",
"Metakloid",
"Mini-Metakloid",
"Mega-Grunzoid",
"Maxi-Grunzoid",
"Mega-Oboid",
"Oboid",
"Maxi-Oboid",
"Mega-Bingoid",
"Mini-Bingoid",
"Mega-Harmonoid",
"Harmonoid",
"Mini-Harmonoid",
"Maxi-Harmonoid",
"Maxi-Tropfloid",
"Mega-Computoid",
"Computoid",
"Mini-Computoid",
"Maxi-Computoid",
"Mega-Alloid",
"Mini-Alloid",
"Maxi-Alloid",
"Mega-Paukoid",
"Paukoid",
"Mini-Paukoid",
"Maxi-Paukoid",
"Gluckoid",
"Mini-Gluckoid",
"Maxi-Gluckoid",
"Gurgloid",
"Mini-Gurgloid",
"Maxi-Gurgloid",
"Mega-Flippoid",
"Mini-Flippoid",
"Mega-Morsoid",
"Morsoid",
"Mini-Morsoid",
"Maxi-Morsoid",
"Mager-Morsoid",
"Mega-Rostoid",
"Rostoid",
"Mini-Rostoid",
"Mega-Kofioid",
"Mini-Kofioid",
"Maxi-Kofioid",
"Kofioid"
],

//Furniture
[
"Orient-Bett",
"Orient-Kommode",
"Orient-Schrank",
"Orient-Bank",
"Orient-Stuhl",
"Orient-Tisch",
"Orient-Tischchen",
"Orient-Lampe",
"Orient-Paravent",
"Orient-Truhe",
"Orient-Wandregal",
"Western-Bett",
"Western-Kommode",
"Western-Schrank",
"Western-Sofa",
"Western-Sessel",
"Western-Stuhl",
"Western-Tisch",
"Western-Teetisch",
"Western-Regal",
"Western-Anrichte",
"Western-Wandregal",
"Klassikbett",
"Klassikfrisiertisch",
"Klassikschrank",
"Klassikstuhl",
"Klassiksofa",
"Klassiktisch",
"Klassikregal",
"Klassiksofatisch",
"Klassiksekretär",
"Klassikstanduhr",
"Klassikhängeschrank",
"Royalbett",
"Royalkommode",
"Royalschrank",
"Royalstuhl",
"Royalsofa",
"Royaltisch",
"Royallampe",
"Royalstanduhr",
"Royalvitrine",
"Royalspiegel",
"Royalwandlampe",
"Azurbett",
"Azurkommode",
"Azurschrank",
"Azurstuhl",
"Azurbank",
"Azurtisch",
"Azurregal",
"Azurspind",
"Azuruhr",
"Azurschränkchen",
"Azurwandregal",
"Korbbett",
"Korbkommode",
"Korbschrank",
"Korbstuhl",
"Korbsessel",
"Korbtisch",
"Korblampe",
"Korb-Bücherregal",
"Korbspiegel",
"Korb-Wandschirm",
"Korb-Wandradio",
"Smaragdbett",
"Smaragdkommode",
"Smaragdschrank",
"Smaragdstuhl",
"Smaragdbank",
"Smaragdtisch",
"Smaragdpult",
"Smaragdtischchen",
"Smaragdanrichte",
"Smaragdbüfett",
"Smaragdwanduhr",
"Blockhausbett",
"Blockhauskommode",
"Blockhausschrank",
"Blockhausstuhl",
"Blockhaussessel",
"Blockhaussofa",
"Blockhaustisch",
"Blockhaustischchen",
"Blockhausregal",
"Blockhausuhr",
"Blockhauswanduhr",
"Schachbett",
"Schachkommode",
"Schachschrank",
"Schachstuhl",
"Schachsofa",
"Schachecktisch",
"Schachschreibtisch",
"Schachtisch",
"Schachschränkchen",
"Schachlampe",
"Schachwanduhr",
"Kinderbett",
"Kinderkommode",
"Kinderschrank",
"Kindersofa",
"Kinderstuhl",
"Kindertisch",
"Kindergarderobe",
"Kinderregal",
"Kinderuhr",
"Kinderanlage",
"Kinderwanduhr",
"Herzchenbett",
"Herzchenkommode",
"Herzchenschrank",
"Herzchenstuhl",
"Herzchensofa",
"Herzchentisch",
"Herzchensofatisch",
"Herzchenspiegel",
"Herzchenküche",
"Herzchenlampe",
"Herzchenwanduhr",
"Robo-Bett",
"Robo-Kommode",
"Robo-Schrank",
"Robo-Sofa",
"Robo-Stuhl",
"Robo-Tisch",
"Robo-Anlage",
"Robo-Fernseher",
"Robo-Uhr",
"Robo-Lampe",
"Robo-Wanduhr",
"Pünktchenbett",
"Pünktchenkommode",
"Pünktchenschrank",
"Pünktchensessel",
"Pünktchensofa",
"Pünktchentisch",
"Pünktchenlampe",
"Pünktchenhocker",
"Pünktchensofatisch",
"Pünktchenfernseher",
"Pünktchenuhr",
"Schneemannbett",
"Schneemannkommode",
"Schneemannschrank",
"Schneemannstuhl",
"Schneemannsofa",
"Schneemanntisch",
"Schneemannkühler",
"Schneemannfernseher",
"Schneemannuhr",
"Schneemannlampe",
"Schneemannspiegel",
"Pilzbett",
"Pilzkommode",
"Pilzschrank",
"Pilzstuhl",
"Pilzhocker",
"Pilztisch",
"Pilztischchen",
"Pilzlampe",
"Pilzwandlampe",
"Pilzfernseher",
"Pilzgarderobe",
"Karnevalsbett",
"Karnevalskommode",
"Karnevalsschrank",
"Karnevalssofa",
"Karnevalssessel",
"Karnevalstisch",
"Karnevalsecktisch",
"Karnevalsregal",
"Karnevalsspiegel",
"Karnevalslampe",
"Karnevalsuhr",
"Eierbett",
"Eierkommode",
"Eierschrank",
"Eierstuhl",
"Eierliege",
"Eiertisch",
"Eieranlage",
"Eierspielzeug",
"Eieruhr",
"Eierlampe",
"Eierfernseher",
"Kürbisbett",
"Kürbiskommode",
"Kürbisschrank",
"Kürbissofa",
"Kürbisstuhl",
"Kürbistisch",
"Kürbisspiegel",
"Kürbisregal",
"Kürbisuhr",
"Kürbislampe",
"Kürbiswandlampe",
"Herbstbett",
"Herbstkommode",
"Herbstschrank",
"Herbstsofa",
"Herbststuhl",
"Herbsttisch",
"Herbstspiegel",
"Herbstfernseher",
"Herbstuhr",
"Herbstlampe",
"Herbstwandlampe",
"Festtagsbett",
"Festtagskommode",
"Festtagsschrank",
"Festtagssofa",
"Festtagsstuhl",
"Festtagstisch",
"Festtagsregal",
"Festtagspiano",
"Festtagsstanduhr",
"Festtagslampe",
"Festtagsfernseher",
"Prachtbett",
"Prachtkommode",
"Prachtschrank",
"Prachtsofa",
"Prachtstuhl",
"Prachttisch",
"Prachtvitrine",
"Prachtspiegel",
"Prachtkäfig",
"Prachtlampe",
"Prachtuhr",
"Graziabett",
"Graziakommode",
"Graziaschrank",
"Graziabank",
"Graziastuhl",
"Graziatisch",
"Graziaschreibtisch",
"Graziawagen",
"Graziaregal",
"Grazialampe",
"Graziawanduhr",
"Süßbett",
"Süßkommode",
"Süßschrank",
"Süßsofa",
"Süßstuhl",
"Süßtisch",
"Süßminitisch",
"Süßregal",
"Süßlampe",
"Süßminilampe",
"Süßanlage",
"Luxusbett",
"Luxuskommode",
"Luxusschrank",
"Luxussofa",
"Luxussessel",
"Luxushocker",
"Luxustisch",
"Luxuspult",
"Luxusanrichte",
"Luxuslampe",
"Luxusuhr",
"Minimalbett",
"Minimalsofa",
"Minimalstuhl",
"Minimalkommode",
"Minimalschrank",
"Minimaluhr",
"Minimallampe",
"Minimalschemel",
"Minimaltisch",
"Minimaltischchen",
"Minimalspiegel",
"Goldbett",
"Goldkommode",
"Goldschrank",
"Goldstuhl",
"Goldbank",
"Goldtisch",
"Golduhr",
"Goldmann",
"Goldfrau",
"Goldwandschirm",
"Goldfackel",
"Kuhschädel",
"Wüstenkaktus",
"Wildwest-Zaun",
"Sattelablage",
"Fassade",
"Planwagen",
"Tränke",
"Steppenläufer",
"Brunnen",
"Wagenrad",
"Sternensplitter",
"Mond",
"Landefähre",
"Rakete",
"Mondfahrzeug",
"Raumsonde",
"Raumfähre",
"Raumanzug",
"Raumstation",
"UFO",
"Umleitungsschild",
"Schubkarre",
"Stahlträger",
"Kanaldeckel",
"Absperrhütchen",
"Verkehrshütchen",
"Straßensperre",
"Warnschild",
"Dampfwalze",
"Presslufthammer",
"Streifenhütchen",
"Zementmischer",
"Ölfass",
"Absperrung",
"Ecke (rot)",
"Ecke (blau)",
"Ecke (neutral)",
"Rundengong",
"Matte",
"Kampfrichtertisch",
"Hantelbank",
"Sandsack",
"Maisbirne",
"Vogelhaus",
,
,
"Gartenzwerg",
"Insektenfänger",
"Hängematte",
"Vogeltränke",
"Picknicktisch",
"Vogelfutterplatz",
"Gartenstuhl",
"Rasenmäher",
"Grill",
"Planschbecken",
"Rasensprenger",
"Fackel",
"Elefantenrutsche",
"Kinderwagen",
"Wiege",
"Babybett",
"Spielwagen",
"Karussell",
"Schaukelpferd",
"Modelleisenbahn",
"Stehaufpüppchen",
"Püppchen",
"Laborliege",
"Laborstuhl",
"Medizinschrank",
"Rundkolben",
"Elektromaschine",
"Energiemaschine",
"Streckmaschine",
"Steuerrad",
"Fass",
"Fässchen",
"Schiffskanone",
"Anker",
"Schiffskompass",
"Gruselskelett",
"Gruselkessel",
"Gruselmausstein",
"Gruselstein",
"Gruselsarg",
"Gruselkristall",
"Gruseluhr",
"Gruselstatue",
"Bauer",
"Läufer",
"König",
"Springer",
"Dame",
"Turm",
"Tafelhälfte (rechts)",
"Tafelhälfte (links)",
"Lehrerpult",
"Lehrertisch",
"Lehrerstuhl",
"Schultisch",
"Schulstuhl",
"Schuhregal",
"Tafel",
"Wischmopp",
"Skelett",
"Anatomiemodell",
"Kreislaufmodell",
"Hamsterkäfig",
"Labortisch",
"Sprungkasten",
"Ballwagen",
"Turnmatte",
"Hürde",
"Punktetafel",
"Klappstuhl",
"Augentest",
"Rumpfmesser",
"Stadiometer",
"Waage",
"Krankenhausbett",
"Patientenvorhang",
"Infusionsständer",
"Spültisch",
"Sekretär",
"Sekretärstuhl",
"Globus",
"Bürotisch",
"Bürostuhl",
"Büroschrank",
"Kaffeemaschine",
"Hoteltresen",
"Kasse",
"Musikbox",
"Siphon",
"Riesen-Daruma",
"Daruma",
"Mini-Daruma",
"Papa-Bär",
"Mama-Bär",
"Baby-Bär",
"Mama-Eisbär",
"Papa-Panda",
"Mama-Panda",
"Baby-Panda",
"Langkaktus",
"Flachkaktus",
"Kugelkaktus",
"Profi-Golfbag",
"Ledersessel",
"Ledersofa",
"Bären-Totempfahl",
"Adler-Totempfahl",
"Unken-Totempfahl",
"Raben-Totempfahl",
"Lavalampe",
"Teetischchen",
"Kochfeuer",
"Paravent",
"Kohlebecken",
"Tansu-Teeschrank",
"Papierlaterne",
"Papier-Wandlaterne",
"Asternschrank",
"Stufenschrank",
"Sichtschutz",
"Papiertiger",
"Glücksfroschset",
"Schwert",
"Bogen",
"Samuraikostüm",
"Mondkatana",
"Sonnenkatana",
"Ninjaschwert",
"Wasserspiel",
"Mega-Laterne",
"Hockerturm",
"Badematte",
"Schüssel",
"Badebecken",
"Milchtruhe",
"Eiscremetruhe",
"Wascheinheit",
"Biedermeier-Vase",
"Jugendstil-Vase",
"Ming-Vase",
"Glückskatze",
"Linkshänderkatze",
"Schwarz-Glückskatze",
"Gold-Glückskatze",
"Grapefruittisch",
"Zitronentisch",
"Orangenstuhl",
"Kiwihocker",
"Birnenschrank",
"Birnenkommode",
"Melonensitz",
"Melonentisch",
"Apfelfernseher",
"Apfeluhr",
"Seerosentisch",
"Froschstuhl",
"Kiefernstuhl",
"Kieferntisch",
"Blümchenstuhl",
"Blümchentisch",
"Ponderosa-Bonsai",
"Pinien-Bonsai",
"Bergkiefern-Bonsai",
"Pflaumen-Bonsai",
"Palmen-Bonsai",
"Azaleen-Bonsai",
"Ahorn-Bonsai",
"Weißdorn-Bonsai",
"Quitten-Bonsai",
"Jasmin-Bonsai",
"Pothos",
"Kokosnusspalme",
"Pachira",
"Buntwurz",
"Wunderstrauch",
"Drachenbaum",
"Steckenpalme",
"Aloe Vera",
"Gummibaum",
"Bogenhanf",
"Fächerpalme",
"Yuccapalme",
"Bromelia",
"Birkenfeige",
"Kongatrommel",
"Djembetrommel",
"Pauke",
"Geige",
"Cello",
"Kontrabass",
"Folk-Gitarre",
"Country-Gitarre",
"Rock-Gitarre",
"Jazz-Gitarre",
"Ukulele",
"Konzertflügel",
"Klavier",
"Taiko-Trommel",
"Vibrafon",
"Laute",
"Harfe",
"Taktmesser",
"Abfalleimer",
"Abfalltonne",
"Mülltonne",
"Mülleimer",
"Ruhmessäule",
"Ioniersäule",
"Korinthersäule",
"Antiksäule",
"Pyramide",
,
"Sarkophag",
"Jomon-Töpferei",
"Tischtennisset",
"Bowlingset",
"Bowlingmaschine",
"Basketballkorb",
"Billardtisch",
"Mah-Jongg-Tisch",
"Dartbrett",
"Flipper",
"Arcade-Spiel",
"Videospieltisch",
"Hocker",
"Shogi-Brett",
"Go-Brett",
"Triumphbogen",
"Ritterrüstung",
"Turm von Pisa",
"Kompass",
"Schokolade",
"Rucksack",
"Mountainbike",
"Gasgrill",
"Kajak",
"Laterne",
"Schlafsack",
"Lagerfeuer",
"Feuer",
"Videofernseher",
"Großbild-Fernseher",
"Retro-Fernseher",
"Küchenzeile",
"Küchenecke",
"Luxusherd",
"Kochherd",
"Herd",
"Spülbecken",
"Tee-Service",
"Eismaschine",
"Kühlschrank",
"Retro-Kühlschrank",
"Mikrowelle",
"Toaster",
"Mixer",
"Wäscheleine",
"Hundehütte",
"Sonnenstuhl",
"Wellenbrecher",
"Surfbrett",
"Taucher Tom",
"Strandtisch",
"Schatzkiste",
"Rettungsring",
"Snowboard",
"Schlitten",
"Schneemann",
"Sonnenblume",
"Osterglocke",
"Gerbera",
"Toilette",
"Luxustoilette",
"Pissoir",
"Regal",
"Safe",
"Profi-Waschmaschine",
"Uralt-Waschmaschine",
"Wäschetrockner",
"Kanonenofen",
"Heizgerät",
"Kamin",
"Heizkörper",
"Grammofon",
"Kastengrammofon",
"Tonbandgerät",
"Retro-Anlage",
"Goldanlage",
"Hi-Fi-Anlage",
"Highend-Anlage",
"Würfel-Anlage",
"Radiorekorder",
"CD-Player",
"Kassettenrekorder",
"Runduhr",
"Kitsch-Uhr",
"Antikstanduhr",
"Würfeluhr",
"Fernost-Uhr",
"Ovaluhr",
"Eulenuhr",
"Wecker",
"Normalstuhl",
"Schaukelstuhl",
"Pult (links)",
"Pult (rechts)",
"Zapfsäule",
"Feuerlöscher",
"Hydrant",
"Waschbärenfigur",
"Streifenstange",
"Snackautomat",
"Vogelscheuche",
"Vogelkäfig",
"Telefonzelle",
"Schwimmteich",
"Weizenfeld",
"Computer",
"Ananasbett",
"Glastisch",
"Heiztisch",
"Cremesofa",
"Aktenschrank",
"Kleiderschrank",
"Badewanne",
"Dusche",
"Massagesessel",
"Staubsauger",
"Flaschenschiff",
"Trinkvogel",
"Tischspielzeug",
"Teleskop",
"Mörser",
"Pedalnähmaschine",
"Karton",
"Holzkiste",
"Ventilator",
"Kerze",
"Minilampe",
"Arbeitslampe",
"Tischlampe",
"Thron",
"Normalbett",
,
"Münze",
"Zielpfahl",
"Feuerblume",
"Superpilz",
"Koopa-Panzer",
"Superstern",
"1-Up-Pilz",
"?-Block",
"Röhre",
"Feuerbarriere",
"Willi-Kanone",
"Yoshi-Ei",
"Dreier-Banane",
"Rotpanzer-Set",
"Kart",
,
,
"Master-Schwert",
,
,
,
"Dolphin-Modell",
"Schachtelkobold",
"Kadomatsu",
"Kagami-Mochi",
"Puppenset",
"Tannenbaum",
"Tannenbäumchen",
"Festfahne",
"Kerzenleuchter",
"Herzchentelefon",
"Taschentuch",
"Sparschwein",
"Bankautomat",
"Alukoffer",
"Reiskuchen",
"Dango-Schachtel",
"Bambus",
"Resetti-Figur",
"Globus (cool)",
"Picknick-Korb",
"Modellschiff",
"Weizenbündel",
"Espressokanne",
"Festtagssocke",
"Schneekugel",
"Gemüsekorb",
"Yut-Spiel",
"Hibiskus",
"Nuss-Schälchen",
"Festtagskranz",
"Brauntopf",
"Weißtopf",
"Wandteppich",
"Kreisel",
"Bildnische",
"Karpfenwimpel",
"Auberginenkuh",
"Prunkwinde",
"Laubhaufen",
"Sandburg",
"Einkaufswagen",
"Hagoita-Schläger",
"Blütenlampe",
"Gurkenpferd",
"Filzhut-Stuhl",
"Tteok-Schale",
"Kimbap-Teller",
"Eiscreme-Lampe",
"Blumenstrauß",
"Amorbank",
"Ausstellungssockel",
"Standvitrine",
"Tischvitrine",
"Wandvitrine",
"Museumshocker",
"Wegweiser",
"Prunkbilderrahmen",
"Hygrometer",
"Empfangstisch",
"Posterrahmen",
"Ausstellungswand",
"Quallenlampe",
"Klimaanlage",
"Pendeluhr",
"LED-Wandanzeige",
"Gold-Angelpokal",
"Silber-Angelpokal",
"Bronze-Angelpokal",
"Gold-Insektenpokal",
"Silber-Insektenpokal",
"Bronze-Insektenpokal",
"Museumsmodell",
"Briefset",
"Neujahrsgericht",
"Bronzeglocke",
"Plastikhocker",
"Füllhorn",
"Kürbiskuchen",
"Truthahn",
"Kuchentablett",
"Doppel-Bücherregal",
"Stehleiter",
"Mikroskop",
"Orchidee",
"Dreirad",
"Duschkabine",
"Standmikrofon",
"Tatamibett",
"Cembalo",
"Regiestuhl",
"Theremin",
"Etagenbett",
"Fernost-Puppe",
"Volleyballnetz",
"Klavierhocker",
"Bûche de Noël",
"Barockpuppe",
"Fruchtkorb",
"Weihnachtsstern",
"Bratplatte",
"Schneehäschen",
"Retro-Telefon",
"Plattenspieler",
"Spinnrad",
"Aufklapp-Bilderbuch",
"Wassereimer",
"Spirituslampe",
"Wasserkocher",
"Hochzeitstorte",
"Bonbonglas",
"Festtagsgesteck",
"Holzkohlengrill",
"Glöckchenlampe",
"Standscheinwerfer",
"Scheinwerfer",
"Buntglaslampe",
"Camping-Kochkessel",
"Mini-Iglu",
"Zahlenrad",
"Retro-Kamera",
"LED-Tafel",
"AdsH-Fähnchen",
"AdsH-Silberabzeichen",
"AdsH-Goldabzeichen",
"AdsH-Silberpokal",
"AdsH-Goldpokal",
"Gold-Hausmodell",
"Kratzbaum",
"Geschirrspüler",
"Holzschemel",
"CD-Schrank",
"Metal-Gitarre",
"Zeitschriftenregal",
"Pappkoffer",
"Milchkanne",
"Garderobenständer",
"Lotuslampe",
"Nähmaschine",
"Puppenhaus",
"Eiscremespender",
"PC-Arbeitsplatz",
"Töpfchen",
"Wasserkessel",
"Hausaufgaben-Set",
"Salatbüfett",
"Absperrkordel",
"Waschmaschine",
"Duftlampe",
"Kandidatenpult",
"Getränkekühlschrank",
"Donut-Hocker",
"Snackvitrine",
"Kochstelle",
"Flachbildfernseher",
"Zahlenkugel-Maschine",
"Chefsessel",
"Malset",
"Chefschreibtisch",
"Gewürzständer",
"Waschbecken",
"Räucherstäbchen-Set",
"Zeitschriftenablage",
"Reiskocher",
"Planetariumprojektor",
"Sushi-Bar",
"Himmelsglobus",
"Whiteboard",
"Pfauenstuhl",
"Whirlpool",
"Kücheninsel",
"Kissen",
"Sanshin",
"Effekt-Rack",
"Luftbefeuchter",
"Stechuhr",
"Kranspiel",
"Notenständer",
"Bügelset",
"Rollkoffer",
"Blumenkasten",
"Zahnarztstuhl",
"Verstärker",
"Webstuhl",
"Asia-Restauranttisch",
"Einmachglas",
"Fernsehkamera",
"Büfett",
"Kühltruhe",
"Feuertopf",
"Suppentopf",
"Notebook",
"Server",
"Kopierer",
"Schlagzeug",
"Getränkespender",
"Wasserspender",
"Stabstaubsauger",
"Schminkbox",
"Doppelhals-Gitarre",
,
"Popcorn-Maschine",
"DJ-Set",
"Blumengesteck",
"Softeis-Lampe",
"Heimcomputertisch",
"Orgel",
"Karaoke-Set",
"Teekessel",
"Digitalbilderrahmen",
"Küchenregal",
"Wandgesteck",
"Wandregal",
"Buntglasscheibe",
"Wandlautsprecher",
"Urkunde",
"Minifernseher",
"Kuckucksuhr",
"Wandventilator",
"Mobile",
"Sicherungskasten",
"Fernost-Urkunde",
"Lüftungsventilator",
"Deko-Rettungsring",
"Lampion",
"Überwachungskamera",
"Notausgangsschild",
"Lautsprecherbox",
"Wandleuchter",
"Toilettenkabine",
"Toilettenhäuschen",
"Greisenmaske",
"Dämonenmaske",
"Frauenmaske",
"Spinnennetz-Uhr",
"Raupensofa",
"Nashornkäferstuhl",
"Hirschkäferstuhl",
"Bienenkommode",
"Leuchtkäferlampe",
"Schmetterlingstisch",
"Marienkäferschemel",
"Schneckenuhr",
"Zikadenanlage",
"Seeanemonenbett",
"Tintenfischstuhl",
"Krebsuhr",
"Leuchtfischlampe",
"Oktopushocker",
"Fischsofa",
"Kugelfischfernseher",
"Schollentisch",
"Flundertisch",
"Waschbärenwanduhr",
"Mini-Langkaktus",
"Mini-Flachkaktus",
"Mini-Kugelkaktus",
"Fahrradergometer",
"Kraftstation",
"Latzuggerät",
"Laufband",
"Brotkasten",
"Chaiselongue",
"Schokoladenbrunnen",
"Sofa-Element",
"Sofa-Eckelement",
"Kantinentablett",
"Sanduhr",
"Spielzeugfiguren-Set",
"Modellauto",
"Autorennbahn",
"Spielzeugautomat",
"Bilboquet",
"Kickertisch",
"Schiebepuzzle",
"Eierkörbchen",
"Raumteiler",
"Schreibmaschine",
"Designerregal",
"Designeranlage",
"Designerbett",
"Designersofa",
"Designerstuhl",
"Designerkommode",
"Designerschrank",
"Designeruhr",
"Designerlampe",
"Designertisch",
"Designertischchen",
"Buntholzbett",
"Buntholzbank",
"Buntholzstuhl",
"Buntholzkommode",
"Buntholzschrank",
"Buntholzuhr",
"Buntholzlampe",
"Buntholzhocker",
"Buntholztisch",
"Buntholzregal",
"Buntholzfernseher",
"Nixenbett",
"Nixensofa",
"Nixenstuhl",
"Nixenkommode",
"Nixenschrank",
"Nixenuhr",
"Nixenspiegel",
"Nixenlampe",
"Nixenraumtrenner",
"Nixenregal",
"Nixentisch",
"Eiskommode",
"Eisschränkchen",
"Eistisch",
"Eisstuhl",
"Eistischchen",
"Eislampe",
"Eisregal",
"Eissofa",
"Eisbett",
"Eisuhr",
"Eisspiegel",
"Rokoko-Kerzenhalter",
"Rokoko-Bett",
"Rokoko-Regal",
"Rokoko-Sofa",
"Rokoko-Sessel",
"Rokoko-Kommode",
"Rokoko-Schrank",
"Rokoko-Uhr",
"Rokoko-Spiegel",
"Rokoko-Lampe",
"Rokoko-Tisch",
"Nordbett",
"Nordsofa",
"Nordstuhl",
"Nordkommode",
"Nordschrank",
"Nordlampe",
"Nordfliese",
"Nordregal",
"Nord-Esstisch",
"Nord-Sofatisch",
"Nordwägelchen",
"Astro-Anlage",
"Astrobett",
"Astrosofa",
"Astrostuhl",
"Astrokommode",
"Astroschrank",
"Astrouhr",
"Astrotisch",
"Astrofernseher",
"Astroregal",
"Astrolampe",
"Kartenhaus",
"Kartenbett",
"Kartensofa",
"Kartenstuhl",
"Kartenkommode",
"Kartenschrank",
"Kartenwanduhr",
"Kartenlampe",
"Kartenraumteiler",
"Kartenregal",
"Kartentisch",
"Streifenkommode",
"Streifenlampe",
"Streifenschrank",
"Streifenfernseher",
"Streifentisch",
"Streifensofa",
"Streifenregal",
"Streifenuhr",
"Streifenbett",
"Streifenwaschbecken",
"Streifenstuhl",
"Schlamperbett",
"Schlampersofa",
"Schlamperuhr",
"Schlamperstuhl",
"Schlampertisch",
"Schlamperschrank",
"Schlamperspülbecken",
"Schlamperlampe",
"Schlamperanlage",
"Schlamperfernseher",
"Schlamperkommode",
"Fackelständer",
"Fahnenmast",
"Holzfächer",
"Pappbusch",
"Pappgras",
"Papphügel",
"Pappbaum",
"Kakaobaum",
"Trinkwasserbrunnen",
"Efeu-Topfpflanze",
"Wunderlampe",
"Bumerang",
"Neonschild",
"Barcelos-Hahn",
"Dalapferd",
"Traumfänger",
"Knochenfigur",
"Postplakat",
"Kleeblattuhr",
"Drachenlaterne",
"Hula-Puppe",
"Moai-Statue",
"Stammesmaske",
,
"Pagode",
"Meerjungfrau",
"Wahrheitsmund",
,
"Matroschka",
"Samgyetang-Suppe",
"Eiffelturm",
"Piratenflagge",
"Retro-Teleskop",
"Piratenrüstung",
"Marshmallow-Hocker",
"Kartontisch",
"Kartonhocker",
"Kartonsofa",
"Kartonschrank",
"Kartonbett",
"Rattenfigur",
"Büffelfigur",
"Tigerfigur",
"Hasenfigur",
"Drachenfigur",
"Schlangenfigur",
"Pferdefigur",
"Schafsfigur",
"Affenfigur",
"Hahnenfigur",
"Hundefigur",
"Schweinefigur",
"Wandmonitor",
"Holoprojektor",
"Pilotenstuhl",
"Crewstuhl",
"Forschungskonsole",
"Kontrollkonsole",
"Steuerkonsole",
"Pilotenmonitor",
"Crewmonitor",
"3D-Radarbild",
"Schokoladenkuchen",
"Milch- und Zuckerset",
"Kaffeetasse",
"Kuchenvitrine",
"Kaffeemühle",
"Geburtstagstisch",
"Geburtstagsdeko",
"Geburtstagsschild",
"Geburtstagstorte",
"Skilift",
"Schneemann-Familie",
,
"Curling-Stein",
"Pfeffermühle",
"Skizzenbuch",
"Spielzeugkamera",
"Windmühlen-Souvenir",
"Auto-Rikscha",
"Weltkarte",
"Bob",
"Slalomtor",
"Campingofen",
"Skiständer",
"Sitar",
"Ayers-Rock-Modell",
"Räucherofen",
"Gaudí-Salamander",
"Songpyeon-Teller",
"Dudelsack",
,
"Schneemaschine",
"Traubenteller",
"Aquariumkugel",
"Nussknacker",
,
"Geschenksocke",
"Berliner",
"Schneemobil",
"Love Tester",
"Freiheitsstatue",
"Patchwork-Sessel",
"Patchwork-Kommode",
"Patchwork-Lampe",
"Patchwork-Tisch",
"Patchwork-Sofa",
"Shogun-Klappstuhl",
"Shogi-Stein",
"Spielstein",
"Ballonfernseher",
"Ballonsofa",
"Ballonuhr",
"Ballonlampe",
"Ballontisch",
"Ballonbett",
"Ballonstuhl",
"Ballonkommode",
"Ballonhundlampe",
"Ballonschrank",
"Ballonspiegel",
"Liliengrammofon",
"Rosensessel",
"Sonnenblumenanlage",
"Tulpenkommode",
"Veilchenraumteiler",
"Hortensienbett",
"Azaleenhocker",
"Stiefmütterchentisch",
"Kamillenventilator",
"Hibiskusuhr",
,
,
,
"Giraffenmesslatte",
"Retro-Radio",
"„0“-Lampe",
"„1“-Lampe",
"„2“-Lampe",
"„3“-Lampe",
"„4“-Lampe",
"„5“-Lampe",
"„6“-Lampe",
"„7“-Lampe",
"„8“-Lampe",
"„9“-Lampe",
"Schaukelwidder",
"Stier-Badewanne",
"Zwillinge-Schrank",
"Krebs-Tisch",
"Löwe-Wandschmuck",
"Jungfrau-Harfe",
"Waage-Modell",
"Skorpion-Lampe",
"Schütze-Bogen",
"Steinbock-Skulptur",
"Wassermann-Krug",
"Fische-Lampe",
"Neujahrs-Sonnenlampe",
"Nordlicht-Raumteiler",
"Keimlingtisch",
"Kirschblütenuhr",
"Blattbett",
"Regenbogenraumteiler",
"Palmenlampe",
"Feuerwerkstisch",
"Vollmondspiegel",
"Reisährenbett",
"Herbstlaubstuhl",
"Baumstumpfstuhl",
"Pinnwand",
"Küchenwaage",
"Sushi-Boot",
"Kokeshi-Figur",
"Supermarktmodell",
"Geldautomat",
"Getränkeregal",
"Kühlregal",
"Supermarktschild",
"Supermarktkasse",
"Grillfleisch-Bett",
"Notizbuchschrank",
"Radiergummisofa",
"Notizbuchbett",
"Stifte-Raumteiler",
"Korrekturroller",
"Zeichendreieck-Tisch",
"Spielzeugklavier",
"Untersuchungstisch",
"Schnurtelefon",
"Tischglocke",
"Holzeimer",
"Kokosnusswasser",
"Instant-Nudelsuppe",
"Feuerholz",
"Burger-Menü",
"Armleuchter",
"Kühlbox",
"Waschtisch",
"Verlobungsring",
"Luftreiniger",
"Trennwand",
"Sushibrett",
"Synthesizer",
"Werkzeugkasten",
"Handtuchkorb",
"Haltestange",
"Wollkorb",
"Schulpult",
"U-Bahn-Bank",
"Pizza",
"Pflanzenraumteiler",
"Ramensuppe",
"Tarte",
"Pracht-Tee-Set",
"Ringwurfspiel",
"Moosgesteck",
"Gartenschlauch",
"Mini-Gewächshaus",
"Traktor",
"Braunbärfigur",
"Fukusuke",
"Kalligrafietisch",
"Ikebana",
"Rollwagen",
"Holzregal",
"Fließband",
"Luftpumpe",
"Bücherstapel",
"Brotkorb",
"Frühstücksplatte",
"Frühstückstablett",
"Pfannkuchenstapel",
"Eiscremestand",
"Blechgießkanne",
"Erste-Hilfe-Kasten",
"Blechkanne",
"Onigiri-Boot",
"Geldscheinpyramide",
"Edelstahlkanne",
"Sushiplatte",
"Reissackstapel",
"Hängepflanze",
"Futon",
"Asia-Tee-Set",
"Zaunwinde",
"Weekender",
"Tretroller",
"Bento",
"Getränkepackung",
"Gartentisch",
"Kanister",
"Stapler",
"Absperrhütchen-Set",
"Langhantel",
"Forschungskapsel",
"Aktenschrank L",
"Aktenschrank M",
"Aktenrollwagen",
"Papiertrennwand",
"Holz-Alu-Stuhl",
"Gefängnisgitter",
"Registrierkasse",
"Umkleide",
"Dinohaxe",
"Bewohnerstatue",
"Holzabtropfbrett",
"Sperlingsnest",
"Schwingschaukel",
"LCD-Fernseher",
"Podest",
"Schwebebalken",
"Gymnastikball",
"Tischdeckentisch",
"Geschirr",
"Zeichentisch",
"Garderobe",
"Pastellfernsehtisch",
"Fischschneidebrett",
"Restauranttafel",
"Holztheke",
"Einrad",
"Handtuchständer",
"Holz-Alu-Tisch",
"Rollschrank",
"Metallfahnenstange",
"Maispflanzenreihe",
"Keramikwaschbecken",
"Ball",
"Glastrennwand",
"Zypresse",
"Blumenvitrine",
"Tablettausgabe",
"Gratin",
"Schirmständer",
"Metallkanister",
"Frisiertisch",
"Plastik-Gartenstuhl",
"Einkaufstüte",
"Telefontisch",
"Blumenbeet",
"Sandkasten",
"Plastiktisch",
"Verkehrsschild",
"Handwaschbecken",
"Buchstütze",
"OP-Beistelltisch",
"Klinikbett",
"Profi-Bürostuhl",
"Müll",
"Schulbank",
"Klassenraumtisch",
"Meetingraumtisch",
"Arbeitsschemel",
"Arbeitstisch",
"Mini-Kühlschrank",
"Trage",
"Rollcontainer",
"Wachsmalstiftset",
"Wählscheibentelefon",
"Kabelrolle",
"Baseball-Set",
"Bürouhr",
"Blumenkranz",
"Sukkulente",
"Meetingraumstuhl",
"Münztelefon",
"Make-up-Wagen",
"Geldkassette",
"Fernost-Tisch",
"OP-Tisch",
"Displaytisch",
"Arztpult",
"Tennisschläger",
"Trinkgeldschale",
"Tischmikrofon",
"Reifenstapel",
"Spindwand",
"Gepäckaufbewahrung",
"Rednerpult",
"Geschenkeberg",
"Schulranzen",
"Edelvitrine",
"Popcorn",
"Barhocker",
"Barstuhl",
"Holztrennwand",
"Tablettrückgabe",
"Rundtisch",
"Warteraum-Couch",
"Holzbeistelltisch",
"Metallbeistelltisch",
"Netztrennwand",
"Baumstammtisch",
"Ablagebox",
"Romantikgartenstuhl",
"Romantikgartentisch",
"Kinderteller",
"Wandfernseher",
"Aushang",
"Wasserkrug",
"Hemdstapel",
"Verkaufsautomat",
"Saxofon",
"Spiegelwaschtisch",
"Parfüm-Set",
"Dosenstapel",
"Propan",
"Shoji-Trennwand",
"Bambustrennwand",
"Massagestuhl",
"Fernost-Fass",
"Rezeptionsstuhl",
"Getränkeautomat",
"Marschtrommel",
"Wii U-Konsole",
"Dokumentenstapel",
"Fernost-Stuhl",
"Kinder-Cocktail",
"Sorbet",
"Kinositz",
"Wertstofftonne",
"Pantoffelregal",
"Elektrogrill",
"Ladenkasse",
"Steinofen",
"Handtasche",
"Retro-Mikrofon",
"E-Orgel",
"Holz-Xylofon",
"Trompete",
"Mischpult",
"Küchentheke",
"Industriekühlschrank",
"Holztafel",
"E-Bass",
"Bistrotisch",
"Servierwagen",
"Rezeption",
"Laden-Schild",
"Magazinsammlung",
"Scherenuhr",
"Stifthalter",
"Holzauslage",
"Kunststoffauslage",
"Edelauslage",
"Warenauslage",
"Warenregal",
"Fußboden-Spot",
"Ledersitzbank",
"Lunchbox",
"Tagesmenü",
"Skateboard-Ständer",
"Schreibtisch",
"Abfallkorb",
"Frisierstuhl",
"Fernost-Tischchen",
"Teerose",
"Tasse",
"Schallplattenkiste",
"Damenfahrrad",
"Gitarrenverstärker",
"Videokamera",
"Lautsprecher",
"Spülstation",
"Apothekerschrank",
"Würstchenteller",
"Absperrkette",
"Gartenwerkzeug-Set",
"Werkzeugwagen",
"Fußballtor",
"Elektro-Werbetafel",
"Werbetafel",
"Tischspiegel",
"4er-Spind",
"Gartenwasserhahn",
"Pflanzkasten",
"Gartenstein",
"Gartenfels",
"Funktionalbank",
"Funktionalsessel",
"Funktionaltisch",
"Funktional-TV-Tisch",
"Funktionalleuchte",
"Edelstuhl",
"Edelbank",
"Kleinwagen",
"Cabrio",
"Fischteller",
"Pasta",
"Käseplatte",
"Taco-Teller",
"Asia-Platte",
"Efeuraumteiler",
"Teetasse",
"Reisgericht",
"Zwischenwand",
"Schneide-Set",
"Back-Set",
"Gastro-Herd",
"Glasvitrine",
"Tresen",
"Schmuckkästchen",
"Deko-Ente",
"Naan-Teller",
"Designer-Duschwand",
"Kalligrafie-Deko",
"Schmuckteller",
"Kacheltrennwand",
"Bühnenmonitor",
"Bücherriemen",
"Brettspiel",
"Werkzeugregal",
"Wasch-Set",
"EKG-Gerät",
"Fernost-Schränkchen",
"Lilienstrauß",
"Udon-Suppe",
"Donut-Schachtel",
"Sashimi",
"Wassermelone",
"Hummer-Teller",
"Omelett",
"Paella",
"Retro-Trennwand",
"Bambusbank",
"Bushaltestelle",
"Schuhspindwand",
"Empfangsschalter",
"Servierschale",
"Cupcake",
"Glasteekanne",
"Espressomaschine",
"Bodensitz",
"Wok-Gericht",
"Konsolentisch",
"Rundsitzkissen",
"Schwingsessel",
"Gartenlaterne",
"Badezimmerregal",
"Mofa",
"Folklorekissen",
"Rattanstuhl",
"Fernost-Kissen",
"Papierchaos",
"Teetisch",
,
,
,
,
"Wii U-Software-Regal",
"Nintendo 3DS-Regal",
"amiibo-Regal",
,
"Game Boy-Station",
"Grillspieß",
"Wyvern-Nest",
"Jäger",
"Rotflügel",
"Felyne-Statue",
"Jäger-Wagen",
"Kameradentafel",
"Objektbox",
,
"Nest am Ast",
"Sushi-Bank",
"Gefriertruhe",
"Einkaufskorbständer",
"Supermarktbanner",
"Warmhaltevitrine",
"Kaffeeautomat",
"Riesentorte",
"Lebkuchenhaus",
"Forschungs-Ufo",
"Riesenameise",
"Berg",
"Eisberg",
"Sonne",
"Geldscheinhaufen",
"Riesenschmortopf",
"Kutsche",
"Drehkaffeetasse",
"Riesenteddy",
"Heldenroboter",
"Monitorturm",
"Zelt",
"Propellerflugzeug",
"U-Boot",
"Luxuswagen",
"Riesenei",
"Aufblasfigur",
"Setzling-Uhr",
"Supermuschel",
"Inkopolis-Schild",
"Inkopolis-Tisch",
"Inkopolis-Turm",
"Aufblas-Tintenfisch",
"Inkopolis-Stuhl",
"Tentatek-Kleckser",
"Splatfest-Schild (l)",
"Splatfest-Schild (r)",
"Startpunkt",
"Standfernseher",
"Einsame-Insel-Karte",
"Pfanne",
"Einsaminsel-Tisch",
"Einsaminsel-Hocker",
"Hello-Kitty-Kommode",
"Hello-Kitty-Bäumchen",
"Hello-Kitty-Bett",
"Hello-Kitty-Tisch",
"Hello-Kitty-Stuhl",
"Hello-Kitty-Uhr",
"Hello-Kitty-Uhr",
"My-Melody-Bett",
"My-Melody-Uhr",
"My-Melody-Uhr",
"My-Melody-Stuhl",
"My-Melody-Spiegel",
"My-Melody-Tisch",
"Pompompurin-Bett",
"Pompompurin-Stuhl",
"Pompompurin-Regal",
"Pompompurin-Tisch",
"Pompompurin-Pudding",
"Pompompurin-TV",
"Pompompurin-TV",
"Kiki-&-Lala-Bett",
"Kiki-&-Lala-Uhr",
"Kiki-&-Lala-Uhr",
"Kiki-&-Lala-Tisch",
"Kiki-&-Lala-Sofa",
"Wolkenmaschine",
"Cinnamoroll-Tisch",
"Cinnamoroll-Schirm",
"Cinnamoroll-Sofa",
"Cinnamoroll-Menü",
"Cinnamoroll-Hocker",
"Cinnamoroll-Tablett",
"Teich-Tischchen",
"Teich-Nascherei",
"Teich-Leuchte",
"Teich-Bogenbrücke",
"Teich-Schiebetür",
"Papierpuppe",
"Zierblende HHD",
"Zierblende Melinda",
"Zierblende Tina",
"Zierblende Sina",
"Zierblende K.K.",
"Zierblende S&N",
"ImmoNook-Auto",
"Melinda-Mofa",
"Bombe",
"Feenflasche",
"Hyrule-Schatzkiste",
"Huhn-Ornament",
"Mythenstein",
"Herz",
"Herzcontainer",
"Herzteil",
"Lon Lon-Milch",
"Termina-Mond",
"Hylia-Schild",
"Held-der-Zeit-Rolle",
"Rubin",
"Bus-Miniatur",
"Seemann-Miniatur",
"Nintendo-Bank",
"Chihuahua-Ornament",
"Dalmatiner-Ornament",
"Dackel-Ornament",
"Labrador-Ornament",
"GameCube-Kommode",
"Wii-FB-Hochschrank",
"DS Lite-Bank",
"Nintendo DSi-Bank",
"Lotusteich",
"Supermarktuhr",
"Donut-Kissen",
"Otomon-Ei",
"Navirou-Ornament",
"Fueki-Topf",
"Fueki-Stuhl",
"Fueki-Kommode",
"Fueki-Anlage",
"Fueki-Tisch",
"Puzzleopolis-Kissen",
,
,
,
,
,
"Nähzubehör",
"Quilt-Wandteppich",
"Durianblumenkorb",
"Bananenblumenkorb",
"Ladenschild",
"Einkaufswagendepot",
"Helmkiste",
"Pizzakarton",
"Müllkübel",
"Weltenbummlerkoffer",
,
,
"2017-Kuchen",
"Schneetannenbaum",
"Wälzer",
"Museumsuhr",
"Elektroequipment",
"Riesen-Sterni-Haufen",
"Umsatzprognosetafel",
"ImmoNook-Matte",
"Fundgrubenuhr",
"Fundgrubenmatte",
"Tischlerzubehör",
"Werkzeugaufbewahrung",
"Schubert-Matte",
"Schuhcremeauswahl",
"Schuhputzset",
"Ansagemikrofon",
"Lageplan",
"DJ-K.K.-Bühne",
"Gitarrenkoffer",
"Ladenmatte",
"Museumsmatte",
"ImmoNook-Modellbau",
"Winci-Gemälde",
"Bedienungsanleitung"
],

//Mannequins
[
"Mannequin 1",
"Mannequin 2",
"Mannequin 3",
"Mannequin 4"
],

//Art
[
"Wellengemälde",
"Feierlichgemälde",
"Altertumgemälde",
"Einfachgemälde",
"Berühmtgemälde",
"Perfektgemälde",
"Enormgemälde",
"Hübschgemälde",
"Schöngemälde",
"Bekanntgemälde",
"Blumengemälde",
"Warmgemälde",
"Gemüsegemälde",
"Feingemälde",
"Furchtgemälde",
"Strenggemälde",
"Obstgemälde",
"Wahrgemälde",
"Ruhegemälde",
"Kraftgemälde",
"Perlengemälde",
"Edelgemälde",
"Wintergemälde",
"Ungestümgemälde",
"Anmutsgemälde",
"Eleganzstatue",
"Erhabenstatue",
"Galantstatue",
"Athletenstatue",
"Würdestatue",
"Geheimnisbüste",
"Uraltstatue",
"Mutterstatue",
"Wellengemälde (Fälschung)",
"Feierlichgemälde (Fälschung)",
"Altertumgemälde (Fälschung)",
"Einfachgemälde (Fälschung)",
"Berühmtgemälde (Fälschung)",
"Enormgemälde (Fälschung)",
"Schöngemälde (Fälschung)",
"Gemüsegemälde (Fälschung)",
"Furchtgemälde (Fälschung)",
"Obstgemälde (Fälschung)",
"Perlengemälde (Fälschung)",
"Edelgemälde (Fälschung)",
"Ungestümgemälde (Fälschung)",
"Anmutsgemälde (Fälschung)",
"Eleganzstatue (Fälschung)",
"Erhabenstatue (Fälschung)",
"Galantstatue (Fälschung)",
"Athletenstatue (Fälschung)",
"Würdestatue (Fälschung)",
"Geheimnisbüste (Fälschung)",
"Uraltstatue (Fälschung)",
"Mutterstatue (Fälschung)"
],

//Fossils
[
"Bernstein",
"Ammonit",
"Koprolith",
"Dino-Ei",
"Farnfossil",
"Dino-Fußabdruck",
"Archaeopteryx",
"Pekingmensch",
"Haizahn",
"Trilobit",
"T-Rex-Schädel",
"T-Rex-Torso",
"T-Rex-Schwanz",
"Triceratops-Schädel",
"Triceratops-Torso",
"Triceratops-Schwanz",
"Mammut-Schädel",
"Mammut-Torso",
"Ankylosaurus-Schädel",
"Ankylosaurus-Torso",
"Ankylosaurus-Schwanz",
"Apatosaurus-Schädel",
"Apatosaurus-Torso",
"Apatosaurus-Schwanz",
"Dimetrodon-Schädel",
"Dimetrodon-Torso",
"Dimetrodon-Schwanz",
"Iguanodon-Schädel",
"Iguanodon-Torso",
"Iguanodon-Schwanz",
"Säbelzahn-Schädel",
"Säbelzahn-Torso",
"Pachysaurus-Schädel",
"Pachysaurus-Torso",
"Pachysaurus-Schwanz",
"Parasaurus-Schädel",
"Parasaurus-Torso",
"Parasaurus-Schwanz",
"Seismosaurus-Schädel",
"Seismosaurus-Hals",
"Seismosaurus-Thorax",
"Seismosaurus-Hüfte",
"Seismosaurus-Schwanz",
"Plesiosaurus-Schädel",
"Plesiosaurus-Hals",
"Plesiosaurus-Torso",
"Stegosaurus-Schädel",
"Stegosaurus-Torso",
"Stegosaurus-Schwanz",
"Ptera-Schädel",
"Ptera-Flügel (L)",
"Ptera-Flügel (R)",
"Ichthyo-Schädel",
"Ichthyo-Torso",
"Velociraptor-Schädel",
"Velociraptor-Torso",
"Styraco-Schädel",
"Styraco-Torso",
"Styraco-Schwanz",
"Spinosaurus-Schädel",
"Spinosaurus-Torso",
"Spinosaurus-Schwanz",
"Megacerops-Schädel",
"Megacerops-Torso",
"Megacerops-Schwanz",
"Archelon-Schädel",
"Archelon-Torso",
"T-Rex-Modell",
"Triceratops-Modell",
"Mammut-Modell",
"Ankylosaurus-Modell",
"Apatosaurus-Modell",
"Dimetrodon-Modell",
"Iguanodon-Modell",
"Säbelzahn-Modell",
"Pachysaurus-Modell",
"Parasaurus-Modell",
"Seismosaurus-Modell",
"Plesiosaurus-Modell",
"Stegosaurus-Modell",
"Pteranodon-Modell",
"Ichthyosaurus-Modell",
"Velociraptor-Modell",
"Styracosaurus-Modell",
"Spinosaurus-Modell",
"Megacerops-Modell",
"Archelon-Modell"
],

//Pics
[
"Foto von Theo",
"Foto von Siggi",
"Foto von Mathilda",
"Foto von Annabell",
"Foto von Hilde",
"Foto von Annalena",
"Foto von Olaf",
"Foto von Torsten",
"Foto von Pia",
"Foto von Kurt",
"Foto von Chang",
"Foto von Nathan",
"Foto von Ernst",
"Foto von Mandy",
"Foto von Ursula",
"Foto von Gerald",
"Foto von Paula",
"Foto von Ike",
"Foto von Tabea",
"Foto von Berthold",
"Foto von Grischa",
"Foto von Jan",
"Foto von Jule",
"Foto von Armin",
"Foto von Twiggy",
"Foto von Alex",
"Foto von Iris",
"Foto von Ansgar",
"Foto von Anna",
"Foto von Jesko",
"Foto von Lukas",
"Foto von Pierre",
"Foto von Picko",
"Foto von Nestor",
"Foto von Medolie",
"Foto von Angus",
"Foto von Toro",
"Foto von Carlos",
"Foto von Marius",
"Foto von Arnold",
"Foto von Klaus",
"Foto von Jens",
"Foto von Miezi",
"Foto von Sophie",
"Foto von Bianca",
"Foto von Kiki",
"Foto von Tanja",
"Foto von Julian",
"Foto von Franka",
"Foto von Tristan",
"Foto von Kabuki",
"Foto von Pit",
"Foto von Monique",
"Foto von Zita",
"Foto von Stefan",
"Foto von Karen",
"Foto von Timo",
"Foto von Mischka",
"Foto von Minka",
"Foto von Feline",
"Foto von Kleo",
"Foto von Heinz",
"Foto von Janine",
"Foto von Felyne",
"Foto von Birte",
"Foto von Mona",
"Foto von Toni",
"Foto von Bertram",
"Foto von Bernd",
"Foto von Berry",
"Foto von Vladimir",
"Foto von Michael",
"Foto von Linda",
"Foto von Claudia",
"Foto von Juna",
"Foto von Sandrine",
"Foto von Eduard",
"Foto von Hubert",
"Foto von Tatjana",
"Foto von Marty",
"Foto von Konrad",
"Foto von Benedikt",
"Foto von Waldemar",
"Foto von Gisela",
"Foto von Inga",
"Foto von Mareile",
"Foto von Tschiwi",
"Foto von Elfriede",
"Foto von Hannes",
"Foto von Patricia",
"Foto von Angela",
"Foto von Nelly",
"Foto von Jolanda",
"Foto von Markus",
"Foto von Ali",
"Foto von Tilmann",
"Foto von Krokki",
"Foto von Steve",
"Foto von Rosa",
"Foto von Frederick",
"Foto von Fatima",
"Foto von Benjamin",
"Foto von Walter",
"Foto von Oswald",
"Foto von Dina",
"Foto von Eckart",
"Foto von Selina",
"Foto von Martin",
"Foto von Vroni",
"Foto von Erik",
"Foto von Chelsea",
"Foto von Bienchen",
"Foto von Hasso",
"Foto von Viktor",
"Foto von Keks",
"Foto von Strolch",
"Foto von Isolde",
"Foto von Fido",
"Foto von Doris",
"Foto von Rosi",
"Foto von Agnes",
"Foto von Bea",
"Foto von Wuffi",
"Foto von Ronaldo",
"Foto von Wastl",
"Foto von Bella",
"Foto von Thomas",
"Foto von Bill",
"Foto von Kalle",
"Foto von Daune",
"Foto von Sissi",
"Foto von Olivia",
"Foto von Erika",
"Foto von Marina",
"Foto von Quacks",
"Foto von Erwin",
"Foto von Gustav",
"Foto von Helmut",
"Foto von Volker",
"Foto von Tanya",
"Foto von Pullunda",
"Foto von Gustavia",
"Foto von Monika",
"Foto von Quentin",
"Foto von Olga",
"Foto von Bastian",
"Foto von Benni",
"Foto von Frauke",
"Foto von Elisa",
"Foto von Paolo",
"Foto von Axel",
"Foto von Elfi",
"Foto von Thorsten",
"Foto von Eleonore",
"Foto von Chai",
"Foto von Liliane",
"Foto von Robbi",
"Foto von Fritz",
"Foto von Tarno",
"Foto von Caspar",
"Foto von Warzi",
"Foto von Nele",
"Foto von Jörg",
"Foto von Paul",
"Foto von Jacques",
"Foto von Knuth",
"Foto von Prinz",
"Foto von Jeanette",
"Foto von Sani",
"Foto von Violetta",
"Foto von Carlo",
"Foto von Dörte",
"Foto von Freddy",
"Foto von Anette",
"Foto von Zenobi",
"Foto von Hennes",
"Foto von Gregor",
"Foto von Wilma",
"Foto von Bocki",
"Foto von Pamela",
"Foto von Alfredo",
"Foto von Manfred",
"Foto von Kong",
"Foto von Ludwig",
"Foto von Boyd",
"Foto von Konga",
"Foto von Kokong",
"Foto von Katrin",
"Foto von Hans",
"Foto von Rilla",
"Foto von Hamid",
"Foto von Jessi",
"Foto von Günther",
"Foto von Reinhold",
"Foto von Samira",
"Foto von Dietmar",
"Foto von Emilie",
"Foto von Heinrich",
,
"Foto von Richi",
"Foto von Christin",
"Foto von Berta",
"Foto von Norbert",
"Foto von Biggi",
"Foto von Jürgen",
"Foto von Herbert",
"Foto von Rudi",
"Foto von Emma",
"Foto von Zara",
"Foto von Emil",
"Foto von Jolly",
"Foto von Walli",
"Foto von Hermann",
"Foto von Birgit",
"Foto von Claire",
"Foto von Annerose",
"Foto von Tommi",
"Foto von Carsten",
"Foto von Friedel",
"Foto von Jimmy",
,
"Foto von Epona",
"Foto von Ute",
"Foto von Konny",
"Foto von Kornelia",
"Foto von Silke",
"Foto von Heribert",
"Foto von Oskar",
"Foto von Caroline",
"Foto von Pepe",
"Foto von Sunny",
"Foto von Kerstin",
"Foto von Marga",
"Foto von Carola",
"Foto von Astrid",
"Foto von Sylvia",
"Foto von Sinan",
"Foto von Robert",
"Foto von Marlies",
"Foto von Dieter",
"Foto von Leonardo",
"Foto von Rex",
"Foto von Leandro",
"Foto von Leonhard",
"Foto von Leon",
"Foto von Lorenz",
"Foto von Dorothea",
"Foto von Simon",
"Foto von Bonni",
"Foto von Daniel",
"Foto von Steffi",
"Foto von Pippo",
"Foto von Uta",
"Foto von Anton",
"Foto von Dora",
"Foto von Rafael",
"Foto von Susi",
"Foto von Jenny",
"Foto von Samson",
"Foto von Manni",
"Foto von Renate",
"Foto von Ricky",
"Foto von Eva",
"Foto von Fritzi",
"Foto von Mausbert",
"Foto von Schoki",
"Foto von Gretel",
"Foto von Penelope",
"Foto von Charlie",
"Foto von Ottfried",
"Foto von Marianne",
"Foto von Ottokar",
"Foto von Klecks",
"Foto von Isabella",
"Foto von Sandra",
"Foto von Senta",
"Foto von Lutz",
"Foto von Julia",
"Foto von Guido",
"Foto von Ingo",
"Foto von Christa",
"Foto von Flora",
"Foto von Philippa",
"Foto von Apollo",
"Foto von Adelheid",
"Foto von Adrian",
"Foto von Balduin",
"Foto von Quetzal",
"Foto von Arthur",
"Foto von Horst",
"Foto von Kai",
"Foto von Lora",
"Foto von Sonja",
"Foto von Roland",
"Foto von Cube",
"Foto von Hauke",
"Foto von Frieda",
"Foto von Judith",
"Foto von Puck",
"Foto von Staksi",
"Foto von Max",
"Foto von Pingi",
"Foto von Matze",
"Foto von Susanne",
"Foto von Svenja",
"Foto von Oink",
"Foto von Luzie",
"Foto von Ede",
"Foto von Hugo",
"Foto von Larissa",
"Foto von Schwarte",
"Foto von Rolo",
"Foto von Bolle",
"Foto von Magda",
"Foto von Quiekie",
"Foto von Oinka",
"Foto von Clemens",
"Foto von Kevin",
"Foto von Brigitte",
"Foto von Nora",
"Foto von Ganon",
"Foto von Mimmi",
"Foto von Doro",
"Foto von Koko",
"Foto von Philip",
"Foto von Gaston",
"Foto von Gabi",
"Foto von Lotta",
"Foto von Michelle",
"Foto von Aki",
"Foto von Rubina",
"Foto von Gustl",
"Foto von Claude",
"Foto von Manu",
"Foto von Anne",
"Foto von Poldi",
"Foto von Nico",
"Foto von Hilda",
"Foto von Henrike",
"Foto von Karl",
"Foto von Mira",
"Foto von Toby",
"Foto von Frank",
"Foto von Regina",
"Foto von Atze",
"Foto von Rüdiger",
"Foto von Maria",
"Foto von Ilona",
"Foto von Dolly",
"Foto von Babsi",
"Foto von Edith",
"Foto von Stella",
"Foto von Lana",
"Foto von Natascha",
"Foto von Locke",
"Foto von Wolli",
"Foto von Tippsi",
"Foto von Martina",
"Foto von Marion",
"Foto von Pietro",
"Foto von Etoile",
"Foto von Paulina",
"Foto von Klara",
"Foto von Felix",
"Foto von Noisette",
"Foto von Knuspi",
"Foto von Karin",
"Foto von Ricarda",
"Foto von Hanne",
"Foto von Rudolf",
"Foto von Marika",
"Foto von Ronny",
"Foto von Hörnchen",
"Foto von Natalja",
"Foto von Maren",
"Foto von Trita",
"Foto von Steffen",
"Foto von Huschke",
"Foto von Nadine",
"Foto von A-Chan",
"Foto von L-Pyon",
"Foto von Boris",
"Foto von Gisbert",
"Foto von Arne",
"Foto von Tamara",
"Foto von Tim",
"Foto von Lilly",
"Foto von Bettina",
"Foto von Sascha",
"Foto von Lupo",
"Foto von Weber",
"Foto von Lupa",
"Foto von Sigmund",
"Foto von Freya",
"Foto von Grimm",
"Foto von Viviane",
"Foto von Sabine",
"Foto von Wolfgang",
"Foto von Wolf-Link"
],

//Pics (special)
[
"Foto von Blanka",
"Foto von Ohs",
"Foto von Chris",
"Foto von Resetti",
"Foto von Don",
"Foto von Katja",
"Foto von K.K."
],

//Pics (special)
[
"Foto von Björn",
"Foto von Rosina",
"Foto von Bartholo",
"Foto von Helios",
"Foto von Sigrid",
"Foto von Smeralda",
"Foto von Carleon",
"Foto von Aziza",
"Foto von K.K.",
"Foto von Reiner",
"Foto von Grazia",
"Foto von Samthea",
"Foto von Tina",
"Foto von Sina",
"Foto von Bonnie",
"Foto von Lore",
"Foto von Käpten",
"Foto von Lotte",
"Foto von Schlepp",
"Foto von Nepp",
"Foto von Flip",
"Foto von Don",
"Foto von Resetti",
"Foto von Fred",
"Foto von Eugen",
"Foto von Eufemia",
"Foto von Pavo",
"Foto von Pelly",
"Foto von Peggy",
"Foto von Kofi",
"Foto von Jakob",
"Foto von Wuff",
"Foto von Peter",
"Foto von Harry",
"Foto von Trude",
"Foto von Tom Nook",
"Foto von Gulliver",
"Foto von Johannes",
"Foto von Schubert",
"Foto von Melinda",
"Foto von Törtel",
"Foto von Gernod",
"Foto von Samselt",
"Foto von Olli",
"Foto von Gerd",
"Foto von Blanka",
"Foto von Serenada",
"Foto von DJ K.K.",
"Foto von Katja",
"Foto von Ohs",
"Foto von Chris",
"Foto von Moritz",
"Foto von Winci",
"Foto von Karlotta"
],

//Tools & wearables
[
"Leihaxt",
"Axt",
"Silberaxt",
"Goldaxt",
"Leihkescher",
"Kescher",
"Silberkescher",
"Goldkescher",
"Leihangel",
"Angel",
"Silberangel",
"Goldangel",
"Leihschaufel",
"Schaufel",
"Silberschaufel",
"Goldschaufel",
"Leihgießkanne",
"Gießkanne",
"Silberkanne",
"Goldkanne",
"Leihschleuder",
"Schleuder",
"Silberschleuder",
"Goldschleuder",
"Leihhammer",
"Quietschehammer",
"Megafon",
"Stoppuhr",
"Wunderkerze",
"Römerkerze",
"Partyknaller",
"Seifenblasenset",
"Hasenballon (rot)",
"Hasenballon (orange)",
"Hasenballon (gelb)",
"Hasenballon (grün)",
"Hasenballon (türkis)",
"Hasenballon (blau)",
"Hasenballon (lila)",
"Hasenballon (rosa)",
"Ballon (rot)",
"Ballon (orange)",
"Ballon (gelb)",
"Ballon (grün)",
"Ballon (türkis)",
"Ballon (blau)",
"Ballon (lila)",
"Ballon (rosa)",
"Herzballon (rot)",
"Herzballon (orange)",
"Herzballon (gelb)",
"Herzballon (grün)",
"Herzballon (türkis)",
"Herzballon (blau)",
"Herzballon (lila)",
"Herzballon (rosa)",
"Windrad (rot)",
"Windrad (orange)",
"Windrad (gelb)",
"Windrad (grün)",
"Windrad (türkis)",
"Windrad (blau)",
"Windrad (lila)",
"Windrad (rosa)"
],

//Uncategorized 2
[
"Kaffeebecher",
"Apfelschorle",
"Bohnenkörbchen",
"Sushi-Rolle",
"Vanille-Softeis",
"Schoko-Softeis",
"Pfefferminz-Softeis",
"Erdbeer-Softeis",
"Vanilleeis",
"Erdbeereis",
"Zitrone-Minz-Eis",
"Erdbeer-Minz-Eis",
"Leuchtstab (blau)",
"Leuchtstab (grün)",
"Leuchtstab (rosa)",
"Leuchtstab (gelb)",
"Blumenelfenstab",
"Kiki-&-Lala-Stab",
"Tröte",
"Fontäne",
"Fontäne (abgebrannt)",
"Geschenkesack",
"Sack",
"Standard-Kaffee",
"Qualitäts-Kaffee",
"Premium-Kaffee",
"Schokoladentaler"],

//Uncategorized 3
[
"Unterschriftenliste",
"Unterschriftenliste",
"Altpapier",
"Fundsache (Buch)",
"Fundsache (Stoffbeutel)",
"Fundsache (Einzelhandschuh)",
"Fundsache (Papiertüte)",
"Waschlappen"
],

//Fortune cookies
[
"Glückskeks",
"Glückszettel Nr. 1",
"Glückszettel Nr. 2",
"Glückszettel Nr. 3",
"Glückszettel Nr. 4",
"Glückszettel Nr. 5",
"Glückszettel Nr. 6",
"Glückszettel Nr. 7",
"Glückszettel Nr. 8",
"Glückszettel Nr. 9",
"Glückszettel Nr. 10",
"Glückszettel Nr. 11",
"Glückszettel Nr. 12",
"Glückszettel Nr. 13",
"Glückszettel Nr. 14",
"Glückszettel Nr. 15",
"Glückszettel Nr. 16",
"Glückszettel Nr. 17",
"Glückszettel Nr. 18",
"Glückszettel Nr. 19",
"Glückszettel Nr. 20",
"Glückszettel Nr. 21",
"Glückszettel Nr. 22",
"Glückszettel Nr. 23",
"Glückszettel Nr. 24",
"Glückszettel Nr. 25",
"Glückszettel Nr. 26",
"Glückszettel Nr. 27",
"Glückszettel Nr. 28",
"Glückszettel Nr. 29",
"Glückszettel Nr. 30",
"Glückszettel Nr. 31",
"Glückszettel Nr. 32",
"Glückszettel Nr. 33",
"Glückszettel Nr. 34",
"Glückszettel Nr. 35",
"Glückszettel Nr. 36",
"Glückszettel Nr. 37",
"Glückszettel Nr. 38",
"Glückszettel Nr. 39",
"Glückszettel Nr. 40",
"Glückszettel Nr. 41",
"Glückszettel Nr. 42",
"Glückszettel Nr. 43",
"Glückszettel Nr. 44",
"Glückszettel Nr. 45",
"Glückszettel Nr. 46",
"Glückszettel Nr. 47",
"Glückszettel Nr. 48",
"Glückszettel Nr. 49",
"Glückszettel Nr. 50"
],

//Fortune cookies
[
"Glückskeks",
"Glückszettel Nr. 1",
"Glückszettel Nr. 2",
"Glückszettel Nr. 3",
"Glückszettel Nr. 46",
"Glückszettel Nr. 5",
"Glückszettel Nr. 49",
"Glückszettel Nr. 7",
"Glückszettel Nr. 8",
"Glückszettel Nr. 9",
"Glückszettel Nr. 10",
"Glückszettel Nr. 11",
"Glückszettel Nr. 12",
"Glückszettel Nr. 13",
"Glückszettel Nr. 14",
"Glückszettel Nr. 15",
"Glückszettel Nr. 50",
"Glückszettel Nr. 17",
"Glückszettel Nr. 18",
"Glückszettel Nr. 19",
"Glückszettel Nr. 20",
"Glückszettel Nr. 21",
"Glückszettel Nr. 22",
"Glückszettel Nr. 23",
"Glückszettel Nr. 24",
"Glückszettel Nr. 25",
"Glückszettel Nr. 26",
"Glückszettel Nr. 27",
"Glückszettel Nr. 28",
"Glückszettel Nr. 29",
"Glückszettel Nr. 48",
"Glückszettel Nr. 31",
"Glückszettel Nr. 32",
"Glückszettel Nr. 33",
"Glückszettel Nr. 34",
"Glückszettel Nr. 35",
"Glückszettel Nr. 36",
"Glückszettel Nr. 37",
"Glückszettel Nr. 47",
"Glückszettel Nr. 39",
"Glückszettel Nr. 40",
"Glückszettel Nr. 41",
"Glückszettel Nr. 42",
"Glückszettel Nr. 43",
"Glückszettel Nr. 44",
"Glückszettel Nr. 45",
"Glückszettel Nr. 4",
"Glückszettel Nr. 38",
"Glückszettel Nr. 30",
"Glückszettel Nr. 6",
"Glückszettel Nr. 16",
"Glückszettel Nr. 51",
"Glückszettel Nr. 52",
"Glückszettel Nr. 53",
"Glückszettel Nr. 54",
"Glückszettel Nr. 55",
"Glückszettel Nr. 56",
"Glückszettel Nr. 57"
],

//Tickets
[
"Lotteriekeks",
"Lotterie-Niete",
"Lotterielos A",
"Lotterielos B",
"Lotterielos C",
"Lotterielos D",
"Lotterielos E",
"Lotterielos F",
"Lotterielos G",
"Lotterielos H"
],

//In-game events
[
"Glücksfünf-Karte",
"Glücksfünf-Altkarte",
"Zeitkapsel",
"Suchliste"
],

//Unused furniture (only inside)
[],

//HRA exhibition (only inside)
[
"Rotbriefkasten",
"Metallbriefkasten",
"Blaubriefkasten",
"Gelbbriefkasten",
"Orangebriefkasten",
"Grünbriefkasten",
"Goldbriefkasten",
"Holzbriefkasten",
"Weißbriefkasten",
"Rosabriefkasten",
"Samuraibriefkasten",
"Kartonbriefkasten",
"Stahlbriefkasten",
"Rotlackbriefkasten",
"Hellblaubriefkasten",
"Türkisbriefkasten",
"Nixenbriefkasten",
"Korbbriefkasten",
"Märchenbriefkasten",
"Royalbriefkasten",
"Fassbriefkasten",
"Süßbriefkasten",
"Rundfenster-Bogentür",
"Fisch-Bogentür",
"Astro-Bogentür",
"Fenster-Bogentür",
"Gelb-Bogentür",
"Eisen-Bogentür",
"Kaputt-Bogentür",
"Süß-Bogentür",
"Nixen-Bogentür",
"Samurai-Bogentür",
"Blockhaus-Bogentür",
"Märchen-Bogentür",
"Braun-Bogentür",
"Grün-Bogentür",
"Massiv-Bogentür",
"Blau-Bogentür",
"Birkenholz-Bogentür",
"Fernost-Bogentür",
"Pink-Bogentür",
"Kinder-Bogentür",
"Bambus-Bogentür",
"Gold-Bogentür",
"Rundfenstertür",
"Fischtür",
"Astrotür",
"Fenstertür",
"Gelbtür",
"Eisentür",
"Kaputt-Tür",
"Süßtür",
"Nixentür",
"Samuraitür",
"Blockhaustür",
"Märchentür",
"Brauntür",
"Grüntür",
"Massivtür",
"Blautür",
"Birkenholztür",
"Fernost-Tür",
"Pinktür",
"Kindertür",
"Bambustür",
"Rotdach",
"Grünziegeldach",
"Blau-Schindeldach",
"Astrodach",
"Kinderdach",
"Schwarzplattendach",
"Strohdach",
"Schwarzziegeldach",
"Märchendach",
"Western-Dach",
"Blechdach",
"Betondach",
"Süßdach",
"Weißdach",
"Lilaschindeldach",
"Reetdach",
"Nixendach",
"Blauplattendach",
"Liladach",
"Rosadach",
"Schwarzdach",
"Goldgelbdach",
"Pinkdach",
"Schwarzschindeldach",
"Braundach",
"Grasdach",
"Steindach",
"Grün-Märchendach",
"Natursteindach",
"Grünplattendach",
"Grauplattendach",
"Golddach",
"Blaudach",
"Gelbdach",
"Gründach",
"Seilzaun",
"Weißzaun",
"Baumstammzaun",
"Hecke",
"Rosa-Nixenzaun",
"Blau-Nixenzaun",
"Klinkermauer",
"Backsteinmauer",
"Pinkzaun",
"Märchenzaun",
"Weidenzaun",
"Lattenzaun",
"Blauzaun",
"Prachtzaun",
"Samuraimauer",
"Stacheldrahtzaun",
"Süßmauer",
"Betonmauer",
"Blechzaun",
"Bambuszaun",
"Buchsbaumhecke",
"Betonsteinmauer",
"Goldzaun",
"Backsteinfassade",
"Orient-Fassade",
"Granitfassade",
"Astrofassade",
"Kinderfassade",
"Schlichtfassade",
"Korbfassade",
"Samuraifassade",
"Märchenfassade",
"Blockhausfassade",
"Blechfassade",
"Betonfassade",
"Süßfassade",
"Tünchfassade",
"Fachwerkfassade",
"Klinkerfassade",
"Nixenfassade",
"Scheunenfassade",
"Buntfassade",
"Pinkfassade",
"Blaufassade",
"Orangefassade",
"Blumenmusterfassade",
"Gelbholzfassade",
"Weißholzfassade",
"Lehmfassade",
"Steinfassade",
"Ornamentfassade",
"Feldsteinfassade",
"Royalfassade",
"Schwarzholzfassade",
"Goldfassade",
"Buntkiesweg",
"Feldsteinweg",
"Ziegelweg",
"Kiesweg",
"Grünfliesenweg",
"Betonweg",
"Blauziegelweg",
"Rotfliesenweg",
"Sandsteinweg",
"Villa",
"Samuraischloss",
"Schloss",
"Designerhaus"
],

//Presents
[],

//New furniture (update)
[
"Zauberlampe",
,
,
,
"Floßtrophäe"
]];